package github.kasuminova.ssoptimizer.mapping;

/**
 * 游戏与外部运行时类的可读命名常量表。
 * <p>
 * 该表只暴露开发侧应当看到的 named 名称，禁止在业务或注入源码中继续散落
 * 混淆类名字符串。外部类必须保留上游命名空间，只做语义化去混淆，不得映射进
 * {@code github/kasuminova/ssoptimizer/**}。
 */
public final class GameClassNames {
    public static final String SPRITE                              = "com/fs/graphics/Sprite";
    public static final String SPRITE_DOTTED                       = "com.fs.graphics.Sprite";
    public static final String ENGINE                              = "com/fs/starfarer/combat/entities/Engine";
    public static final String ENGINE_STATE                        = "com/fs/starfarer/combat/entities/Engine$EngineState";
    public static final String ENGINE_GLOW_TYPE                    = "com/fs/starfarer/combat/entities/Engine$EngineGlowType";
    public static final String ENGINE_OWNER                        = "com/fs/starfarer/combat/entities/ship/ShipEngineController$EngineOwner";
    public static final String SHIP                                = "com/fs/starfarer/combat/entities/Ship";
    public static final String ENGINE_SLOT                         = "com/fs/starfarer/loading/specs/EngineSlot";
    public static final String CONTRAIL_GROUP                      = "com/fs/starfarer/combat/entities/ContrailEngine$ContrailGroup";
    public static final String CONTRAIL_SEGMENT                    = "com/fs/starfarer/combat/entities/ContrailEngine$ContrailSegment";
    public static final String ENGINE_DOTTED                       = "com.fs.starfarer.combat.entities.Engine";
    public static final String ENGINE_STATE_DOTTED                 = "com.fs.starfarer.combat.entities.Engine$EngineState";
    public static final String ENGINE_GLOW_TYPE_DOTTED             = "com.fs.starfarer.combat.entities.Engine$EngineGlowType";
    public static final String ENGINE_OWNER_DOTTED                 = "com.fs.starfarer.combat.entities.ship.ShipEngineController$EngineOwner";
    public static final String SHIP_DOTTED                         = "com.fs.starfarer.combat.entities.Ship";
    public static final String ENGINE_SLOT_DOTTED                  = "com.fs.starfarer.loading.specs.EngineSlot";
    public static final String CONTRAIL_GROUP_DOTTED               = "com.fs.starfarer.combat.entities.ContrailEngine$ContrailGroup";
    public static final String CONTRAIL_SEGMENT_DOTTED             = "com.fs.starfarer.combat.entities.ContrailEngine$ContrailSegment";
    public static final String BITMAP_FONT_RENDERER                = "com/fs/graphics/font/BitmapFontRenderer";
    public static final String BITMAP_FONT_RENDERER_DOTTED         = "com.fs.graphics.font.BitmapFontRenderer";
    public static final String BITMAP_GLYPH                        = "com/fs/graphics/font/BitmapGlyph";
    public static final String BITMAP_FONT                         = "com/fs/graphics/font/BitmapFont";
    public static final String BITMAP_FONT_MANAGER                 = "com/fs/graphics/font/BitmapFontManager";
    public static final String TEXTURED_STRIP_RENDERER             = "com/fs/starfarer/renderers/TexturedStripRenderer";
    public static final String TEXTURED_STRIP_RENDERER_DOTTED      = "com.fs.starfarer.renderers.TexturedStripRenderer";
    public static final String CONTRAIL_ENGINE                     = "com/fs/starfarer/combat/entities/ContrailEngine";
    public static final String CONTRAIL_ENGINE_DOTTED              = "com.fs.starfarer.combat.entities.ContrailEngine";
    public static final String COLLISION_GRID_QUERY                = "com/fs/starfarer/combat/CollisionGridQuery";
    public static final String COLLISION_GRID_QUERY_DOTTED         = "com.fs.starfarer.combat.CollisionGridQuery";
    public static final String SHIELD                              = "com/fs/starfarer/combat/systems/Shield";
    public static final String SHIELD_DOTTED                       = "com.fs.starfarer.combat.systems.Shield";
    public static final String TESSELATOR                          = "com/fs/starfarer/util/Tesselator";
    public static final String TESSELATOR_DOTTED                   = "com.fs.starfarer.util.Tesselator";
    public static final String COMBAT_STATE                        = "com/fs/starfarer/combat/CombatState";
    public static final String COMBAT_STATE_DOTTED                 = "com.fs.starfarer.combat.CombatState";
    public static final String COMBAT_ENGINE                       = "com/fs/starfarer/combat/CombatEngine";
    public static final String COMBAT_ENGINE_DOTTED                = "com.fs.starfarer.combat.CombatEngine";
    public static final String DECAL_RENDERER                      = "com/fs/starfarer/renderers/damage/DecalRenderer";
    public static final String DECAL_RENDERER_DOTTED               = "com.fs.starfarer.renderers.damage.DecalRenderer";
    public static final String WEAPON_DAMAGE_EFFECT                = "com/fs/starfarer/combat/entities/ship/WeaponDamageEffect";
    public static final String WEAPON_DAMAGE_EFFECT_DOTTED         = "com.fs.starfarer.combat.entities.ship.WeaponDamageEffect";
    public static final String CUSTOM_COMBAT_ENTITY                = "com/fs/starfarer/combat/entities/CustomCombatEntity";
    public static final String CUSTOM_COMBAT_ENTITY_DOTTED         = "com.fs.starfarer.combat.entities.CustomCombatEntity";
    public static final String SMOOTH_PARTICLE                     = "com/fs/graphics/particle/SmoothParticle";
    public static final String SMOOTH_PARTICLE_DOTTED              = "com.fs.graphics.particle.SmoothParticle";
    public static final String BASE_PARTICLE                       = "com/fs/graphics/particle/BaseParticle";
    public static final String DETAILED_SMOKE_PARTICLE             = "com/fs/starfarer/renderers/fx/DetailedSmokeParticle";
    public static final String DETAILED_SMOKE_PARTICLE_DOTTED      = "com.fs.starfarer.renderers.fx.DetailedSmokeParticle";
    public static final String GENERIC_TEXTURE_PARTICLE            = "com/fs/graphics/particle/GenericTextureParticle";
    public static final String GENERIC_TEXTURE_PARTICLE_DOTTED     = "com.fs.graphics.particle.GenericTextureParticle";
    public static final String SMOKE_PARTICLE_DOTTED               = "com.fs.graphics.particle.SmokeParticle";
    public static final String NEBULA_PARTICLE_DOTTED              = "com.fs.graphics.particle.NebulaParticle";
    public static final String NEGATIVE_PARTICLE_DOTTED            = "com.fs.graphics.particle.NegativeParticle";
    public static final String STARFARER_LAUNCHER                  = "com/fs/starfarer/StarfarerLauncher";
    public static final String FOCUSED_COMPONENT_TRACKER           = "com/fs/starfarer/ui/FocusedComponentTracker";
    public static final String FOCUSED_COMPONENT                   = "com/fs/starfarer/ui/FocusedComponent";
    public static final String INPUT_EVENT                         = "com/fs/starfarer/util/InputEvent";
    public static final String PARALLEL_IMAGE_PRELOADER            = "com/fs/graphics/ParallelImagePreloader";
    public static final String PARALLEL_IMAGE_PRELOADER_DOTTED     = "com.fs.graphics.ParallelImagePreloader";
    public static final String TEXTURE_MANAGER                     = "com/fs/graphics/TextureManager";
    public static final String TEXTURE_MANAGER_DOTTED              = "com.fs.graphics.TextureManager";
    public static final String TEXTURE_LOADER                      = "com/fs/graphics/TextureLoader";
    public static final String TEXTURE_OBJECT                      = "com/fs/graphics/TextureObject";
    public static final String TEXTURE_OBJECT_DOTTED               = "com.fs.graphics.TextureObject";
    public static final String SOUND_MANAGER                       = "sound/SoundManager";
    public static final String SOUND_MANAGER_DOTTED                = "sound.SoundManager";
    public static final String RENDER_STATE_UTILS                  = "com/fs/graphics/util/RenderStateUtils";
    public static final String RENDER_STATE_UTILS_DOTTED           = "com.fs.graphics.util.RenderStateUtils";
    public static final String LOADING_UTILS                       = "com/fs/starfarer/loading/LoadingUtils";
    public static final String LOADING_UTILS_DOTTED                = "com.fs.starfarer.loading.LoadingUtils";
    public static final String STARFARER_SETTINGS                  = "com/fs/starfarer/settings/StarfarerSettings";
    public static final String STARFARER_SETTINGS_DOTTED           = "com.fs.starfarer.settings.StarfarerSettings";
    public static final String BASE_TILED_TERRAIN                  = "com/fs/starfarer/api/impl/campaign/terrain/BaseTiledTerrain";
    public static final String BASE_TILED_TERRAIN_DOTTED           = "com.fs.starfarer.api.impl.campaign.terrain.BaseTiledTerrain";
    public static final String HYPERSPACE_AUTOMATON                = "com/fs/starfarer/api/impl/campaign/terrain/HyperspaceAutomaton";
    public static final String HYPERSPACE_AUTOMATON_DOTTED         = "com.fs.starfarer.api.impl.campaign.terrain.HyperspaceAutomaton";
    public static final String CAMPAIGN_SAVE_PROGRESS_DIALOG       = "com/fs/starfarer/campaign/save/CampaignSaveProgressDialog";
    public static final String CAMPAIGN_SAVE_PROGRESS_DIALOG_DOTTED = "com.fs.starfarer.campaign.save.CampaignSaveProgressDialog";
    public static final String SAVE_PROGRESS_OUTPUT_STREAM         = "com/fs/starfarer/util/SaveProgressOutputStream";
    public static final String SAVE_PROGRESS_OUTPUT_STREAM_DOTTED  = "com.fs.starfarer.util.SaveProgressOutputStream";
    public static final String MARKET                              = "com/fs/starfarer/campaign/econ/Market";
    public static final String MARKET_DOTTED                       = "com.fs.starfarer.campaign.econ.Market";
    public static final String COMMODITY_ON_MARKET                 = "com/fs/starfarer/campaign/econ/CommodityOnMarket";
    public static final String COMMODITY_ON_MARKET_DOTTED          = "com.fs.starfarer.campaign.econ.CommodityOnMarket";
    public static final String CAMPAIGN_LOCATION_MAP_CANVAS        = "com/fs/starfarer/coreui/CampaignLocationMapCanvas";
    public static final String CAMPAIGN_LOCATION_MAP_CANVAS_DOTTED = "com.fs.starfarer.coreui.CampaignLocationMapCanvas";
    public static final String LINUX_DISPLAY                       = "org/lwjgl/opengl/LinuxDisplay";
    public static final String LINUX_EVENT                         = "org/lwjgl/opengl/LinuxEvent";
    public static final String LINUX_EVENT_DOTTED                  = "org.lwjgl.opengl.LinuxEvent";
    public static final String LINUX_KEYBOARD                      = "org/lwjgl/opengl/LinuxKeyboard";
    public static final String STANDARD_TOOLTIP_V2_EXPANDABLE      = "com/fs/starfarer/ui/impl/StandardTooltipV2Expandable";
    public static final String STARFARER_SETTINGS_TEXT_FIELD_OWNER = "com/fs/starfarer/settings/StarfarerSettings$SettingsTextFieldFactory";
    public static final String TEXT_FIELD_IMPL                     = "com/fs/starfarer/ui/TextFieldImpl";
    public static final String TEXT_FIELD_API                      = "com/fs/starfarer/api/ui/TextFieldAPI";
    public static final String RESOURCE_LOADER                     = "com/fs/util/ResourceLoader";
    public static final String RESOURCE_LOADER_DOTTED              = "com.fs.util.ResourceLoader";
    public static final String RESOURCE_LOADER_STATE_DOTTED        = "com.fs.starfarer.loading.ResourceLoaderState";
    public static final String SPEC_STORE_DOTTED                   = "com.fs.starfarer.loading.SpecStore";
    public static final String CAMPAIGN_ENGINE                     = "com/fs/starfarer/campaign/CampaignEngine";
    public static final String CAMPAIGN_ENGINE_DOTTED              = "com.fs.starfarer.campaign.CampaignEngine";
    public static final String TITLE_SCREEN_STATE                  = "com/fs/starfarer/title/TitleScreenState";
    public static final String TITLE_SCREEN_STATE_DOTTED           = "com.fs.starfarer.title.TitleScreenState";
    public static final String TASK_ICON_MANAGER                   = "com/fs/starfarer/combat/warroom/TaskIconManager";
    public static final String TASK_ICON_MANAGER_DOTTED            = "com.fs.starfarer.combat.warroom.TaskIconManager";
    public static final String PROFILER                            = "com/fs/profiler/Profiler";
    public static final String PROFILER_DOTTED                     = "com.fs.profiler.Profiler";
    public static final String AI_INTERFACE                        = "com/fs/starfarer/combat/ai/AI";
    public static final String AI_UTILS                            = "com/fs/starfarer/combat/ai/AIUtils";
    public static final String AI_UTILS_DOTTED                     = "com.fs.starfarer.combat.ai.AIUtils";
    public static final String BASIC_SHIP_AI                       = "com/fs/starfarer/combat/ai/BasicShipAI";
    public static final String FIGHTER_AI                          = "com/fs/starfarer/combat/ai/FighterAI";
    public static final String FIGHTER_AI_DOTTED                   = "com.fs.starfarer.combat.ai.FighterAI";
    public static final String FIGHTER_WING                        = "com/fs/starfarer/combat/ai/FighterWing";
    public static final String ATTACK_AI_MODULE                    = "com/fs/starfarer/combat/ai/attack/AttackAIModule";
    public static final String ATTACK_AI_MODULE_DOTTED             = "com.fs.starfarer.combat.ai.attack.AttackAIModule";
    public static final String SHIPWIDE_AI_FLAGS                   = "com/fs/starfarer/api/combat/ShipwideAIFlags";
    public static final String SHIPWIDE_AI_FLAGS_DOTTED            = "com.fs.starfarer.api.combat.ShipwideAIFlags";
    public static final String TIMEOUT_TRACKER_MAP                 = "com/fs/starfarer/api/util/TimeoutTrackerMap";
    public static final String TIMEOUT_TRACKER_MAP_DOTTED          = "com.fs.starfarer.api.util.TimeoutTrackerMap";
    public static final String COMBAT_FLEET_MANAGER                = "com/fs/starfarer/combat/CombatFleetManager";
    public static final String COMBAT_FLEET_MANAGER_DOTTED         = "com.fs.starfarer.combat.CombatFleetManager";
    public static final String WEAPON_GROUP                        = "com/fs/starfarer/combat/systems/WeaponGroup";
    public static final String WEAPON_GROUP_DOTTED                 = "com.fs.starfarer.combat.systems.WeaponGroup";
    public static final String SHIP_SYSTEM_SCRIPT_ADAPTER_DOTTED   = "com.fs.starfarer.loading.specs.ShipSystemSpec$SystemAIScriptAdapter";
    public static final String HULL_VARIANT_SPEC_DOTTED            = "com.fs.starfarer.loading.specs.HullVariantSpec";
    public static final String MISSILE_AI_DOTTED                   = "com.fs.starfarer.combat.ai.missile.MissileAI";

    private GameClassNames() {
    }
}