package github.kasuminova.ssoptimizer.asm.render;

import github.kasuminova.ssoptimizer.bootstrap.AsmClassProcessor;
import org.objectweb.asm.*;

/**
 * Replaces the method bodies of {@code Sprite.render(FF)V} and
 * {@code Sprite.renderNoBind(FF)V} with a single static call to
 * {@link SpriteRenderHelper#renderSprite}, which routes to a native
 * JNI implementation (1 JNI call) or a direct GL11 fallback.
 */
public final class EngineSpriteProcessor implements AsmClassProcessor {
    // Helper class that receives all sprite fields and does the rendering
    static final         String HELPER_OWNER    =
            "github/kasuminova/ssoptimizer/common/render/engine/SpriteRenderHelper";
    static final         String RENDER_DESC     = "(FFFFFFFIIIIIIFFFF)V";
    private static final String TARGET_CLASS    = "com/fs/graphics/Sprite";
    // Game class references
    private static final String SPRITE_CLASS    = "com/fs/graphics/Sprite";
    private static final String TEXTURE_CLASS   = "com/fs/graphics/Object";
    private static final String TEXTURE_DESC    = "L" + TEXTURE_CLASS + ";";
    private static final String COLOR_CLASS     = "java/awt/Color";
    private static final String COLOR_DESC      = "L" + COLOR_CLASS + ";";
    private static final String TEX_CLAMP_CLASS = "com/fs/graphics/util/B";

    // Obfuscated method names
    private static final String BIND_METHOD   = "\u00D800000";       // texture bind
    private static final String CLAMP_ENABLE  = "\u00D800000";      // B.Ø00000()
    private static final String CLAMP_RESTORE = "new";             // B.new()

    @Override
    public byte[] process(byte[] classfileBuffer) {
        ClassReader reader = new ClassReader(classfileBuffer);
        if (!TARGET_CLASS.equals(reader.getClassName())) {
            return null;
        }

        final boolean[] modified = {false};
        // COMPUTE_FRAMES is required: JDK 25 ignores -noverify, so the
        // bytecode verifier checks StackMapTable entries for every branch.
        ClassWriter writer = new ClassWriter(reader, ClassWriter.COMPUTE_FRAMES) {
            @Override
            protected String getCommonSuperClass(String type1, String type2) {
                // Safe fallback – avoids ClassNotFoundException for game classes
                return "java/lang/Object";
            }
        };

        reader.accept(new ClassVisitor(Opcodes.ASM9, writer) {
            @Override
            public MethodVisitor visitMethod(int access, String name, String desc,
                                             String sig, String[] ex) {
                MethodVisitor delegate = super.visitMethod(access, name, desc, sig, ex);
                if ("render".equals(name) && "(FF)V".equals(desc)) {
                    modified[0] = true;
                    return new SpriteMethodReplacer(delegate, true);
                }
                if ("renderNoBind".equals(name) && "(FF)V".equals(desc)) {
                    modified[0] = true;
                    return new SpriteMethodReplacer(delegate, false);
                }
                return delegate;
            }
        }, 0);

        return modified[0] ? writer.toByteArray() : null;
    }

    /**
     * Replaces a render / renderNoBind method body with a delegation to
     * {@link SpriteRenderHelper#renderSprite}.
     * <p>
     * The generated bytecode:
     * <ol>
     *   <li>Null-checks the texture field → early return</li>
     *   <li>(render only) Binds the texture</li>
     *   <li>Enables tex-clamp if needed</li>
     *   <li>Extracts all 17 sprite fields and pushes them onto the stack</li>
     *   <li>Calls {@code SpriteRenderHelper.renderSprite(...)}</li>
     *   <li>Restores tex-clamp if needed</li>
     * </ol>
     */
    static final class SpriteMethodReplacer extends MethodVisitor {
        private final MethodVisitor target;
        private final boolean       bindTexture;

        SpriteMethodReplacer(MethodVisitor target, boolean bindTexture) {
            super(Opcodes.ASM9); // no delegate → suppresses original bytecode
            this.target = target;
            this.bindTexture = bindTexture;
        }

        @Override
        public void visitCode() {
            target.visitCode();
            emitBody();
        }

        @Override
        public void visitMaxs(int maxStack, int maxLocals) {
            target.visitMaxs(0, 0); // COMPUTE_FRAMES handles this
        }

        @Override
        public void visitEnd() {
            target.visitEnd();
        }

        @Override
        public AnnotationVisitor visitAnnotation(String descriptor, boolean visible) {
            return target.visitAnnotation(descriptor, visible);
        }

        @Override
        public AnnotationVisitor visitParameterAnnotation(int parameter, String descriptor, boolean visible) {
            return target.visitParameterAnnotation(parameter, descriptor, visible);
        }

        private void emitBody() {
            Label returnLabel = new Label();
            Label skipClampEnable = new Label();

            // --- Texture null check: if (this.texture == null) return; ---
            target.visitVarInsn(Opcodes.ALOAD, 0);
            target.visitFieldInsn(Opcodes.GETFIELD, SPRITE_CLASS, "texture", TEXTURE_DESC);
            target.visitJumpInsn(Opcodes.IFNULL, returnLabel);

            if (bindTexture) {
                // --- Texture bind: this.texture.Ø00000(); ---
                target.visitVarInsn(Opcodes.ALOAD, 0);
                target.visitFieldInsn(Opcodes.GETFIELD, SPRITE_CLASS, "texture", TEXTURE_DESC);
                target.visitMethodInsn(Opcodes.INVOKEVIRTUAL, TEXTURE_CLASS, BIND_METHOD, "()V", false);
            }

            // --- TexClamp enable: if (this.texClamp) B.Ø00000(); ---
            target.visitVarInsn(Opcodes.ALOAD, 0);
            target.visitFieldInsn(Opcodes.GETFIELD, SPRITE_CLASS, "texClamp", "Z");
            target.visitJumpInsn(Opcodes.IFEQ, skipClampEnable);
            target.visitMethodInsn(Opcodes.INVOKESTATIC, TEX_CLAMP_CLASS, CLAMP_ENABLE, "()V", false);
            target.visitLabel(skipClampEnable);

            // --- Push 17 parameters for SpriteRenderHelper.renderSprite ---
            emitRenderSpriteParams();

            // --- Call SpriteRenderHelper.renderSprite(...) ---
            target.visitMethodInsn(Opcodes.INVOKESTATIC, HELPER_OWNER, "renderSprite", RENDER_DESC, false);

            // --- TexClamp restore: if (this.texClamp) B.new(); ---
            target.visitVarInsn(Opcodes.ALOAD, 0);
            target.visitFieldInsn(Opcodes.GETFIELD, SPRITE_CLASS, "texClamp", "Z");
            target.visitJumpInsn(Opcodes.IFEQ, returnLabel);
            target.visitMethodInsn(Opcodes.INVOKESTATIC, TEX_CLAMP_CLASS, CLAMP_RESTORE, "()V", false);

            // --- Return ---
            target.visitLabel(returnLabel);
            target.visitInsn(Opcodes.RETURN);
        }

        /**
         * Pushes 17 sprite parameters onto the operand stack in the order expected
         * by {@link SpriteRenderHelper#renderSprite}:
         * posX, posY, width, height, centerX, centerY, angle,
         * colorR, colorG, colorB, colorA, blendSrc, blendDest,
         * texX, texY, texWidth, texHeight.
         */
        private void emitRenderSpriteParams() {
            // posX = x + (float)this.offsetX
            target.visitVarInsn(Opcodes.FLOAD, 1);          // x (method param 1)
            target.visitVarInsn(Opcodes.ALOAD, 0);
            target.visitFieldInsn(Opcodes.GETFIELD, SPRITE_CLASS, "offsetX", "I");
            target.visitInsn(Opcodes.I2F);
            target.visitInsn(Opcodes.FADD);

            // posY = y + (float)this.offsetY
            target.visitVarInsn(Opcodes.FLOAD, 2);          // y (method param 2)
            target.visitVarInsn(Opcodes.ALOAD, 0);
            target.visitFieldInsn(Opcodes.GETFIELD, SPRITE_CLASS, "offsetY", "I");
            target.visitInsn(Opcodes.I2F);
            target.visitInsn(Opcodes.FADD);

            // width
            target.visitVarInsn(Opcodes.ALOAD, 0);
            target.visitFieldInsn(Opcodes.GETFIELD, SPRITE_CLASS, "width", "F");

            // height
            target.visitVarInsn(Opcodes.ALOAD, 0);
            target.visitFieldInsn(Opcodes.GETFIELD, SPRITE_CLASS, "height", "F");

            // centerX
            target.visitVarInsn(Opcodes.ALOAD, 0);
            target.visitFieldInsn(Opcodes.GETFIELD, SPRITE_CLASS, "centerX", "F");

            // centerY
            target.visitVarInsn(Opcodes.ALOAD, 0);
            target.visitFieldInsn(Opcodes.GETFIELD, SPRITE_CLASS, "centerY", "F");

            // angle
            target.visitVarInsn(Opcodes.ALOAD, 0);
            target.visitFieldInsn(Opcodes.GETFIELD, SPRITE_CLASS, "angle", "F");

            // colorR = this.color.getRed()
            target.visitVarInsn(Opcodes.ALOAD, 0);
            target.visitFieldInsn(Opcodes.GETFIELD, SPRITE_CLASS, "color", COLOR_DESC);
            target.visitMethodInsn(Opcodes.INVOKEVIRTUAL, COLOR_CLASS, "getRed", "()I", false);

            // colorG = this.color.getGreen()
            target.visitVarInsn(Opcodes.ALOAD, 0);
            target.visitFieldInsn(Opcodes.GETFIELD, SPRITE_CLASS, "color", COLOR_DESC);
            target.visitMethodInsn(Opcodes.INVOKEVIRTUAL, COLOR_CLASS, "getGreen", "()I", false);

            // colorB = this.color.getBlue()
            target.visitVarInsn(Opcodes.ALOAD, 0);
            target.visitFieldInsn(Opcodes.GETFIELD, SPRITE_CLASS, "color", COLOR_DESC);
            target.visitMethodInsn(Opcodes.INVOKEVIRTUAL, COLOR_CLASS, "getBlue", "()I", false);

            // colorA = (int)(this.color.getAlpha() * this.alphaMult)
            target.visitVarInsn(Opcodes.ALOAD, 0);
            target.visitFieldInsn(Opcodes.GETFIELD, SPRITE_CLASS, "color", COLOR_DESC);
            target.visitMethodInsn(Opcodes.INVOKEVIRTUAL, COLOR_CLASS, "getAlpha", "()I", false);
            target.visitInsn(Opcodes.I2F);
            target.visitVarInsn(Opcodes.ALOAD, 0);
            target.visitFieldInsn(Opcodes.GETFIELD, SPRITE_CLASS, "alphaMult", "F");
            target.visitInsn(Opcodes.FMUL);
            target.visitInsn(Opcodes.F2I);

            // blendSrc
            target.visitVarInsn(Opcodes.ALOAD, 0);
            target.visitFieldInsn(Opcodes.GETFIELD, SPRITE_CLASS, "blendSrc", "I");

            // blendDest
            target.visitVarInsn(Opcodes.ALOAD, 0);
            target.visitFieldInsn(Opcodes.GETFIELD, SPRITE_CLASS, "blendDest", "I");

            // texX
            target.visitVarInsn(Opcodes.ALOAD, 0);
            target.visitFieldInsn(Opcodes.GETFIELD, SPRITE_CLASS, "texX", "F");

            // texY
            target.visitVarInsn(Opcodes.ALOAD, 0);
            target.visitFieldInsn(Opcodes.GETFIELD, SPRITE_CLASS, "texY", "F");

            // texWidth
            target.visitVarInsn(Opcodes.ALOAD, 0);
            target.visitFieldInsn(Opcodes.GETFIELD, SPRITE_CLASS, "texWidth", "F");

            // texHeight
            target.visitVarInsn(Opcodes.ALOAD, 0);
            target.visitFieldInsn(Opcodes.GETFIELD, SPRITE_CLASS, "texHeight", "F");
        }
    }
}