// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.AMDDebugOutput 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class AMDDebugOutput {
    private AMDDebugOutput() {
    }

    // 命令型（回调引用捕获，回调随后在渲染线程触发）
    public static void glDebugMessageCallbackAMD(org.lwjgl.opengl.AMDDebugOutputCallback p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.AMDDebugOutput.glDebugMessageCallbackAMD(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDebugMessageEnableAMD(int p0, int p1, java.nio.IntBuffer p2, boolean p3) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.AMDDebugOutput.glDebugMessageEnableAMD(p0, p1, snapshot.asIntBuffer(), p3));
    }

    // 命令型（字符串捕获，不可变）
    public static void glDebugMessageInsertAMD(int p0, int p1, int p2, java.lang.CharSequence p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.AMDDebugOutput.glDebugMessageInsertAMD(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDebugMessageInsertAMD(int p0, int p1, int p2, java.nio.ByteBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.AMDDebugOutput.glDebugMessageInsertAMD(p0, p1, p2, snapshot));
    }

    // 阻塞取值型
    public static int glGetDebugMessageLogAMD(int p0, java.nio.IntBuffer p1, java.nio.IntBuffer p2, java.nio.IntBuffer p3, java.nio.IntBuffer p4, java.nio.ByteBuffer p5) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.AMDDebugOutput.glGetDebugMessageLogAMD(p0, p1, p2, p3, p4, p5));
    }
}
