// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.AMDPerformanceMonitor 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class AMDPerformanceMonitor {
    private AMDPerformanceMonitor() {
    }

    // 命令型
    public static void glBeginPerfMonitorAMD(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.AMDPerformanceMonitor.glBeginPerfMonitorAMD(p0));
    }

    // 命令型
    public static void glDeletePerfMonitorsAMD(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.AMDPerformanceMonitor.glDeletePerfMonitorsAMD(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDeletePerfMonitorsAMD(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.AMDPerformanceMonitor.glDeletePerfMonitorsAMD(snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glEndPerfMonitorAMD(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.AMDPerformanceMonitor.glEndPerfMonitorAMD(p0));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glGenPerfMonitorsAMD() {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.AMDPerformanceMonitor.glGenPerfMonitorsAMD());
    }

    // 阻塞资源型（glGen 族，不计 StallDetector）
    public static void glGenPerfMonitorsAMD(java.nio.IntBuffer p0) {
        BridgeSupport.blockingWaitResource(() -> org.lwjgl.opengl.AMDPerformanceMonitor.glGenPerfMonitorsAMD(p0));
    }

    // 阻塞取值型
    public static int glGetPerfMonitorCounterDataAMD(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.AMDPerformanceMonitor.glGetPerfMonitorCounterDataAMD(p0, p1));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetPerfMonitorCounterDataAMD(int p0, int p1, java.nio.IntBuffer p2, java.nio.IntBuffer p3) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.AMDPerformanceMonitor.glGetPerfMonitorCounterDataAMD(p0, p1, p2, p3));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetPerfMonitorCounterInfoAMD(int p0, int p1, int p2, java.nio.ByteBuffer p3) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillBooleans(p3, 16, buf -> org.lwjgl.opengl.AMDPerformanceMonitor.glGetPerfMonitorCounterInfoAMD(p0, p1, p2, buf)));
    }

    // 阻塞取值型
    public static java.lang.String glGetPerfMonitorCounterStringAMD(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.AMDPerformanceMonitor.glGetPerfMonitorCounterStringAMD(p0, p1, p2));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetPerfMonitorCounterStringAMD(int p0, int p1, java.nio.IntBuffer p2, java.nio.ByteBuffer p3) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.AMDPerformanceMonitor.glGetPerfMonitorCounterStringAMD(p0, p1, p2, p3));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetPerfMonitorCountersAMD(int p0, java.nio.IntBuffer p1, java.nio.IntBuffer p2, java.nio.IntBuffer p3) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.AMDPerformanceMonitor.glGetPerfMonitorCountersAMD(p0, p1, p2, p3));
    }

    // 阻塞取值型
    public static java.lang.String glGetPerfMonitorGroupStringAMD(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.AMDPerformanceMonitor.glGetPerfMonitorGroupStringAMD(p0, p1));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetPerfMonitorGroupStringAMD(int p0, java.nio.IntBuffer p1, java.nio.ByteBuffer p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.AMDPerformanceMonitor.glGetPerfMonitorGroupStringAMD(p0, p1, p2));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetPerfMonitorGroupsAMD(java.nio.IntBuffer p0, java.nio.IntBuffer p1) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.AMDPerformanceMonitor.glGetPerfMonitorGroupsAMD(p0, p1));
    }

    // 命令型
    public static void glSelectPerfMonitorCountersAMD(int p0, boolean p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.AMDPerformanceMonitor.glSelectPerfMonitorCountersAMD(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glSelectPerfMonitorCountersAMD(int p0, boolean p1, int p2, java.nio.IntBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.AMDPerformanceMonitor.glSelectPerfMonitorCountersAMD(p0, p1, p2, snapshot.asIntBuffer()));
    }
}
