// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.APPLEFence 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class APPLEFence {
    private APPLEFence() {
    }

    // 命令型
    public static void glDeleteFencesAPPLE(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.APPLEFence.glDeleteFencesAPPLE(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDeleteFencesAPPLE(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.APPLEFence.glDeleteFencesAPPLE(snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glFinishFenceAPPLE(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.APPLEFence.glFinishFenceAPPLE(p0));
    }

    // 命令型
    public static void glFinishObjectAPPLE(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.APPLEFence.glFinishObjectAPPLE(p0, p1));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glGenFencesAPPLE() {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.APPLEFence.glGenFencesAPPLE());
    }

    // 阻塞资源型（glGen 族，不计 StallDetector）
    public static void glGenFencesAPPLE(java.nio.IntBuffer p0) {
        BridgeSupport.blockingWaitResource(() -> org.lwjgl.opengl.APPLEFence.glGenFencesAPPLE(p0));
    }

    // 阻塞取值型
    public static boolean glIsFenceAPPLE(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.APPLEFence.glIsFenceAPPLE(p0));
    }

    // 命令型
    public static void glSetFenceAPPLE(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.APPLEFence.glSetFenceAPPLE(p0));
    }

    // 阻塞取值型
    public static boolean glTestFenceAPPLE(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.APPLEFence.glTestFenceAPPLE(p0));
    }

    // 阻塞取值型
    public static boolean glTestObjectAPPLE(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.APPLEFence.glTestObjectAPPLE(p0, p1));
    }
}
