// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.APPLEVertexProgramEvaluators 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class APPLEVertexProgramEvaluators {
    private APPLEVertexProgramEvaluators() {
    }

    // 命令型
    public static void glDisableVertexAttribAPPLE(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.APPLEVertexProgramEvaluators.glDisableVertexAttribAPPLE(p0, p1));
    }

    // 命令型
    public static void glEnableVertexAttribAPPLE(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.APPLEVertexProgramEvaluators.glEnableVertexAttribAPPLE(p0, p1));
    }

    // 阻塞取值型
    public static boolean glIsVertexAttribEnabledAPPLE(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.APPLEVertexProgramEvaluators.glIsVertexAttribEnabledAPPLE(p0, p1));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glMapVertexAttrib1dAPPLE(int p0, int p1, double p2, double p3, int p4, int p5, java.nio.DoubleBuffer p6) {
        BridgeSupport.enqueueSnapshot(p6, snapshot -> org.lwjgl.opengl.APPLEVertexProgramEvaluators.glMapVertexAttrib1dAPPLE(p0, p1, p2, p3, p4, p5, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glMapVertexAttrib1fAPPLE(int p0, int p1, float p2, float p3, int p4, int p5, java.nio.FloatBuffer p6) {
        BridgeSupport.enqueueSnapshot(p6, snapshot -> org.lwjgl.opengl.APPLEVertexProgramEvaluators.glMapVertexAttrib1fAPPLE(p0, p1, p2, p3, p4, p5, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glMapVertexAttrib2dAPPLE(int p0, int p1, double p2, double p3, int p4, int p5, double p6, double p7, int p8, int p9, java.nio.DoubleBuffer p10) {
        BridgeSupport.enqueueSnapshot(p10, snapshot -> org.lwjgl.opengl.APPLEVertexProgramEvaluators.glMapVertexAttrib2dAPPLE(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glMapVertexAttrib2fAPPLE(int p0, int p1, float p2, float p3, int p4, int p5, float p6, float p7, int p8, int p9, java.nio.FloatBuffer p10) {
        BridgeSupport.enqueueSnapshot(p10, snapshot -> org.lwjgl.opengl.APPLEVertexProgramEvaluators.glMapVertexAttrib2fAPPLE(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, snapshot.asFloatBuffer()));
    }
}
