// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.APPLETextureRange 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class APPLETextureRange {
    private APPLETextureRange() {
    }

    // 阻塞取值型
    public static java.nio.Buffer glGetTexParameterPointervAPPLE(int p0, int p1, long p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.APPLETextureRange.glGetTexParameterPointervAPPLE(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTextureRangeAPPLE(int p0, java.nio.ByteBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.APPLETextureRange.glTextureRangeAPPLE(p0, snapshot));
    }
}
