// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ARBBufferStorage 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class ARBBufferStorage {
    private ARBBufferStorage() {
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferStorage(int p0, java.nio.ByteBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBBufferStorage.glBufferStorage(p0, snapshot, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferStorage(int p0, java.nio.DoubleBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBBufferStorage.glBufferStorage(p0, snapshot.asDoubleBuffer(), p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferStorage(int p0, java.nio.FloatBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBBufferStorage.glBufferStorage(p0, snapshot.asFloatBuffer(), p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferStorage(int p0, java.nio.IntBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBBufferStorage.glBufferStorage(p0, snapshot.asIntBuffer(), p2));
    }

    // 阻塞直通型（降级：enqueueSnapshot 无 LongBuffer 重载）
    public static void glBufferStorage(int p0, java.nio.LongBuffer p1, int p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.ARBBufferStorage.glBufferStorage(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferStorage(int p0, java.nio.ShortBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBBufferStorage.glBufferStorage(p0, snapshot.asShortBuffer(), p2));
    }

    // 命令型
    public static void glBufferStorage(int p0, long p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBBufferStorage.glBufferStorage(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNamedBufferStorageEXT(int p0, java.nio.ByteBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBBufferStorage.glNamedBufferStorageEXT(p0, snapshot, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNamedBufferStorageEXT(int p0, java.nio.DoubleBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBBufferStorage.glNamedBufferStorageEXT(p0, snapshot.asDoubleBuffer(), p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNamedBufferStorageEXT(int p0, java.nio.FloatBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBBufferStorage.glNamedBufferStorageEXT(p0, snapshot.asFloatBuffer(), p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNamedBufferStorageEXT(int p0, java.nio.IntBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBBufferStorage.glNamedBufferStorageEXT(p0, snapshot.asIntBuffer(), p2));
    }

    // 阻塞直通型（降级：enqueueSnapshot 无 LongBuffer 重载）
    public static void glNamedBufferStorageEXT(int p0, java.nio.LongBuffer p1, int p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.ARBBufferStorage.glNamedBufferStorageEXT(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNamedBufferStorageEXT(int p0, java.nio.ShortBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBBufferStorage.glNamedBufferStorageEXT(p0, snapshot.asShortBuffer(), p2));
    }

    // 命令型
    public static void glNamedBufferStorageEXT(int p0, long p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBBufferStorage.glNamedBufferStorageEXT(p0, p1, p2));
    }
}
