// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ARBCopyBuffer 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class ARBCopyBuffer {
    private ARBCopyBuffer() {
    }

    // 命令型
    public static void glCopyBufferSubData(int p0, int p1, long p2, long p3, long p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBCopyBuffer.glCopyBufferSubData(p0, p1, p2, p3, p4));
    }
}
