// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ARBDrawInstanced 的 bridge 镜像生成基类（全量镜像兜底面）。
 * <p>
 * 手写类 {@link ARBDrawInstanced} extends 本类：invokestatic 的方法解析先命中手写类
 * 自身声明（顶点流/状态仿真/id stash/map 仿真等精心语义），未覆盖的
 * 落到本基类的通用录制/阻塞语义——手写永远优先，生成物只兜底。
 */
public class ARBDrawInstancedGen {
    protected ARBDrawInstancedGen() {
    }

    // 命令型
    public static void glDrawArraysInstancedARB(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDrawInstanced.glDrawArraysInstancedARB(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElementsInstancedARB(int p0, java.nio.ByteBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBDrawInstanced.glDrawElementsInstancedARB(p0, snapshot, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElementsInstancedARB(int p0, java.nio.IntBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBDrawInstanced.glDrawElementsInstancedARB(p0, snapshot.asIntBuffer(), p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElementsInstancedARB(int p0, java.nio.ShortBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBDrawInstanced.glDrawElementsInstancedARB(p0, snapshot.asShortBuffer(), p2));
    }

    // 命令型
    public static void glDrawElementsInstancedARB(int p0, int p1, int p2, long p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDrawInstanced.glDrawElementsInstancedARB(p0, p1, p2, p3, p4));
    }
}
