// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ARBDrawElementsBaseVertex 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class ARBDrawElementsBaseVertex {
    private ARBDrawElementsBaseVertex() {
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElementsBaseVertex(int p0, java.nio.ByteBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBDrawElementsBaseVertex.glDrawElementsBaseVertex(p0, snapshot, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElementsBaseVertex(int p0, java.nio.IntBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBDrawElementsBaseVertex.glDrawElementsBaseVertex(p0, snapshot.asIntBuffer(), p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElementsBaseVertex(int p0, java.nio.ShortBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBDrawElementsBaseVertex.glDrawElementsBaseVertex(p0, snapshot.asShortBuffer(), p2));
    }

    // 命令型
    public static void glDrawElementsBaseVertex(int p0, int p1, int p2, long p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDrawElementsBaseVertex.glDrawElementsBaseVertex(p0, p1, p2, p3, p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElementsInstancedBaseVertex(int p0, java.nio.ByteBuffer p1, int p2, int p3) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBDrawElementsBaseVertex.glDrawElementsInstancedBaseVertex(p0, snapshot, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElementsInstancedBaseVertex(int p0, java.nio.IntBuffer p1, int p2, int p3) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBDrawElementsBaseVertex.glDrawElementsInstancedBaseVertex(p0, snapshot.asIntBuffer(), p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElementsInstancedBaseVertex(int p0, java.nio.ShortBuffer p1, int p2, int p3) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBDrawElementsBaseVertex.glDrawElementsInstancedBaseVertex(p0, snapshot.asShortBuffer(), p2, p3));
    }

    // 命令型
    public static void glDrawElementsInstancedBaseVertex(int p0, int p1, int p2, long p3, int p4, int p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDrawElementsBaseVertex.glDrawElementsInstancedBaseVertex(p0, p1, p2, p3, p4, p5));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawRangeElementsBaseVertex(int p0, int p1, int p2, java.nio.ByteBuffer p3, int p4) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBDrawElementsBaseVertex.glDrawRangeElementsBaseVertex(p0, p1, p2, snapshot, p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawRangeElementsBaseVertex(int p0, int p1, int p2, java.nio.IntBuffer p3, int p4) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBDrawElementsBaseVertex.glDrawRangeElementsBaseVertex(p0, p1, p2, snapshot.asIntBuffer(), p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawRangeElementsBaseVertex(int p0, int p1, int p2, java.nio.ShortBuffer p3, int p4) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBDrawElementsBaseVertex.glDrawRangeElementsBaseVertex(p0, p1, p2, snapshot.asShortBuffer(), p4));
    }

    // 命令型
    public static void glDrawRangeElementsBaseVertex(int p0, int p1, int p2, int p3, int p4, long p5, int p6) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDrawElementsBaseVertex.glDrawRangeElementsBaseVertex(p0, p1, p2, p3, p4, p5, p6));
    }
}
