// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ARBDrawBuffers 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class ARBDrawBuffers {
    private ARBDrawBuffers() {
    }

    // 命令型
    public static void glDrawBuffersARB(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDrawBuffers.glDrawBuffersARB(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawBuffersARB(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.ARBDrawBuffers.glDrawBuffersARB(snapshot.asIntBuffer()));
    }
}
