// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ARBDirectStateAccess 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class ARBDirectStateAccess {
    private ARBDirectStateAccess() {
    }

    // 命令型
    public static void glBindTextureUnit(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glBindTextureUnit(p0, p1));
    }

    // 命令型
    public static void glBlitNamedFramebuffer(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, int p10, int p11) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glBlitNamedFramebuffer(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11));
    }

    // 阻塞取值型
    public static int glCheckNamedFramebufferStatus(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBDirectStateAccess.glCheckNamedFramebufferStatus(p0, p1));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glClearNamedBufferData(int p0, int p1, int p2, int p3, java.nio.ByteBuffer p4) {
        BridgeSupport.enqueueSnapshot(p4, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glClearNamedBufferData(p0, p1, p2, p3, snapshot));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glClearNamedBufferSubData(int p0, int p1, long p2, long p3, int p4, int p5, java.nio.ByteBuffer p6) {
        BridgeSupport.enqueueSnapshot(p6, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glClearNamedBufferSubData(p0, p1, p2, p3, p4, p5, snapshot));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glClearNamedFramebuffer(int p0, int p1, int p2, java.nio.FloatBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glClearNamedFramebuffer(p0, p1, p2, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glClearNamedFramebuffer(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glClearNamedFramebuffer(p0, p1, p2, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glClearNamedFramebufferfi(int p0, int p1, float p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glClearNamedFramebufferfi(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glClearNamedFramebufferu(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glClearNamedFramebufferu(p0, p1, p2, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCompressedTextureSubImage1D(int p0, int p1, int p2, int p3, int p4, java.nio.ByteBuffer p5) {
        BridgeSupport.enqueueSnapshot(p5, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glCompressedTextureSubImage1D(p0, p1, p2, p3, p4, snapshot));
    }

    // 命令型
    public static void glCompressedTextureSubImage1D(int p0, int p1, int p2, int p3, int p4, int p5, long p6) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glCompressedTextureSubImage1D(p0, p1, p2, p3, p4, p5, p6));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCompressedTextureSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, java.nio.ByteBuffer p7) {
        BridgeSupport.enqueueSnapshot(p7, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glCompressedTextureSubImage2D(p0, p1, p2, p3, p4, p5, p6, snapshot));
    }

    // 命令型
    public static void glCompressedTextureSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, long p8) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glCompressedTextureSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7, p8));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCompressedTextureSubImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, java.nio.ByteBuffer p10) {
        BridgeSupport.enqueueSnapshot(p10, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glCompressedTextureSubImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, snapshot));
    }

    // 命令型
    public static void glCompressedTextureSubImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, long p10) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glCompressedTextureSubImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    }

    // 命令型
    public static void glCopyNamedBufferSubData(int p0, int p1, long p2, long p3, long p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glCopyNamedBufferSubData(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glCopyTextureSubImage1D(int p0, int p1, int p2, int p3, int p4, int p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glCopyTextureSubImage1D(p0, p1, p2, p3, p4, p5));
    }

    // 命令型
    public static void glCopyTextureSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glCopyTextureSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7));
    }

    // 命令型
    public static void glCopyTextureSubImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glCopyTextureSubImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glCreateBuffers() {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.ARBDirectStateAccess.glCreateBuffers());
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCreateBuffers(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glCreateBuffers(snapshot.asIntBuffer()));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glCreateFramebuffers() {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.ARBDirectStateAccess.glCreateFramebuffers());
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCreateFramebuffers(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glCreateFramebuffers(snapshot.asIntBuffer()));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glCreateProgramPipelines() {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.ARBDirectStateAccess.glCreateProgramPipelines());
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCreateProgramPipelines(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glCreateProgramPipelines(snapshot.asIntBuffer()));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glCreateQueries(int p0) {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.ARBDirectStateAccess.glCreateQueries(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCreateQueries(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glCreateQueries(p0, snapshot.asIntBuffer()));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glCreateRenderbuffers() {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.ARBDirectStateAccess.glCreateRenderbuffers());
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCreateRenderbuffers(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glCreateRenderbuffers(snapshot.asIntBuffer()));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glCreateSamplers() {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.ARBDirectStateAccess.glCreateSamplers());
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCreateSamplers(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glCreateSamplers(snapshot.asIntBuffer()));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glCreateTextures(int p0) {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.ARBDirectStateAccess.glCreateTextures(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCreateTextures(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glCreateTextures(p0, snapshot.asIntBuffer()));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glCreateTransformFeedbacks() {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.ARBDirectStateAccess.glCreateTransformFeedbacks());
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCreateTransformFeedbacks(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glCreateTransformFeedbacks(snapshot.asIntBuffer()));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glCreateVertexArrays() {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.ARBDirectStateAccess.glCreateVertexArrays());
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCreateVertexArrays(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glCreateVertexArrays(snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glDisableVertexArrayAttrib(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glDisableVertexArrayAttrib(p0, p1));
    }

    // 命令型
    public static void glEnableVertexArrayAttrib(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glEnableVertexArrayAttrib(p0, p1));
    }

    // 命令型
    public static void glFlushMappedNamedBufferRange(int p0, long p1, long p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glFlushMappedNamedBufferRange(p0, p1, p2));
    }

    // 命令型
    public static void glGenerateTextureMipmap(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glGenerateTextureMipmap(p0));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetCompressedTextureImage(int p0, int p1, java.nio.ByteBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillBooleans(p2, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetCompressedTextureImage(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetCompressedTextureImage(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetCompressedTextureImage(p0, p1, buf)));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetCompressedTextureImage(int p0, int p1, java.nio.ShortBuffer p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.ARBDirectStateAccess.glGetCompressedTextureImage(p0, p1, p2));
    }

    // 命令型
    public static void glGetCompressedTextureImage(int p0, int p1, int p2, long p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glGetCompressedTextureImage(p0, p1, p2, p3));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetNamedBufferParameter(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetNamedBufferParameter(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetNamedBufferParameter(int p0, int p1, java.nio.LongBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillLongs(p2, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetNamedBufferParameter(p0, p1, buf)));
    }

    // 阻塞取值型
    public static int glGetNamedBufferParameteri(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBDirectStateAccess.glGetNamedBufferParameteri(p0, p1));
    }

    // 阻塞取值型
    public static long glGetNamedBufferParameteri64(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBDirectStateAccess.glGetNamedBufferParameteri64(p0, p1));
    }

    // 阻塞取值型
    public static java.nio.ByteBuffer glGetNamedBufferPointer(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBDirectStateAccess.glGetNamedBufferPointer(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetNamedBufferSubData(int p0, long p1, java.nio.ByteBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillBooleans(p2, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetNamedBufferSubData(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetNamedBufferSubData(int p0, long p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillDoubles(p2, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetNamedBufferSubData(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetNamedBufferSubData(int p0, long p1, java.nio.FloatBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p2, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetNamedBufferSubData(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetNamedBufferSubData(int p0, long p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetNamedBufferSubData(p0, p1, buf)));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetNamedBufferSubData(int p0, long p1, java.nio.ShortBuffer p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.ARBDirectStateAccess.glGetNamedBufferSubData(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetNamedFramebufferAttachmentParameter(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBDirectStateAccess.glGetNamedFramebufferAttachmentParameter(p0, p1, p2));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetNamedFramebufferAttachmentParameter(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p3, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetNamedFramebufferAttachmentParameter(p0, p1, p2, buf)));
    }

    // 阻塞取值型
    public static int glGetNamedFramebufferParameter(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBDirectStateAccess.glGetNamedFramebufferParameter(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetNamedFramebufferParameter(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetNamedFramebufferParameter(p0, p1, buf)));
    }

    // 阻塞取值型
    public static int glGetNamedRenderbufferParameter(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBDirectStateAccess.glGetNamedRenderbufferParameter(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetNamedRenderbufferParameter(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetNamedRenderbufferParameter(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTextureImage(int p0, int p1, int p2, int p3, java.nio.ByteBuffer p4) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillBooleans(p4, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetTextureImage(p0, p1, p2, p3, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTextureImage(int p0, int p1, int p2, int p3, java.nio.DoubleBuffer p4) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillDoubles(p4, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetTextureImage(p0, p1, p2, p3, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTextureImage(int p0, int p1, int p2, int p3, java.nio.FloatBuffer p4) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p4, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetTextureImage(p0, p1, p2, p3, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTextureImage(int p0, int p1, int p2, int p3, java.nio.IntBuffer p4) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p4, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetTextureImage(p0, p1, p2, p3, buf)));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetTextureImage(int p0, int p1, int p2, int p3, java.nio.ShortBuffer p4) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.ARBDirectStateAccess.glGetTextureImage(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glGetTextureImage(int p0, int p1, int p2, int p3, int p4, long p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glGetTextureImage(p0, p1, p2, p3, p4, p5));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTextureLevelParameter(int p0, int p1, int p2, java.nio.FloatBuffer p3) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p3, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetTextureLevelParameter(p0, p1, p2, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTextureLevelParameter(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p3, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetTextureLevelParameter(p0, p1, p2, buf)));
    }

    // 阻塞取值型
    public static float glGetTextureLevelParameterf(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBDirectStateAccess.glGetTextureLevelParameterf(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetTextureLevelParameteri(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBDirectStateAccess.glGetTextureLevelParameteri(p0, p1, p2));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTextureParameter(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p2, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetTextureParameter(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTextureParameter(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetTextureParameter(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTextureParameterI(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetTextureParameterI(p0, p1, buf)));
    }

    // 阻塞取值型
    public static int glGetTextureParameterIi(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBDirectStateAccess.glGetTextureParameterIi(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTextureParameterIu(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetTextureParameterIu(p0, p1, buf)));
    }

    // 阻塞取值型
    public static int glGetTextureParameterIui(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBDirectStateAccess.glGetTextureParameterIui(p0, p1));
    }

    // 阻塞取值型
    public static float glGetTextureParameterf(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBDirectStateAccess.glGetTextureParameterf(p0, p1));
    }

    // 阻塞取值型
    public static int glGetTextureParameteri(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBDirectStateAccess.glGetTextureParameteri(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTransformFeedback(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetTransformFeedback(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTransformFeedback(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p3, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetTransformFeedback(p0, p1, p2, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTransformFeedback(int p0, int p1, int p2, java.nio.LongBuffer p3) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillLongs(p3, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetTransformFeedback(p0, p1, p2, buf)));
    }

    // 阻塞取值型
    public static int glGetTransformFeedbacki(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBDirectStateAccess.glGetTransformFeedbacki(p0, p1));
    }

    // 阻塞取值型
    public static int glGetTransformFeedbacki(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBDirectStateAccess.glGetTransformFeedbacki(p0, p1, p2));
    }

    // 阻塞取值型
    public static long glGetTransformFeedbacki64(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBDirectStateAccess.glGetTransformFeedbacki64(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetVertexArray(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBDirectStateAccess.glGetVertexArray(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetVertexArray(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetVertexArray(p0, p1, buf)));
    }

    // 阻塞取值型
    public static int glGetVertexArrayIndexed(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBDirectStateAccess.glGetVertexArrayIndexed(p0, p1, p2));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetVertexArrayIndexed(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p3, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetVertexArrayIndexed(p0, p1, p2, buf)));
    }

    // 阻塞取值型
    public static long glGetVertexArrayIndexed64i(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBDirectStateAccess.glGetVertexArrayIndexed64i(p0, p1, p2));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetVertexArrayIndexed64i(int p0, int p1, int p2, java.nio.LongBuffer p3) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillLongs(p3, 16, buf -> org.lwjgl.opengl.ARBDirectStateAccess.glGetVertexArrayIndexed64i(p0, p1, p2, buf)));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glInvalidateNamedFramebufferData(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glInvalidateNamedFramebufferData(p0, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glInvalidateNamedFramebufferSubData(int p0, java.nio.IntBuffer p1, int p2, int p3, int p4, int p5) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glInvalidateNamedFramebufferSubData(p0, snapshot.asIntBuffer(), p2, p3, p4, p5));
    }

    // 阻塞取值型
    public static java.nio.ByteBuffer glMapNamedBuffer(int p0, int p1, java.nio.ByteBuffer p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBDirectStateAccess.glMapNamedBuffer(p0, p1, p2));
    }

    // 阻塞取值型
    public static java.nio.ByteBuffer glMapNamedBuffer(int p0, int p1, long p2, java.nio.ByteBuffer p3) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBDirectStateAccess.glMapNamedBuffer(p0, p1, p2, p3));
    }

    // 阻塞取值型
    public static java.nio.ByteBuffer glMapNamedBufferRange(int p0, long p1, long p2, int p3, java.nio.ByteBuffer p4) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBDirectStateAccess.glMapNamedBufferRange(p0, p1, p2, p3, p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNamedBufferData(int p0, java.nio.ByteBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedBufferData(p0, snapshot, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNamedBufferData(int p0, java.nio.DoubleBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedBufferData(p0, snapshot.asDoubleBuffer(), p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNamedBufferData(int p0, java.nio.FloatBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedBufferData(p0, snapshot.asFloatBuffer(), p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNamedBufferData(int p0, java.nio.IntBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedBufferData(p0, snapshot.asIntBuffer(), p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNamedBufferData(int p0, java.nio.ShortBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedBufferData(p0, snapshot.asShortBuffer(), p2));
    }

    // 命令型
    public static void glNamedBufferData(int p0, long p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedBufferData(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNamedBufferStorage(int p0, java.nio.ByteBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedBufferStorage(p0, snapshot, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNamedBufferStorage(int p0, java.nio.DoubleBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedBufferStorage(p0, snapshot.asDoubleBuffer(), p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNamedBufferStorage(int p0, java.nio.FloatBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedBufferStorage(p0, snapshot.asFloatBuffer(), p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNamedBufferStorage(int p0, java.nio.IntBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedBufferStorage(p0, snapshot.asIntBuffer(), p2));
    }

    // 阻塞直通型（降级：enqueueSnapshot 无 LongBuffer 重载）
    public static void glNamedBufferStorage(int p0, java.nio.LongBuffer p1, int p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedBufferStorage(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNamedBufferStorage(int p0, java.nio.ShortBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedBufferStorage(p0, snapshot.asShortBuffer(), p2));
    }

    // 命令型
    public static void glNamedBufferStorage(int p0, long p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedBufferStorage(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNamedBufferSubData(int p0, long p1, java.nio.ByteBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedBufferSubData(p0, p1, snapshot));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNamedBufferSubData(int p0, long p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedBufferSubData(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNamedBufferSubData(int p0, long p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedBufferSubData(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNamedBufferSubData(int p0, long p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedBufferSubData(p0, p1, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNamedBufferSubData(int p0, long p1, java.nio.ShortBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedBufferSubData(p0, p1, snapshot.asShortBuffer()));
    }

    // 命令型
    public static void glNamedFramebufferDrawBuffer(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedFramebufferDrawBuffer(p0, p1));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNamedFramebufferDrawBuffers(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedFramebufferDrawBuffers(p0, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glNamedFramebufferParameteri(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedFramebufferParameteri(p0, p1, p2));
    }

    // 命令型
    public static void glNamedFramebufferReadBuffer(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedFramebufferReadBuffer(p0, p1));
    }

    // 命令型
    public static void glNamedFramebufferRenderbuffer(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedFramebufferRenderbuffer(p0, p1, p2, p3));
    }

    // 命令型
    public static void glNamedFramebufferTexture(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedFramebufferTexture(p0, p1, p2, p3));
    }

    // 命令型
    public static void glNamedFramebufferTextureLayer(int p0, int p1, int p2, int p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedFramebufferTextureLayer(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glNamedRenderbufferStorage(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedRenderbufferStorage(p0, p1, p2, p3));
    }

    // 命令型
    public static void glNamedRenderbufferStorageMultisample(int p0, int p1, int p2, int p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glNamedRenderbufferStorageMultisample(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glTextureBuffer(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureBuffer(p0, p1, p2));
    }

    // 命令型
    public static void glTextureBufferRange(int p0, int p1, int p2, long p3, long p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureBufferRange(p0, p1, p2, p3, p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTextureParameter(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureParameter(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTextureParameter(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureParameter(p0, p1, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTextureParameterI(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureParameterI(p0, p1, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTextureParameterIu(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureParameterIu(p0, p1, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glTextureParameterf(int p0, int p1, float p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureParameterf(p0, p1, p2));
    }

    // 命令型
    public static void glTextureParameteri(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureParameteri(p0, p1, p2));
    }

    // 命令型
    public static void glTextureStorage1D(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureStorage1D(p0, p1, p2, p3));
    }

    // 命令型
    public static void glTextureStorage2D(int p0, int p1, int p2, int p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureStorage2D(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glTextureStorage2DMultisample(int p0, int p1, int p2, int p3, int p4, boolean p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureStorage2DMultisample(p0, p1, p2, p3, p4, p5));
    }

    // 命令型
    public static void glTextureStorage3D(int p0, int p1, int p2, int p3, int p4, int p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureStorage3D(p0, p1, p2, p3, p4, p5));
    }

    // 命令型
    public static void glTextureStorage3DMultisample(int p0, int p1, int p2, int p3, int p4, int p5, boolean p6) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureStorage3DMultisample(p0, p1, p2, p3, p4, p5, p6));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTextureSubImage1D(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.ByteBuffer p6) {
        BridgeSupport.enqueueSnapshot(p6, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureSubImage1D(p0, p1, p2, p3, p4, p5, snapshot));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTextureSubImage1D(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.DoubleBuffer p6) {
        BridgeSupport.enqueueSnapshot(p6, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureSubImage1D(p0, p1, p2, p3, p4, p5, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTextureSubImage1D(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.FloatBuffer p6) {
        BridgeSupport.enqueueSnapshot(p6, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureSubImage1D(p0, p1, p2, p3, p4, p5, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTextureSubImage1D(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.IntBuffer p6) {
        BridgeSupport.enqueueSnapshot(p6, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureSubImage1D(p0, p1, p2, p3, p4, p5, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTextureSubImage1D(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.ShortBuffer p6) {
        BridgeSupport.enqueueSnapshot(p6, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureSubImage1D(p0, p1, p2, p3, p4, p5, snapshot.asShortBuffer()));
    }

    // 命令型
    public static void glTextureSubImage1D(int p0, int p1, int p2, int p3, int p4, int p5, long p6) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureSubImage1D(p0, p1, p2, p3, p4, p5, p6));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTextureSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.ByteBuffer p8) {
        BridgeSupport.enqueueSnapshot(p8, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7, snapshot));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTextureSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.DoubleBuffer p8) {
        BridgeSupport.enqueueSnapshot(p8, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTextureSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.FloatBuffer p8) {
        BridgeSupport.enqueueSnapshot(p8, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTextureSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.IntBuffer p8) {
        BridgeSupport.enqueueSnapshot(p8, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTextureSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.ShortBuffer p8) {
        BridgeSupport.enqueueSnapshot(p8, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7, snapshot.asShortBuffer()));
    }

    // 命令型
    public static void glTextureSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, long p8) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7, p8));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTextureSubImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, java.nio.ByteBuffer p10) {
        BridgeSupport.enqueueSnapshot(p10, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureSubImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, snapshot));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTextureSubImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, java.nio.DoubleBuffer p10) {
        BridgeSupport.enqueueSnapshot(p10, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureSubImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTextureSubImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, java.nio.FloatBuffer p10) {
        BridgeSupport.enqueueSnapshot(p10, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureSubImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTextureSubImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, java.nio.IntBuffer p10) {
        BridgeSupport.enqueueSnapshot(p10, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureSubImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTextureSubImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, java.nio.ShortBuffer p10) {
        BridgeSupport.enqueueSnapshot(p10, snapshot -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureSubImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, snapshot.asShortBuffer()));
    }

    // 命令型
    public static void glTextureSubImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, long p10) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glTextureSubImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    }

    // 命令型
    public static void glTransformFeedbackBufferBase(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glTransformFeedbackBufferBase(p0, p1, p2));
    }

    // 命令型
    public static void glTransformFeedbackBufferRange(int p0, int p1, int p2, long p3, long p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glTransformFeedbackBufferRange(p0, p1, p2, p3, p4));
    }

    // 阻塞取值型
    public static boolean glUnmapNamedBuffer(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBDirectStateAccess.glUnmapNamedBuffer(p0));
    }

    // 命令型
    public static void glVertexArrayAttribBinding(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glVertexArrayAttribBinding(p0, p1, p2));
    }

    // 命令型
    public static void glVertexArrayAttribFormat(int p0, int p1, int p2, int p3, boolean p4, int p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glVertexArrayAttribFormat(p0, p1, p2, p3, p4, p5));
    }

    // 命令型
    public static void glVertexArrayAttribIFormat(int p0, int p1, int p2, int p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glVertexArrayAttribIFormat(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glVertexArrayAttribLFormat(int p0, int p1, int p2, int p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glVertexArrayAttribLFormat(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glVertexArrayBindingDivisor(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glVertexArrayBindingDivisor(p0, p1, p2));
    }

    // 命令型
    public static void glVertexArrayElementBuffer(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glVertexArrayElementBuffer(p0, p1));
    }

    // 命令型
    public static void glVertexArrayVertexBuffer(int p0, int p1, int p2, long p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBDirectStateAccess.glVertexArrayVertexBuffer(p0, p1, p2, p3, p4));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glVertexArrayVertexBuffers(int p0, int p1, int p2, java.nio.IntBuffer p3, org.lwjgl.PointerBuffer p4, java.nio.IntBuffer p5) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.ARBDirectStateAccess.glVertexArrayVertexBuffers(p0, p1, p2, p3, p4, p5));
    }
}
