// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ARBGetProgramBinary 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class ARBGetProgramBinary {
    private ARBGetProgramBinary() {
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetProgramBinary(int p0, java.nio.IntBuffer p1, java.nio.IntBuffer p2, java.nio.ByteBuffer p3) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.ARBGetProgramBinary.glGetProgramBinary(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramBinary(int p0, int p1, java.nio.ByteBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBGetProgramBinary.glProgramBinary(p0, p1, snapshot));
    }

    // 命令型
    public static void glProgramParameteri(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBGetProgramBinary.glProgramParameteri(p0, p1, p2));
    }
}
