// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ARBGpuShaderFp64 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class ARBGpuShaderFp64 {
    private ARBGpuShaderFp64() {
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetUniform(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillDoubles(p2, 16, buf -> org.lwjgl.opengl.ARBGpuShaderFp64.glGetUniform(p0, p1, buf)));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform1EXT(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glProgramUniform1EXT(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 命令型
    public static void glProgramUniform1dEXT(int p0, int p1, double p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBGpuShaderFp64.glProgramUniform1dEXT(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform2EXT(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glProgramUniform2EXT(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 命令型
    public static void glProgramUniform2dEXT(int p0, int p1, double p2, double p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBGpuShaderFp64.glProgramUniform2dEXT(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform3EXT(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glProgramUniform3EXT(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 命令型
    public static void glProgramUniform3dEXT(int p0, int p1, double p2, double p3, double p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBGpuShaderFp64.glProgramUniform3dEXT(p0, p1, p2, p3, p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform4EXT(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glProgramUniform4EXT(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 命令型
    public static void glProgramUniform4dEXT(int p0, int p1, double p2, double p3, double p4, double p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBGpuShaderFp64.glProgramUniform4dEXT(p0, p1, p2, p3, p4, p5));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix2EXT(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glProgramUniformMatrix2EXT(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix2x3EXT(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glProgramUniformMatrix2x3EXT(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix2x4EXT(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glProgramUniformMatrix2x4EXT(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix3EXT(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glProgramUniformMatrix3EXT(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix3x2EXT(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glProgramUniformMatrix3x2EXT(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix3x4EXT(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glProgramUniformMatrix3x4EXT(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix4EXT(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glProgramUniformMatrix4EXT(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix4x2EXT(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glProgramUniformMatrix4x2EXT(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix4x3EXT(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glProgramUniformMatrix4x3EXT(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniform1(int p0, java.nio.DoubleBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glUniform1(p0, snapshot.asDoubleBuffer()));
    }

    // 命令型
    public static void glUniform1d(int p0, double p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBGpuShaderFp64.glUniform1d(p0, p1));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniform2(int p0, java.nio.DoubleBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glUniform2(p0, snapshot.asDoubleBuffer()));
    }

    // 命令型
    public static void glUniform2d(int p0, double p1, double p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBGpuShaderFp64.glUniform2d(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniform3(int p0, java.nio.DoubleBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glUniform3(p0, snapshot.asDoubleBuffer()));
    }

    // 命令型
    public static void glUniform3d(int p0, double p1, double p2, double p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBGpuShaderFp64.glUniform3d(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniform4(int p0, java.nio.DoubleBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glUniform4(p0, snapshot.asDoubleBuffer()));
    }

    // 命令型
    public static void glUniform4d(int p0, double p1, double p2, double p3, double p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBGpuShaderFp64.glUniform4d(p0, p1, p2, p3, p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniformMatrix2(int p0, boolean p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glUniformMatrix2(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniformMatrix2x3(int p0, boolean p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glUniformMatrix2x3(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniformMatrix2x4(int p0, boolean p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glUniformMatrix2x4(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniformMatrix3(int p0, boolean p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glUniformMatrix3(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniformMatrix3x2(int p0, boolean p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glUniformMatrix3x2(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniformMatrix3x4(int p0, boolean p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glUniformMatrix3x4(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniformMatrix4(int p0, boolean p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glUniformMatrix4(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniformMatrix4x2(int p0, boolean p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glUniformMatrix4x2(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniformMatrix4x3(int p0, boolean p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBGpuShaderFp64.glUniformMatrix4x3(p0, p1, snapshot.asDoubleBuffer()));
    }
}
