// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ARBInternalformatQuery2 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class ARBInternalformatQuery2 {
    private ARBInternalformatQuery2() {
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetInternalformat(int p0, int p1, int p2, java.nio.LongBuffer p3) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillLongs(p3, 16, buf -> org.lwjgl.opengl.ARBInternalformatQuery2.glGetInternalformat(p0, p1, p2, buf)));
    }

    // 阻塞取值型
    public static long glGetInternalformati64(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBInternalformatQuery2.glGetInternalformati64(p0, p1, p2));
    }
}
