// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ARBInstancedArrays 的 bridge 镜像生成基类（全量镜像兜底面）。
 * <p>
 * 手写类 {@link ARBInstancedArrays} extends 本类：invokestatic 的方法解析先命中手写类
 * 自身声明（顶点流/状态仿真/id stash/map 仿真等精心语义），未覆盖的
 * 落到本基类的通用录制/阻塞语义——手写永远优先，生成物只兜底。
 */
public class ARBInstancedArraysGen {
    protected ARBInstancedArraysGen() {
    }

    // 命令型
    public static void glVertexAttribDivisorARB(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBInstancedArrays.glVertexAttribDivisorARB(p0, p1));
    }
}
