// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ARBMapBufferRange 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class ARBMapBufferRange {
    private ARBMapBufferRange() {
    }

    // 命令型
    public static void glFlushMappedBufferRange(int p0, long p1, long p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBMapBufferRange.glFlushMappedBufferRange(p0, p1, p2));
    }

    // 阻塞取值型
    public static java.nio.ByteBuffer glMapBufferRange(int p0, long p1, long p2, int p3, java.nio.ByteBuffer p4) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBMapBufferRange.glMapBufferRange(p0, p1, p2, p3, p4));
    }
}
