// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ARBMultitexture 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class ARBMultitexture {
    private ARBMultitexture() {
    }

    // 命令型
    public static void glActiveTextureARB(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBMultitexture.glActiveTextureARB(p0));
    }

    // 命令型
    public static void glClientActiveTextureARB(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBMultitexture.glClientActiveTextureARB(p0));
    }

    // 命令型
    public static void glMultiTexCoord1dARB(int p0, double p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBMultitexture.glMultiTexCoord1dARB(p0, p1));
    }

    // 命令型
    public static void glMultiTexCoord1fARB(int p0, float p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBMultitexture.glMultiTexCoord1fARB(p0, p1));
    }

    // 命令型
    public static void glMultiTexCoord1iARB(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBMultitexture.glMultiTexCoord1iARB(p0, p1));
    }

    // 命令型
    public static void glMultiTexCoord1sARB(int p0, short p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBMultitexture.glMultiTexCoord1sARB(p0, p1));
    }

    // 命令型
    public static void glMultiTexCoord2dARB(int p0, double p1, double p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBMultitexture.glMultiTexCoord2dARB(p0, p1, p2));
    }

    // 命令型
    public static void glMultiTexCoord2fARB(int p0, float p1, float p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBMultitexture.glMultiTexCoord2fARB(p0, p1, p2));
    }

    // 命令型
    public static void glMultiTexCoord2iARB(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBMultitexture.glMultiTexCoord2iARB(p0, p1, p2));
    }

    // 命令型
    public static void glMultiTexCoord2sARB(int p0, short p1, short p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBMultitexture.glMultiTexCoord2sARB(p0, p1, p2));
    }

    // 命令型
    public static void glMultiTexCoord3dARB(int p0, double p1, double p2, double p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBMultitexture.glMultiTexCoord3dARB(p0, p1, p2, p3));
    }

    // 命令型
    public static void glMultiTexCoord3fARB(int p0, float p1, float p2, float p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBMultitexture.glMultiTexCoord3fARB(p0, p1, p2, p3));
    }

    // 命令型
    public static void glMultiTexCoord3iARB(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBMultitexture.glMultiTexCoord3iARB(p0, p1, p2, p3));
    }

    // 命令型
    public static void glMultiTexCoord3sARB(int p0, short p1, short p2, short p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBMultitexture.glMultiTexCoord3sARB(p0, p1, p2, p3));
    }

    // 命令型
    public static void glMultiTexCoord4dARB(int p0, double p1, double p2, double p3, double p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBMultitexture.glMultiTexCoord4dARB(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glMultiTexCoord4fARB(int p0, float p1, float p2, float p3, float p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBMultitexture.glMultiTexCoord4fARB(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glMultiTexCoord4iARB(int p0, int p1, int p2, int p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBMultitexture.glMultiTexCoord4iARB(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glMultiTexCoord4sARB(int p0, short p1, short p2, short p3, short p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBMultitexture.glMultiTexCoord4sARB(p0, p1, p2, p3, p4));
    }
}
