// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ARBPixelBufferObject 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class ARBPixelBufferObject {
    private ARBPixelBufferObject() {
    }

    // 命令型（ARRAY_BUFFER 绑定簿记：录制侧 pointerState/仿真状态 + 执行侧簿记与溯源环；不含 BufferMapEmulator——ARB 路径既定不喂 map 仿真器，与手写 ARBVertexBufferObject 对齐）
    public static void glBindBufferARB(int p0, int p1) {
        BridgeSupport.simulatedState().onBindBuffer(p0, p1);
        final String recordThread;
        if (p0 == org.lwjgl.opengl.ARBVertexBufferObject.GL_ARRAY_BUFFER_ARB) {
            BridgeSupport.pointerState().setArrayBufferBinding(p1);
            recordThread = Thread.currentThread().getName();
        } else {
            recordThread = null;
        }
        BridgeSupport.enqueue(() -> {
            org.lwjgl.opengl.ARBPixelBufferObject.glBindBufferARB(p0, p1);
            if (p0 == org.lwjgl.opengl.ARBVertexBufferObject.GL_ARRAY_BUFFER_ARB) {
                BridgeSupport.executedArrayBufferBinding(p1, "ARBPixelBufferObject", recordThread);
            }
        });
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferDataARB(int p0, java.nio.ByteBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBPixelBufferObject.glBufferDataARB(p0, snapshot, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferDataARB(int p0, java.nio.DoubleBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBPixelBufferObject.glBufferDataARB(p0, snapshot.asDoubleBuffer(), p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferDataARB(int p0, java.nio.FloatBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBPixelBufferObject.glBufferDataARB(p0, snapshot.asFloatBuffer(), p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferDataARB(int p0, java.nio.IntBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBPixelBufferObject.glBufferDataARB(p0, snapshot.asIntBuffer(), p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferDataARB(int p0, java.nio.ShortBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBPixelBufferObject.glBufferDataARB(p0, snapshot.asShortBuffer(), p2));
    }

    // 命令型
    public static void glBufferDataARB(int p0, long p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBPixelBufferObject.glBufferDataARB(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferSubDataARB(int p0, long p1, java.nio.ByteBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBPixelBufferObject.glBufferSubDataARB(p0, p1, snapshot));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferSubDataARB(int p0, long p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBPixelBufferObject.glBufferSubDataARB(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferSubDataARB(int p0, long p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBPixelBufferObject.glBufferSubDataARB(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferSubDataARB(int p0, long p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBPixelBufferObject.glBufferSubDataARB(p0, p1, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferSubDataARB(int p0, long p1, java.nio.ShortBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBPixelBufferObject.glBufferSubDataARB(p0, p1, snapshot.asShortBuffer()));
    }

    // 命令型（删除当前绑定的 buffer 会重置 ARRAY_BUFFER 绑定：录制/执行侧簿记同步）
    public static void glDeleteBuffersARB(int p0) {
        if (BridgeSupport.pointerState().arrayBufferBinding() == p0) {
            BridgeSupport.pointerState().setArrayBufferBinding(0);
        }
        final String recordThread = Thread.currentThread().getName();
        BridgeSupport.enqueue(() -> {
            org.lwjgl.opengl.ARBPixelBufferObject.glDeleteBuffersARB(p0);
            if (BridgeSupport.executedArrayBufferBinding() == p0) {
                BridgeSupport.executedArrayBufferBinding(0, "ARBPixelBufferObject.glDeleteBuffersARB", recordThread);
            }
        });
    }

    // 快照命令型（删除当前绑定的 buffer 会重置 ARRAY_BUFFER 绑定：录制/执行侧簿记同步）
    public static void glDeleteBuffersARB(java.nio.IntBuffer p0) {
        while (p0.hasRemaining()) {
            if (BridgeSupport.pointerState().arrayBufferBinding() == p0.get()) {
                BridgeSupport.pointerState().setArrayBufferBinding(0);
            }
        }
        p0.rewind();
        final String recordThread = Thread.currentThread().getName();
        BridgeSupport.enqueueSnapshot(p0, snapshot -> {
            final java.nio.IntBuffer view = snapshot.asIntBuffer();
            final int count = view.remaining();
            org.lwjgl.opengl.ARBPixelBufferObject.glDeleteBuffersARB(view);
            for (int i = 0; i < count; i++) {
                if (BridgeSupport.executedArrayBufferBinding() == view.get(i)) {
                    BridgeSupport.executedArrayBufferBinding(0, "ARBPixelBufferObject.glDeleteBuffersARB", recordThread);
                }
            }
        });
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glGenBuffersARB() {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.ARBPixelBufferObject.glGenBuffersARB());
    }

    // 阻塞资源型（glGen 族，不计 StallDetector）
    public static void glGenBuffersARB(java.nio.IntBuffer p0) {
        BridgeSupport.blockingWaitResource(() -> org.lwjgl.opengl.ARBPixelBufferObject.glGenBuffersARB(p0));
    }

    // 阻塞取值型
    public static int glGetBufferParameterARB(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBPixelBufferObject.glGetBufferParameterARB(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetBufferParameterARB(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.ARBPixelBufferObject.glGetBufferParameterARB(p0, p1, buf)));
    }

    // 阻塞取值型
    public static int glGetBufferParameteriARB(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBPixelBufferObject.glGetBufferParameteriARB(p0, p1));
    }

    // 阻塞取值型
    public static java.nio.ByteBuffer glGetBufferPointerARB(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBPixelBufferObject.glGetBufferPointerARB(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetBufferSubDataARB(int p0, long p1, java.nio.ByteBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillBooleans(p2, 16, buf -> org.lwjgl.opengl.ARBPixelBufferObject.glGetBufferSubDataARB(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetBufferSubDataARB(int p0, long p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillDoubles(p2, 16, buf -> org.lwjgl.opengl.ARBPixelBufferObject.glGetBufferSubDataARB(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetBufferSubDataARB(int p0, long p1, java.nio.FloatBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p2, 16, buf -> org.lwjgl.opengl.ARBPixelBufferObject.glGetBufferSubDataARB(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetBufferSubDataARB(int p0, long p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.ARBPixelBufferObject.glGetBufferSubDataARB(p0, p1, buf)));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetBufferSubDataARB(int p0, long p1, java.nio.ShortBuffer p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.ARBPixelBufferObject.glGetBufferSubDataARB(p0, p1, p2));
    }

    // 阻塞取值型
    public static boolean glIsBufferARB(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBPixelBufferObject.glIsBufferARB(p0));
    }

    // 阻塞取值型
    public static java.nio.ByteBuffer glMapBufferARB(int p0, int p1, java.nio.ByteBuffer p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBPixelBufferObject.glMapBufferARB(p0, p1, p2));
    }

    // 阻塞取值型
    public static java.nio.ByteBuffer glMapBufferARB(int p0, int p1, long p2, java.nio.ByteBuffer p3) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBPixelBufferObject.glMapBufferARB(p0, p1, p2, p3));
    }

    // 阻塞取值型
    public static boolean glUnmapBufferARB(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBPixelBufferObject.glUnmapBufferARB(p0));
    }
}
