// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ARBProgramInterfaceQuery 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class ARBProgramInterfaceQuery {
    private ARBProgramInterfaceQuery() {
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetProgramInterface(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p3, 16, buf -> org.lwjgl.opengl.ARBProgramInterfaceQuery.glGetProgramInterface(p0, p1, p2, buf)));
    }

    // 阻塞取值型
    public static int glGetProgramInterfacei(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBProgramInterfaceQuery.glGetProgramInterfacei(p0, p1, p2));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetProgramResource(int p0, int p1, int p2, java.nio.IntBuffer p3, java.nio.IntBuffer p4, java.nio.IntBuffer p5) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.ARBProgramInterfaceQuery.glGetProgramResource(p0, p1, p2, p3, p4, p5));
    }

    // 阻塞取值型
    public static int glGetProgramResourceIndex(int p0, int p1, java.lang.CharSequence p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBProgramInterfaceQuery.glGetProgramResourceIndex(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetProgramResourceIndex(int p0, int p1, java.nio.ByteBuffer p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBProgramInterfaceQuery.glGetProgramResourceIndex(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetProgramResourceLocation(int p0, int p1, java.lang.CharSequence p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBProgramInterfaceQuery.glGetProgramResourceLocation(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetProgramResourceLocation(int p0, int p1, java.nio.ByteBuffer p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBProgramInterfaceQuery.glGetProgramResourceLocation(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetProgramResourceLocationIndex(int p0, int p1, java.lang.CharSequence p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBProgramInterfaceQuery.glGetProgramResourceLocationIndex(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetProgramResourceLocationIndex(int p0, int p1, java.nio.ByteBuffer p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBProgramInterfaceQuery.glGetProgramResourceLocationIndex(p0, p1, p2));
    }

    // 阻塞取值型
    public static java.lang.String glGetProgramResourceName(int p0, int p1, int p2, int p3) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBProgramInterfaceQuery.glGetProgramResourceName(p0, p1, p2, p3));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetProgramResourceName(int p0, int p1, int p2, java.nio.IntBuffer p3, java.nio.ByteBuffer p4) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.ARBProgramInterfaceQuery.glGetProgramResourceName(p0, p1, p2, p3, p4));
    }
}
