// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ARBShaderSubroutine 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class ARBShaderSubroutine {
    private ARBShaderSubroutine() {
    }

    // 阻塞取值型
    public static java.lang.String glGetActiveSubroutineName(int p0, int p1, int p2, int p3) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBShaderSubroutine.glGetActiveSubroutineName(p0, p1, p2, p3));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetActiveSubroutineName(int p0, int p1, int p2, java.nio.IntBuffer p3, java.nio.ByteBuffer p4) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.ARBShaderSubroutine.glGetActiveSubroutineName(p0, p1, p2, p3, p4));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetActiveSubroutineUniform(int p0, int p1, int p2, int p3, java.nio.IntBuffer p4) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p4, 16, buf -> org.lwjgl.opengl.ARBShaderSubroutine.glGetActiveSubroutineUniform(p0, p1, p2, p3, buf)));
    }

    // 阻塞取值型
    public static java.lang.String glGetActiveSubroutineUniformName(int p0, int p1, int p2, int p3) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBShaderSubroutine.glGetActiveSubroutineUniformName(p0, p1, p2, p3));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetActiveSubroutineUniformName(int p0, int p1, int p2, java.nio.IntBuffer p3, java.nio.ByteBuffer p4) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.ARBShaderSubroutine.glGetActiveSubroutineUniformName(p0, p1, p2, p3, p4));
    }

    // 阻塞取值型
    public static int glGetActiveSubroutineUniformi(int p0, int p1, int p2, int p3) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBShaderSubroutine.glGetActiveSubroutineUniformi(p0, p1, p2, p3));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetProgramStage(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p3, 16, buf -> org.lwjgl.opengl.ARBShaderSubroutine.glGetProgramStage(p0, p1, p2, buf)));
    }

    // 阻塞取值型
    public static int glGetProgramStagei(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBShaderSubroutine.glGetProgramStagei(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetSubroutineIndex(int p0, int p1, java.lang.CharSequence p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBShaderSubroutine.glGetSubroutineIndex(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetSubroutineIndex(int p0, int p1, java.nio.ByteBuffer p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBShaderSubroutine.glGetSubroutineIndex(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetSubroutineUniformLocation(int p0, int p1, java.lang.CharSequence p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBShaderSubroutine.glGetSubroutineUniformLocation(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetSubroutineUniformLocation(int p0, int p1, java.nio.ByteBuffer p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBShaderSubroutine.glGetSubroutineUniformLocation(p0, p1, p2));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetUniformSubroutineu(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.ARBShaderSubroutine.glGetUniformSubroutineu(p0, p1, buf)));
    }

    // 阻塞取值型
    public static int glGetUniformSubroutineui(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBShaderSubroutine.glGetUniformSubroutineui(p0, p1));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniformSubroutinesu(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBShaderSubroutine.glUniformSubroutinesu(p0, snapshot.asIntBuffer()));
    }
}
