// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ARBSeparateShaderObjects 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class ARBSeparateShaderObjects {
    private ARBSeparateShaderObjects() {
    }

    // 命令型
    public static void glActiveShaderProgram(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glActiveShaderProgram(p0, p1));
    }

    // 命令型
    public static void glBindProgramPipeline(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glBindProgramPipeline(p0));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glCreateShaderProgram(int p0, java.lang.CharSequence p1) {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glCreateShaderProgram(p0, p1));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glCreateShaderProgram(int p0, java.lang.CharSequence[] p1) {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glCreateShaderProgram(p0, p1));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glCreateShaderProgram(int p0, java.nio.ByteBuffer p1) {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glCreateShaderProgram(p0, p1));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glCreateShaderProgram(int p0, java.nio.ByteBuffer[] p1) {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glCreateShaderProgram(p0, p1));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glCreateShaderProgram(int p0, int p1, java.nio.ByteBuffer p2) {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glCreateShaderProgram(p0, p1, p2));
    }

    // 命令型
    public static void glDeleteProgramPipelines(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glDeleteProgramPipelines(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDeleteProgramPipelines(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glDeleteProgramPipelines(snapshot.asIntBuffer()));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glGenProgramPipelines() {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glGenProgramPipelines());
    }

    // 阻塞资源型（glGen 族，不计 StallDetector）
    public static void glGenProgramPipelines(java.nio.IntBuffer p0) {
        BridgeSupport.blockingWaitResource(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glGenProgramPipelines(p0));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetProgramPipeline(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.ARBSeparateShaderObjects.glGetProgramPipeline(p0, p1, buf)));
    }

    // 阻塞取值型
    public static java.lang.String glGetProgramPipelineInfoLog(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glGetProgramPipelineInfoLog(p0, p1));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetProgramPipelineInfoLog(int p0, java.nio.IntBuffer p1, java.nio.ByteBuffer p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glGetProgramPipelineInfoLog(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetProgramPipelinei(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glGetProgramPipelinei(p0, p1));
    }

    // 阻塞取值型
    public static boolean glIsProgramPipeline(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glIsProgramPipeline(p0));
    }

    // 命令型
    public static void glProgramParameteri(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramParameteri(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform1(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform1(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform1(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform1(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform1(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform1(p0, p1, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glProgramUniform1d(int p0, int p1, double p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform1d(p0, p1, p2));
    }

    // 命令型
    public static void glProgramUniform1f(int p0, int p1, float p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform1f(p0, p1, p2));
    }

    // 命令型
    public static void glProgramUniform1i(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform1i(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform1u(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform1u(p0, p1, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glProgramUniform1ui(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform1ui(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform2(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform2(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform2(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform2(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform2(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform2(p0, p1, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glProgramUniform2d(int p0, int p1, double p2, double p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform2d(p0, p1, p2, p3));
    }

    // 命令型
    public static void glProgramUniform2f(int p0, int p1, float p2, float p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform2f(p0, p1, p2, p3));
    }

    // 命令型
    public static void glProgramUniform2i(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform2i(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform2u(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform2u(p0, p1, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glProgramUniform2ui(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform2ui(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform3(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform3(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform3(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform3(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform3(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform3(p0, p1, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glProgramUniform3d(int p0, int p1, double p2, double p3, double p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform3d(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glProgramUniform3f(int p0, int p1, float p2, float p3, float p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform3f(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glProgramUniform3i(int p0, int p1, int p2, int p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform3i(p0, p1, p2, p3, p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform3u(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform3u(p0, p1, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glProgramUniform3ui(int p0, int p1, int p2, int p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform3ui(p0, p1, p2, p3, p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform4(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform4(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform4(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform4(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform4(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform4(p0, p1, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glProgramUniform4d(int p0, int p1, double p2, double p3, double p4, double p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform4d(p0, p1, p2, p3, p4, p5));
    }

    // 命令型
    public static void glProgramUniform4f(int p0, int p1, float p2, float p3, float p4, float p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform4f(p0, p1, p2, p3, p4, p5));
    }

    // 命令型
    public static void glProgramUniform4i(int p0, int p1, int p2, int p3, int p4, int p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform4i(p0, p1, p2, p3, p4, p5));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform4u(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform4u(p0, p1, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glProgramUniform4ui(int p0, int p1, int p2, int p3, int p4, int p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniform4ui(p0, p1, p2, p3, p4, p5));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix2(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniformMatrix2(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix2(int p0, int p1, boolean p2, java.nio.FloatBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniformMatrix2(p0, p1, p2, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix2x3(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniformMatrix2x3(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix2x3(int p0, int p1, boolean p2, java.nio.FloatBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniformMatrix2x3(p0, p1, p2, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix2x4(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniformMatrix2x4(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix2x4(int p0, int p1, boolean p2, java.nio.FloatBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniformMatrix2x4(p0, p1, p2, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix3(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniformMatrix3(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix3(int p0, int p1, boolean p2, java.nio.FloatBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniformMatrix3(p0, p1, p2, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix3x2(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniformMatrix3x2(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix3x2(int p0, int p1, boolean p2, java.nio.FloatBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniformMatrix3x2(p0, p1, p2, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix3x4(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniformMatrix3x4(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix3x4(int p0, int p1, boolean p2, java.nio.FloatBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniformMatrix3x4(p0, p1, p2, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix4(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniformMatrix4(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix4(int p0, int p1, boolean p2, java.nio.FloatBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniformMatrix4(p0, p1, p2, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix4x2(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniformMatrix4x2(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix4x2(int p0, int p1, boolean p2, java.nio.FloatBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniformMatrix4x2(p0, p1, p2, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix4x3(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniformMatrix4x3(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix4x3(int p0, int p1, boolean p2, java.nio.FloatBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBSeparateShaderObjects.glProgramUniformMatrix4x3(p0, p1, p2, snapshot.asFloatBuffer()));
    }

    // 命令型
    public static void glUseProgramStages(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glUseProgramStages(p0, p1, p2));
    }

    // 命令型
    public static void glValidateProgramPipeline(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSeparateShaderObjects.glValidateProgramPipeline(p0));
    }
}
