// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ARBSamplerObjects 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class ARBSamplerObjects {
    private ARBSamplerObjects() {
    }

    // 命令型
    public static void glBindSampler(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSamplerObjects.glBindSampler(p0, p1));
    }

    // 命令型
    public static void glDeleteSamplers(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSamplerObjects.glDeleteSamplers(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDeleteSamplers(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.ARBSamplerObjects.glDeleteSamplers(snapshot.asIntBuffer()));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glGenSamplers() {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.ARBSamplerObjects.glGenSamplers());
    }

    // 阻塞资源型（glGen 族，不计 StallDetector）
    public static void glGenSamplers(java.nio.IntBuffer p0) {
        BridgeSupport.blockingWaitResource(() -> org.lwjgl.opengl.ARBSamplerObjects.glGenSamplers(p0));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetSamplerParameter(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p2, 16, buf -> org.lwjgl.opengl.ARBSamplerObjects.glGetSamplerParameter(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetSamplerParameter(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.ARBSamplerObjects.glGetSamplerParameter(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetSamplerParameterI(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.ARBSamplerObjects.glGetSamplerParameterI(p0, p1, buf)));
    }

    // 阻塞取值型
    public static int glGetSamplerParameterIi(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBSamplerObjects.glGetSamplerParameterIi(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetSamplerParameterIu(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.ARBSamplerObjects.glGetSamplerParameterIu(p0, p1, buf)));
    }

    // 阻塞取值型
    public static int glGetSamplerParameterIui(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBSamplerObjects.glGetSamplerParameterIui(p0, p1));
    }

    // 阻塞取值型
    public static float glGetSamplerParameterf(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBSamplerObjects.glGetSamplerParameterf(p0, p1));
    }

    // 阻塞取值型
    public static int glGetSamplerParameteri(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBSamplerObjects.glGetSamplerParameteri(p0, p1));
    }

    // 阻塞取值型
    public static boolean glIsSampler(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBSamplerObjects.glIsSampler(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glSamplerParameter(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBSamplerObjects.glSamplerParameter(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glSamplerParameter(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBSamplerObjects.glSamplerParameter(p0, p1, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glSamplerParameterI(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBSamplerObjects.glSamplerParameterI(p0, p1, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glSamplerParameterIu(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBSamplerObjects.glSamplerParameterIu(p0, p1, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glSamplerParameterf(int p0, int p1, float p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSamplerObjects.glSamplerParameterf(p0, p1, p2));
    }

    // 命令型
    public static void glSamplerParameteri(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBSamplerObjects.glSamplerParameteri(p0, p1, p2));
    }
}
