// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ARBShadingLanguageInclude 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class ARBShadingLanguageInclude {
    private ARBShadingLanguageInclude() {
    }

    // 命令型（字符串数组录制时刻快照）
    public static void glCompileShaderIncludeARB(int p0, java.lang.CharSequence[] p1) {
        final java.lang.CharSequence[] copy = p1.clone();
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBShadingLanguageInclude.glCompileShaderIncludeARB(p0, copy));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCompileShaderIncludeARB(int p0, int p1, java.nio.ByteBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.ARBShadingLanguageInclude.glCompileShaderIncludeARB(p0, p1, snapshot));
    }

    // 命令型（字符串捕获，不可变）
    public static void glDeleteNamedStringARB(java.lang.CharSequence p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBShadingLanguageInclude.glDeleteNamedStringARB(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDeleteNamedStringARB(java.nio.ByteBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.ARBShadingLanguageInclude.glDeleteNamedStringARB(snapshot));
    }

    // 阻塞取值型
    public static java.lang.String glGetNamedStringARB(java.lang.CharSequence p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBShadingLanguageInclude.glGetNamedStringARB(p0, p1));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetNamedStringARB(java.lang.CharSequence p0, java.nio.IntBuffer p1, java.nio.ByteBuffer p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.ARBShadingLanguageInclude.glGetNamedStringARB(p0, p1, p2));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetNamedStringARB(java.nio.ByteBuffer p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.ARBShadingLanguageInclude.glGetNamedStringARB(p0, p1, p2));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetNamedStringARB(java.nio.ByteBuffer p0, java.nio.IntBuffer p1, java.nio.ByteBuffer p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.ARBShadingLanguageInclude.glGetNamedStringARB(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetNamedStringiARB(java.lang.CharSequence p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBShadingLanguageInclude.glGetNamedStringiARB(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetNamedStringiARB(java.lang.CharSequence p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.ARBShadingLanguageInclude.glGetNamedStringiARB(p0, p1, buf)));
    }

    // 阻塞取值型
    public static boolean glIsNamedStringARB(java.lang.CharSequence p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBShadingLanguageInclude.glIsNamedStringARB(p0));
    }

    // 阻塞取值型
    public static boolean glIsNamedStringARB(java.nio.ByteBuffer p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBShadingLanguageInclude.glIsNamedStringARB(p0));
    }

    // 命令型（字符串捕获，不可变）
    public static void glNamedStringARB(int p0, java.lang.CharSequence p1, java.lang.CharSequence p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBShadingLanguageInclude.glNamedStringARB(p0, p1, p2));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glNamedStringARB(int p0, java.nio.ByteBuffer p1, java.nio.ByteBuffer p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.ARBShadingLanguageInclude.glNamedStringARB(p0, p1, p2));
    }
}
