// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ARBTransformFeedback2 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class ARBTransformFeedback2 {
    private ARBTransformFeedback2() {
    }

    // 命令型
    public static void glBindTransformFeedback(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBTransformFeedback2.glBindTransformFeedback(p0, p1));
    }

    // 命令型
    public static void glDeleteTransformFeedbacks(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBTransformFeedback2.glDeleteTransformFeedbacks(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDeleteTransformFeedbacks(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.ARBTransformFeedback2.glDeleteTransformFeedbacks(snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glDrawTransformFeedback(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBTransformFeedback2.glDrawTransformFeedback(p0, p1));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glGenTransformFeedbacks() {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.ARBTransformFeedback2.glGenTransformFeedbacks());
    }

    // 阻塞资源型（glGen 族，不计 StallDetector）
    public static void glGenTransformFeedbacks(java.nio.IntBuffer p0) {
        BridgeSupport.blockingWaitResource(() -> org.lwjgl.opengl.ARBTransformFeedback2.glGenTransformFeedbacks(p0));
    }

    // 阻塞取值型
    public static boolean glIsTransformFeedback(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBTransformFeedback2.glIsTransformFeedback(p0));
    }

    // 命令型
    public static void glPauseTransformFeedback() {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBTransformFeedback2.glPauseTransformFeedback());
    }

    // 命令型
    public static void glResumeTransformFeedback() {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBTransformFeedback2.glResumeTransformFeedback());
    }
}
