// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ARBTransformFeedback3 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class ARBTransformFeedback3 {
    private ARBTransformFeedback3() {
    }

    // 命令型
    public static void glBeginQueryIndexed(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBTransformFeedback3.glBeginQueryIndexed(p0, p1, p2));
    }

    // 命令型
    public static void glDrawTransformFeedbackStream(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBTransformFeedback3.glDrawTransformFeedbackStream(p0, p1, p2));
    }

    // 命令型
    public static void glEndQueryIndexed(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBTransformFeedback3.glEndQueryIndexed(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetQueryIndexed(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p3, 16, buf -> org.lwjgl.opengl.ARBTransformFeedback3.glGetQueryIndexed(p0, p1, p2, buf)));
    }

    // 阻塞取值型
    public static int glGetQueryIndexedi(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBTransformFeedback3.glGetQueryIndexedi(p0, p1, p2));
    }
}
