// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ARBTextureCompression 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class ARBTextureCompression {
    private ARBTextureCompression() {
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCompressedTexImage1DARB(int p0, int p1, int p2, int p3, int p4, java.nio.ByteBuffer p5) {
        BridgeSupport.enqueueSnapshot(p5, snapshot -> org.lwjgl.opengl.ARBTextureCompression.glCompressedTexImage1DARB(p0, p1, p2, p3, p4, snapshot));
    }

    // 命令型
    public static void glCompressedTexImage1DARB(int p0, int p1, int p2, int p3, int p4, int p5, long p6) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBTextureCompression.glCompressedTexImage1DARB(p0, p1, p2, p3, p4, p5, p6));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCompressedTexImage2DARB(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.ByteBuffer p6) {
        BridgeSupport.enqueueSnapshot(p6, snapshot -> org.lwjgl.opengl.ARBTextureCompression.glCompressedTexImage2DARB(p0, p1, p2, p3, p4, p5, snapshot));
    }

    // 命令型
    public static void glCompressedTexImage2DARB(int p0, int p1, int p2, int p3, int p4, int p5, int p6, long p7) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBTextureCompression.glCompressedTexImage2DARB(p0, p1, p2, p3, p4, p5, p6, p7));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCompressedTexImage3DARB(int p0, int p1, int p2, int p3, int p4, int p5, int p6, java.nio.ByteBuffer p7) {
        BridgeSupport.enqueueSnapshot(p7, snapshot -> org.lwjgl.opengl.ARBTextureCompression.glCompressedTexImage3DARB(p0, p1, p2, p3, p4, p5, p6, snapshot));
    }

    // 命令型
    public static void glCompressedTexImage3DARB(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, long p8) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBTextureCompression.glCompressedTexImage3DARB(p0, p1, p2, p3, p4, p5, p6, p7, p8));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCompressedTexSubImage1DARB(int p0, int p1, int p2, int p3, int p4, java.nio.ByteBuffer p5) {
        BridgeSupport.enqueueSnapshot(p5, snapshot -> org.lwjgl.opengl.ARBTextureCompression.glCompressedTexSubImage1DARB(p0, p1, p2, p3, p4, snapshot));
    }

    // 命令型
    public static void glCompressedTexSubImage1DARB(int p0, int p1, int p2, int p3, int p4, int p5, long p6) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBTextureCompression.glCompressedTexSubImage1DARB(p0, p1, p2, p3, p4, p5, p6));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCompressedTexSubImage2DARB(int p0, int p1, int p2, int p3, int p4, int p5, int p6, java.nio.ByteBuffer p7) {
        BridgeSupport.enqueueSnapshot(p7, snapshot -> org.lwjgl.opengl.ARBTextureCompression.glCompressedTexSubImage2DARB(p0, p1, p2, p3, p4, p5, p6, snapshot));
    }

    // 命令型
    public static void glCompressedTexSubImage2DARB(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, long p8) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBTextureCompression.glCompressedTexSubImage2DARB(p0, p1, p2, p3, p4, p5, p6, p7, p8));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCompressedTexSubImage3DARB(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, java.nio.ByteBuffer p9) {
        BridgeSupport.enqueueSnapshot(p9, snapshot -> org.lwjgl.opengl.ARBTextureCompression.glCompressedTexSubImage3DARB(p0, p1, p2, p3, p4, p5, p6, p7, p8, snapshot));
    }

    // 命令型
    public static void glCompressedTexSubImage3DARB(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, long p10) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBTextureCompression.glCompressedTexSubImage3DARB(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetCompressedTexImageARB(int p0, int p1, java.nio.ByteBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillBooleans(p2, 16, buf -> org.lwjgl.opengl.ARBTextureCompression.glGetCompressedTexImageARB(p0, p1, buf)));
    }

    // 命令型
    public static void glGetCompressedTexImageARB(int p0, int p1, long p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBTextureCompression.glGetCompressedTexImageARB(p0, p1, p2));
    }
}
