// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ARBVertexAttribBinding 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class ARBVertexAttribBinding {
    private ARBVertexAttribBinding() {
    }

    // 命令型
    public static void glBindVertexBuffer(int p0, int p1, long p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBVertexAttribBinding.glBindVertexBuffer(p0, p1, p2, p3));
    }

    // 命令型
    public static void glVertexAttribBinding(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBVertexAttribBinding.glVertexAttribBinding(p0, p1));
    }

    // 命令型
    public static void glVertexAttribFormat(int p0, int p1, int p2, boolean p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBVertexAttribBinding.glVertexAttribFormat(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glVertexAttribIFormat(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBVertexAttribBinding.glVertexAttribIFormat(p0, p1, p2, p3));
    }

    // 命令型
    public static void glVertexAttribLFormat(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBVertexAttribBinding.glVertexAttribLFormat(p0, p1, p2, p3));
    }

    // 命令型
    public static void glVertexBindingDivisor(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBVertexAttribBinding.glVertexBindingDivisor(p0, p1));
    }
}
