// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ARBVertexArrayObject 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class ARBVertexArrayObject {
    private ARBVertexArrayObject() {
    }

    // 命令型
    public static void glBindVertexArray(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBVertexArrayObject.glBindVertexArray(p0));
    }

    // 命令型
    public static void glDeleteVertexArrays(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBVertexArrayObject.glDeleteVertexArrays(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDeleteVertexArrays(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.ARBVertexArrayObject.glDeleteVertexArrays(snapshot.asIntBuffer()));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glGenVertexArrays() {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.ARBVertexArrayObject.glGenVertexArrays());
    }

    // 阻塞资源型（glGen 族，不计 StallDetector）
    public static void glGenVertexArrays(java.nio.IntBuffer p0) {
        BridgeSupport.blockingWaitResource(() -> org.lwjgl.opengl.ARBVertexArrayObject.glGenVertexArrays(p0));
    }

    // 阻塞取值型
    public static boolean glIsVertexArray(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.ARBVertexArrayObject.glIsVertexArray(p0));
    }
}
