// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ARBVertexAttrib64bit 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class ARBVertexAttrib64bit {
    private ARBVertexAttrib64bit() {
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetVertexAttribL(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillDoubles(p2, 16, buf -> org.lwjgl.opengl.ARBVertexAttrib64bit.glGetVertexAttribL(p0, p1, buf)));
    }

    // 命令型
    public static void glVertexArrayVertexAttribLOffsetEXT(int p0, int p1, int p2, int p3, int p4, int p5, long p6) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBVertexAttrib64bit.glVertexArrayVertexAttribLOffsetEXT(p0, p1, p2, p3, p4, p5, p6));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribL1(int p0, java.nio.DoubleBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBVertexAttrib64bit.glVertexAttribL1(p0, snapshot.asDoubleBuffer()));
    }

    // 命令型
    public static void glVertexAttribL1d(int p0, double p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBVertexAttrib64bit.glVertexAttribL1d(p0, p1));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribL2(int p0, java.nio.DoubleBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBVertexAttrib64bit.glVertexAttribL2(p0, snapshot.asDoubleBuffer()));
    }

    // 命令型
    public static void glVertexAttribL2d(int p0, double p1, double p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBVertexAttrib64bit.glVertexAttribL2d(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribL3(int p0, java.nio.DoubleBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBVertexAttrib64bit.glVertexAttribL3(p0, snapshot.asDoubleBuffer()));
    }

    // 命令型
    public static void glVertexAttribL3d(int p0, double p1, double p2, double p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBVertexAttrib64bit.glVertexAttribL3d(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribL4(int p0, java.nio.DoubleBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ARBVertexAttrib64bit.glVertexAttribL4(p0, snapshot.asDoubleBuffer()));
    }

    // 命令型
    public static void glVertexAttribL4d(int p0, double p1, double p2, double p3, double p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBVertexAttrib64bit.glVertexAttribL4d(p0, p1, p2, p3, p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribLPointer(int p0, int p1, int p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.ARBVertexAttrib64bit.glVertexAttribLPointer(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 命令型
    public static void glVertexAttribLPointer(int p0, int p1, int p2, long p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ARBVertexAttrib64bit.glVertexAttribLPointer(p0, p1, p2, p3));
    }
}
