// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ATIElementArray 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class ATIElementArray {
    private ATIElementArray() {
    }

    // 命令型
    public static void glDrawElementArrayATI(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ATIElementArray.glDrawElementArrayATI(p0, p1));
    }

    // 命令型
    public static void glDrawRangeElementArrayATI(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ATIElementArray.glDrawRangeElementArrayATI(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glElementPointerATI(java.nio.ByteBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.ATIElementArray.glElementPointerATI(snapshot));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glElementPointerATI(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.ATIElementArray.glElementPointerATI(snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glElementPointerATI(java.nio.ShortBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.ATIElementArray.glElementPointerATI(snapshot.asShortBuffer()));
    }
}
