// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.ATIFragmentShader 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class ATIFragmentShader {
    private ATIFragmentShader() {
    }

    // 命令型
    public static void glAlphaFragmentOp1ATI(int p0, int p1, int p2, int p3, int p4, int p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ATIFragmentShader.glAlphaFragmentOp1ATI(p0, p1, p2, p3, p4, p5));
    }

    // 命令型
    public static void glAlphaFragmentOp2ATI(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ATIFragmentShader.glAlphaFragmentOp2ATI(p0, p1, p2, p3, p4, p5, p6, p7, p8));
    }

    // 命令型
    public static void glAlphaFragmentOp3ATI(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, int p10, int p11) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ATIFragmentShader.glAlphaFragmentOp3ATI(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11));
    }

    // 命令型
    public static void glBeginFragmentShaderATI() {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ATIFragmentShader.glBeginFragmentShaderATI());
    }

    // 命令型
    public static void glBindFragmentShaderATI(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ATIFragmentShader.glBindFragmentShaderATI(p0));
    }

    // 命令型
    public static void glColorFragmentOp1ATI(int p0, int p1, int p2, int p3, int p4, int p5, int p6) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ATIFragmentShader.glColorFragmentOp1ATI(p0, p1, p2, p3, p4, p5, p6));
    }

    // 命令型
    public static void glColorFragmentOp2ATI(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ATIFragmentShader.glColorFragmentOp2ATI(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9));
    }

    // 命令型
    public static void glColorFragmentOp3ATI(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, int p10, int p11, int p12) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ATIFragmentShader.glColorFragmentOp3ATI(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12));
    }

    // 命令型
    public static void glDeleteFragmentShaderATI(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ATIFragmentShader.glDeleteFragmentShaderATI(p0));
    }

    // 命令型
    public static void glEndFragmentShaderATI() {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ATIFragmentShader.glEndFragmentShaderATI());
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glGenFragmentShadersATI(int p0) {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.ATIFragmentShader.glGenFragmentShadersATI(p0));
    }

    // 命令型
    public static void glPassTexCoordATI(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ATIFragmentShader.glPassTexCoordATI(p0, p1, p2));
    }

    // 命令型
    public static void glSampleMapATI(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.ATIFragmentShader.glSampleMapATI(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glSetFragmentShaderConstantATI(int p0, java.nio.FloatBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.ATIFragmentShader.glSetFragmentShaderConstantATI(p0, snapshot.asFloatBuffer()));
    }
}
