// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.EXTFramebufferObject 的 bridge 镜像生成基类（全量镜像兜底面）。
 * <p>
 * 手写类 {@link EXTFramebufferObject} extends 本类：invokestatic 的方法解析先命中手写类
 * 自身声明（顶点流/状态仿真/id stash/map 仿真等精心语义），未覆盖的
 * 落到本基类的通用录制/阻塞语义——手写永远优先，生成物只兜底。
 */
public class EXTFramebufferObjectGen {
    protected EXTFramebufferObjectGen() {
    }

    // 命令型
    public static void glBindFramebufferEXT(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTFramebufferObject.glBindFramebufferEXT(p0, p1));
    }

    // 命令型
    public static void glBindRenderbufferEXT(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTFramebufferObject.glBindRenderbufferEXT(p0, p1));
    }

    // 阻塞取值型
    public static int glCheckFramebufferStatusEXT(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.EXTFramebufferObject.glCheckFramebufferStatusEXT(p0));
    }

    // 命令型
    public static void glDeleteFramebuffersEXT(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTFramebufferObject.glDeleteFramebuffersEXT(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDeleteFramebuffersEXT(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.EXTFramebufferObject.glDeleteFramebuffersEXT(snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glDeleteRenderbuffersEXT(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTFramebufferObject.glDeleteRenderbuffersEXT(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDeleteRenderbuffersEXT(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.EXTFramebufferObject.glDeleteRenderbuffersEXT(snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glFramebufferRenderbufferEXT(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTFramebufferObject.glFramebufferRenderbufferEXT(p0, p1, p2, p3));
    }

    // 命令型
    public static void glFramebufferTexture1DEXT(int p0, int p1, int p2, int p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTFramebufferObject.glFramebufferTexture1DEXT(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glFramebufferTexture2DEXT(int p0, int p1, int p2, int p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTFramebufferObject.glFramebufferTexture2DEXT(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glFramebufferTexture3DEXT(int p0, int p1, int p2, int p3, int p4, int p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTFramebufferObject.glFramebufferTexture3DEXT(p0, p1, p2, p3, p4, p5));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glGenFramebuffersEXT() {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.EXTFramebufferObject.glGenFramebuffersEXT());
    }

    // 阻塞资源型（glGen 族，不计 StallDetector）
    public static void glGenFramebuffersEXT(java.nio.IntBuffer p0) {
        BridgeSupport.blockingWaitResource(() -> org.lwjgl.opengl.EXTFramebufferObject.glGenFramebuffersEXT(p0));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glGenRenderbuffersEXT() {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.EXTFramebufferObject.glGenRenderbuffersEXT());
    }

    // 阻塞资源型（glGen 族，不计 StallDetector）
    public static void glGenRenderbuffersEXT(java.nio.IntBuffer p0) {
        BridgeSupport.blockingWaitResource(() -> org.lwjgl.opengl.EXTFramebufferObject.glGenRenderbuffersEXT(p0));
    }

    // 命令型
    public static void glGenerateMipmapEXT(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTFramebufferObject.glGenerateMipmapEXT(p0));
    }

    // 阻塞取值型
    public static int glGetFramebufferAttachmentParameterEXT(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.EXTFramebufferObject.glGetFramebufferAttachmentParameterEXT(p0, p1, p2));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetFramebufferAttachmentParameterEXT(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p3, 16, buf -> org.lwjgl.opengl.EXTFramebufferObject.glGetFramebufferAttachmentParameterEXT(p0, p1, p2, buf)));
    }

    // 阻塞取值型
    public static int glGetFramebufferAttachmentParameteriEXT(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.EXTFramebufferObject.glGetFramebufferAttachmentParameteriEXT(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetRenderbufferParameterEXT(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.EXTFramebufferObject.glGetRenderbufferParameterEXT(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetRenderbufferParameterEXT(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.EXTFramebufferObject.glGetRenderbufferParameterEXT(p0, p1, buf)));
    }

    // 阻塞取值型
    public static int glGetRenderbufferParameteriEXT(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.EXTFramebufferObject.glGetRenderbufferParameteriEXT(p0, p1));
    }

    // 阻塞取值型
    public static boolean glIsFramebufferEXT(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.EXTFramebufferObject.glIsFramebufferEXT(p0));
    }

    // 阻塞取值型
    public static boolean glIsRenderbufferEXT(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.EXTFramebufferObject.glIsRenderbufferEXT(p0));
    }

    // 命令型
    public static void glRenderbufferStorageEXT(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTFramebufferObject.glRenderbufferStorageEXT(p0, p1, p2, p3));
    }
}
