// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.EXTFogCoord 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class EXTFogCoord {
    private EXTFogCoord() {
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glFogCoordPointerEXT(int p0, java.nio.DoubleBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.EXTFogCoord.glFogCoordPointerEXT(p0, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glFogCoordPointerEXT(int p0, java.nio.FloatBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.EXTFogCoord.glFogCoordPointerEXT(p0, snapshot.asFloatBuffer()));
    }

    // 命令型
    public static void glFogCoordPointerEXT(int p0, int p1, long p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTFogCoord.glFogCoordPointerEXT(p0, p1, p2));
    }

    // 命令型
    public static void glFogCoorddEXT(double p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTFogCoord.glFogCoorddEXT(p0));
    }

    // 命令型
    public static void glFogCoordfEXT(float p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTFogCoord.glFogCoordfEXT(p0));
    }
}
