// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.EXTGpuShader4 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class EXTGpuShader4 {
    private EXTGpuShader4() {
    }

    // 命令型（字符串捕获，不可变）
    public static void glBindFragDataLocationEXT(int p0, int p1, java.lang.CharSequence p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTGpuShader4.glBindFragDataLocationEXT(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBindFragDataLocationEXT(int p0, int p1, java.nio.ByteBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.EXTGpuShader4.glBindFragDataLocationEXT(p0, p1, snapshot));
    }

    // 阻塞取值型
    public static int glGetFragDataLocationEXT(int p0, java.lang.CharSequence p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.EXTGpuShader4.glGetFragDataLocationEXT(p0, p1));
    }

    // 阻塞取值型
    public static int glGetFragDataLocationEXT(int p0, java.nio.ByteBuffer p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.EXTGpuShader4.glGetFragDataLocationEXT(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetUniformuEXT(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.EXTGpuShader4.glGetUniformuEXT(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetVertexAttribIEXT(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.EXTGpuShader4.glGetVertexAttribIEXT(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetVertexAttribIuEXT(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.EXTGpuShader4.glGetVertexAttribIuEXT(p0, p1, buf)));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniform1uEXT(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.EXTGpuShader4.glUniform1uEXT(p0, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glUniform1uiEXT(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTGpuShader4.glUniform1uiEXT(p0, p1));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniform2uEXT(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.EXTGpuShader4.glUniform2uEXT(p0, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glUniform2uiEXT(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTGpuShader4.glUniform2uiEXT(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniform3uEXT(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.EXTGpuShader4.glUniform3uEXT(p0, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glUniform3uiEXT(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTGpuShader4.glUniform3uiEXT(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniform4uEXT(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.EXTGpuShader4.glUniform4uEXT(p0, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glUniform4uiEXT(int p0, int p1, int p2, int p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTGpuShader4.glUniform4uiEXT(p0, p1, p2, p3, p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribI1EXT(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.EXTGpuShader4.glVertexAttribI1EXT(p0, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glVertexAttribI1iEXT(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTGpuShader4.glVertexAttribI1iEXT(p0, p1));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribI1uEXT(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.EXTGpuShader4.glVertexAttribI1uEXT(p0, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glVertexAttribI1uiEXT(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTGpuShader4.glVertexAttribI1uiEXT(p0, p1));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribI2EXT(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.EXTGpuShader4.glVertexAttribI2EXT(p0, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glVertexAttribI2iEXT(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTGpuShader4.glVertexAttribI2iEXT(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribI2uEXT(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.EXTGpuShader4.glVertexAttribI2uEXT(p0, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glVertexAttribI2uiEXT(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTGpuShader4.glVertexAttribI2uiEXT(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribI3EXT(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.EXTGpuShader4.glVertexAttribI3EXT(p0, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glVertexAttribI3iEXT(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTGpuShader4.glVertexAttribI3iEXT(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribI3uEXT(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.EXTGpuShader4.glVertexAttribI3uEXT(p0, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glVertexAttribI3uiEXT(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTGpuShader4.glVertexAttribI3uiEXT(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribI4EXT(int p0, java.nio.ByteBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.EXTGpuShader4.glVertexAttribI4EXT(p0, snapshot));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribI4EXT(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.EXTGpuShader4.glVertexAttribI4EXT(p0, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribI4EXT(int p0, java.nio.ShortBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.EXTGpuShader4.glVertexAttribI4EXT(p0, snapshot.asShortBuffer()));
    }

    // 命令型
    public static void glVertexAttribI4iEXT(int p0, int p1, int p2, int p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTGpuShader4.glVertexAttribI4iEXT(p0, p1, p2, p3, p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribI4uEXT(int p0, java.nio.ByteBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.EXTGpuShader4.glVertexAttribI4uEXT(p0, snapshot));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribI4uEXT(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.EXTGpuShader4.glVertexAttribI4uEXT(p0, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribI4uEXT(int p0, java.nio.ShortBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.EXTGpuShader4.glVertexAttribI4uEXT(p0, snapshot.asShortBuffer()));
    }

    // 命令型
    public static void glVertexAttribI4uiEXT(int p0, int p1, int p2, int p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTGpuShader4.glVertexAttribI4uiEXT(p0, p1, p2, p3, p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribIPointerEXT(int p0, int p1, int p2, int p3, java.nio.ByteBuffer p4) {
        BridgeSupport.enqueueSnapshot(p4, snapshot -> org.lwjgl.opengl.EXTGpuShader4.glVertexAttribIPointerEXT(p0, p1, p2, p3, snapshot));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribIPointerEXT(int p0, int p1, int p2, int p3, java.nio.IntBuffer p4) {
        BridgeSupport.enqueueSnapshot(p4, snapshot -> org.lwjgl.opengl.EXTGpuShader4.glVertexAttribIPointerEXT(p0, p1, p2, p3, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribIPointerEXT(int p0, int p1, int p2, int p3, java.nio.ShortBuffer p4) {
        BridgeSupport.enqueueSnapshot(p4, snapshot -> org.lwjgl.opengl.EXTGpuShader4.glVertexAttribIPointerEXT(p0, p1, p2, p3, snapshot.asShortBuffer()));
    }

    // 命令型
    public static void glVertexAttribIPointerEXT(int p0, int p1, int p2, int p3, long p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTGpuShader4.glVertexAttribIPointerEXT(p0, p1, p2, p3, p4));
    }
}
