// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.EXTGpuProgramParameters 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class EXTGpuProgramParameters {
    private EXTGpuProgramParameters() {
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramEnvParameters4EXT(int p0, int p1, int p2, java.nio.FloatBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.EXTGpuProgramParameters.glProgramEnvParameters4EXT(p0, p1, p2, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramLocalParameters4EXT(int p0, int p1, int p2, java.nio.FloatBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.EXTGpuProgramParameters.glProgramLocalParameters4EXT(p0, p1, p2, snapshot.asFloatBuffer()));
    }
}
