// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.EXTPointParameters 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class EXTPointParameters {
    private EXTPointParameters() {
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glPointParameterEXT(int p0, java.nio.FloatBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.EXTPointParameters.glPointParameterEXT(p0, snapshot.asFloatBuffer()));
    }

    // 命令型
    public static void glPointParameterfEXT(int p0, float p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTPointParameters.glPointParameterfEXT(p0, p1));
    }
}
