// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.EXTShaderImageLoadStore 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class EXTShaderImageLoadStore {
    private EXTShaderImageLoadStore() {
    }

    // 命令型
    public static void glBindImageTextureEXT(int p0, int p1, int p2, boolean p3, int p4, int p5, int p6) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTShaderImageLoadStore.glBindImageTextureEXT(p0, p1, p2, p3, p4, p5, p6));
    }

    // 命令型
    public static void glMemoryBarrierEXT(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTShaderImageLoadStore.glMemoryBarrierEXT(p0));
    }
}
