// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.EXTSeparateShaderObjects 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class EXTSeparateShaderObjects {
    private EXTSeparateShaderObjects() {
    }

    // 命令型
    public static void glActiveProgramEXT(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTSeparateShaderObjects.glActiveProgramEXT(p0));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glCreateShaderProgramEXT(int p0, java.lang.CharSequence p1) {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.EXTSeparateShaderObjects.glCreateShaderProgramEXT(p0, p1));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glCreateShaderProgramEXT(int p0, java.nio.ByteBuffer p1) {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.EXTSeparateShaderObjects.glCreateShaderProgramEXT(p0, p1));
    }

    // 命令型
    public static void glUseShaderProgramEXT(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTSeparateShaderObjects.glUseShaderProgramEXT(p0, p1));
    }
}
