// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.EXTSecondaryColor 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class EXTSecondaryColor {
    private EXTSecondaryColor() {
    }

    // 命令型
    public static void glSecondaryColor3bEXT(byte p0, byte p1, byte p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTSecondaryColor.glSecondaryColor3bEXT(p0, p1, p2));
    }

    // 命令型
    public static void glSecondaryColor3dEXT(double p0, double p1, double p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTSecondaryColor.glSecondaryColor3dEXT(p0, p1, p2));
    }

    // 命令型
    public static void glSecondaryColor3fEXT(float p0, float p1, float p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTSecondaryColor.glSecondaryColor3fEXT(p0, p1, p2));
    }

    // 命令型
    public static void glSecondaryColor3ubEXT(byte p0, byte p1, byte p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTSecondaryColor.glSecondaryColor3ubEXT(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glSecondaryColorPointerEXT(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.EXTSecondaryColor.glSecondaryColorPointerEXT(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glSecondaryColorPointerEXT(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.EXTSecondaryColor.glSecondaryColorPointerEXT(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glSecondaryColorPointerEXT(int p0, boolean p1, int p2, java.nio.ByteBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.EXTSecondaryColor.glSecondaryColorPointerEXT(p0, p1, p2, snapshot));
    }

    // 命令型
    public static void glSecondaryColorPointerEXT(int p0, int p1, int p2, long p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTSecondaryColor.glSecondaryColorPointerEXT(p0, p1, p2, p3));
    }
}
