// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.EXTTextureInteger 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class EXTTextureInteger {
    private EXTTextureInteger() {
    }

    // 命令型
    public static void glClearColorIiEXT(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTTextureInteger.glClearColorIiEXT(p0, p1, p2, p3));
    }

    // 命令型
    public static void glClearColorIuiEXT(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTTextureInteger.glClearColorIuiEXT(p0, p1, p2, p3));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTexParameterIEXT(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.EXTTextureInteger.glGetTexParameterIEXT(p0, p1, buf)));
    }

    // 阻塞取值型
    public static int glGetTexParameterIiEXT(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.EXTTextureInteger.glGetTexParameterIiEXT(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTexParameterIuEXT(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.EXTTextureInteger.glGetTexParameterIuEXT(p0, p1, buf)));
    }

    // 阻塞取值型
    public static int glGetTexParameterIuiEXT(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.EXTTextureInteger.glGetTexParameterIuiEXT(p0, p1));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexParameterIEXT(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.EXTTextureInteger.glTexParameterIEXT(p0, p1, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glTexParameterIiEXT(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTTextureInteger.glTexParameterIiEXT(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexParameterIuEXT(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.EXTTextureInteger.glTexParameterIuEXT(p0, p1, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glTexParameterIuiEXT(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.EXTTextureInteger.glTexParameterIuiEXT(p0, p1, p2));
    }
}
