// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.GL11 的 bridge 镜像生成基类（全量镜像兜底面）。
 * <p>
 * 手写类 {@link GL11} extends 本类：invokestatic 的方法解析先命中手写类
 * 自身声明（顶点流/状态仿真/id stash/map 仿真等精心语义），未覆盖的
 * 落到本基类的通用录制/阻塞语义——手写永远优先，生成物只兜底。
 */
public class GL11Gen {
    protected GL11Gen() {
    }

    // 命令型
    public static void glAccum(int p0, float p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glAccum(p0, p1));
    }

    // 命令型
    public static void glAlphaFunc(int p0, float p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glAlphaFunc(p0, p1));
    }

    // 阻塞取值型
    public static boolean glAreTexturesResident(java.nio.IntBuffer p0, java.nio.ByteBuffer p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL11.glAreTexturesResident(p0, p1));
    }

    // 命令型
    public static void glArrayElement(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glArrayElement(p0));
    }

    // 命令型
    public static void glBegin(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glBegin(p0));
    }

    // 命令型
    public static void glBindTexture(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glBindTexture(p0, p1));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBitmap(int p0, int p1, float p2, float p3, float p4, float p5, java.nio.ByteBuffer p6) {
        BridgeSupport.enqueueSnapshot(p6, snapshot -> org.lwjgl.opengl.GL11.glBitmap(p0, p1, p2, p3, p4, p5, snapshot));
    }

    // 命令型
    public static void glBitmap(int p0, int p1, float p2, float p3, float p4, float p5, long p6) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glBitmap(p0, p1, p2, p3, p4, p5, p6));
    }

    // 命令型
    public static void glBlendFunc(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glBlendFunc(p0, p1));
    }

    // 命令型
    public static void glCallList(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glCallList(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCallLists(java.nio.ByteBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.GL11.glCallLists(snapshot));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCallLists(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.GL11.glCallLists(snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCallLists(java.nio.ShortBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.GL11.glCallLists(snapshot.asShortBuffer()));
    }

    // 命令型
    public static void glClear(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glClear(p0));
    }

    // 命令型
    public static void glClearAccum(float p0, float p1, float p2, float p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glClearAccum(p0, p1, p2, p3));
    }

    // 命令型
    public static void glClearColor(float p0, float p1, float p2, float p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glClearColor(p0, p1, p2, p3));
    }

    // 命令型
    public static void glClearDepth(double p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glClearDepth(p0));
    }

    // 命令型
    public static void glClearStencil(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glClearStencil(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glClipPlane(int p0, java.nio.DoubleBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL11.glClipPlane(p0, snapshot.asDoubleBuffer()));
    }

    // 命令型
    public static void glColor3b(byte p0, byte p1, byte p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glColor3b(p0, p1, p2));
    }

    // 命令型
    public static void glColor3d(double p0, double p1, double p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glColor3d(p0, p1, p2));
    }

    // 命令型
    public static void glColor3f(float p0, float p1, float p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glColor3f(p0, p1, p2));
    }

    // 命令型
    public static void glColor3ub(byte p0, byte p1, byte p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glColor3ub(p0, p1, p2));
    }

    // 命令型
    public static void glColor4b(byte p0, byte p1, byte p2, byte p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glColor4b(p0, p1, p2, p3));
    }

    // 命令型
    public static void glColor4d(double p0, double p1, double p2, double p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glColor4d(p0, p1, p2, p3));
    }

    // 命令型
    public static void glColor4f(float p0, float p1, float p2, float p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glColor4f(p0, p1, p2, p3));
    }

    // 命令型
    public static void glColor4ub(byte p0, byte p1, byte p2, byte p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glColor4ub(p0, p1, p2, p3));
    }

    // 命令型
    public static void glColorMask(boolean p0, boolean p1, boolean p2, boolean p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glColorMask(p0, p1, p2, p3));
    }

    // 命令型
    public static void glColorMaterial(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glColorMaterial(p0, p1));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glColorPointer(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glColorPointer(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glColorPointer(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glColorPointer(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glColorPointer(int p0, boolean p1, int p2, java.nio.ByteBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL11.glColorPointer(p0, p1, p2, snapshot));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glColorPointer(int p0, int p1, int p2, java.nio.ByteBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL11.glColorPointer(p0, p1, p2, snapshot));
    }

    // 命令型
    public static void glColorPointer(int p0, int p1, int p2, long p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glColorPointer(p0, p1, p2, p3));
    }

    // 命令型
    public static void glCopyPixels(int p0, int p1, int p2, int p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glCopyPixels(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glCopyTexImage1D(int p0, int p1, int p2, int p3, int p4, int p5, int p6) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glCopyTexImage1D(p0, p1, p2, p3, p4, p5, p6));
    }

    // 命令型
    public static void glCopyTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glCopyTexImage2D(p0, p1, p2, p3, p4, p5, p6, p7));
    }

    // 命令型
    public static void glCopyTexSubImage1D(int p0, int p1, int p2, int p3, int p4, int p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glCopyTexSubImage1D(p0, p1, p2, p3, p4, p5));
    }

    // 命令型
    public static void glCopyTexSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glCopyTexSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7));
    }

    // 命令型
    public static void glCullFace(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glCullFace(p0));
    }

    // 命令型
    public static void glDeleteLists(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glDeleteLists(p0, p1));
    }

    // 命令型
    public static void glDeleteTextures(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glDeleteTextures(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDeleteTextures(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.GL11.glDeleteTextures(snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glDepthFunc(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glDepthFunc(p0));
    }

    // 命令型
    public static void glDepthMask(boolean p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glDepthMask(p0));
    }

    // 命令型
    public static void glDepthRange(double p0, double p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glDepthRange(p0, p1));
    }

    // 命令型
    public static void glDisable(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glDisable(p0));
    }

    // 命令型
    public static void glDisableClientState(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glDisableClientState(p0));
    }

    // 命令型
    public static void glDrawArrays(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glDrawArrays(p0, p1, p2));
    }

    // 命令型
    public static void glDrawBuffer(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glDrawBuffer(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElements(int p0, java.nio.ByteBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL11.glDrawElements(p0, snapshot));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElements(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL11.glDrawElements(p0, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElements(int p0, java.nio.ShortBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL11.glDrawElements(p0, snapshot.asShortBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElements(int p0, int p1, int p2, java.nio.ByteBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL11.glDrawElements(p0, p1, p2, snapshot));
    }

    // 命令型
    public static void glDrawElements(int p0, int p1, int p2, long p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glDrawElements(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawPixels(int p0, int p1, int p2, int p3, java.nio.ByteBuffer p4) {
        BridgeSupport.enqueueSnapshot(p4, snapshot -> org.lwjgl.opengl.GL11.glDrawPixels(p0, p1, p2, p3, snapshot));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawPixels(int p0, int p1, int p2, int p3, java.nio.IntBuffer p4) {
        BridgeSupport.enqueueSnapshot(p4, snapshot -> org.lwjgl.opengl.GL11.glDrawPixels(p0, p1, p2, p3, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawPixels(int p0, int p1, int p2, int p3, java.nio.ShortBuffer p4) {
        BridgeSupport.enqueueSnapshot(p4, snapshot -> org.lwjgl.opengl.GL11.glDrawPixels(p0, p1, p2, p3, snapshot.asShortBuffer()));
    }

    // 命令型
    public static void glDrawPixels(int p0, int p1, int p2, int p3, long p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glDrawPixels(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glEdgeFlag(boolean p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glEdgeFlag(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glEdgeFlagPointer(int p0, java.nio.ByteBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL11.glEdgeFlagPointer(p0, snapshot));
    }

    // 命令型
    public static void glEdgeFlagPointer(int p0, long p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glEdgeFlagPointer(p0, p1));
    }

    // 命令型
    public static void glEnable(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glEnable(p0));
    }

    // 命令型
    public static void glEnableClientState(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glEnableClientState(p0));
    }

    // 命令型
    public static void glEnd() {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glEnd());
    }

    // 命令型
    public static void glEndList() {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glEndList());
    }

    // 命令型
    public static void glEvalCoord1d(double p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glEvalCoord1d(p0));
    }

    // 命令型
    public static void glEvalCoord1f(float p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glEvalCoord1f(p0));
    }

    // 命令型
    public static void glEvalCoord2d(double p0, double p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glEvalCoord2d(p0, p1));
    }

    // 命令型
    public static void glEvalCoord2f(float p0, float p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glEvalCoord2f(p0, p1));
    }

    // 命令型
    public static void glEvalMesh1(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glEvalMesh1(p0, p1, p2));
    }

    // 命令型
    public static void glEvalMesh2(int p0, int p1, int p2, int p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glEvalMesh2(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glEvalPoint1(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glEvalPoint1(p0));
    }

    // 命令型
    public static void glEvalPoint2(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glEvalPoint2(p0, p1));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glFeedbackBuffer(int p0, java.nio.FloatBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL11.glFeedbackBuffer(p0, snapshot.asFloatBuffer()));
    }

    // 命令型
    public static void glFinish() {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glFinish());
    }

    // 命令型
    public static void glFlush() {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glFlush());
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glFog(int p0, java.nio.FloatBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL11.glFog(p0, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glFog(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL11.glFog(p0, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glFogf(int p0, float p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glFogf(p0, p1));
    }

    // 命令型
    public static void glFogi(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glFogi(p0, p1));
    }

    // 命令型
    public static void glFrontFace(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glFrontFace(p0));
    }

    // 命令型
    public static void glFrustum(double p0, double p1, double p2, double p3, double p4, double p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glFrustum(p0, p1, p2, p3, p4, p5));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glGenLists(int p0) {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.GL11.glGenLists(p0));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glGenTextures() {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.GL11.glGenTextures());
    }

    // 阻塞资源型（glGen 族，不计 StallDetector）
    public static void glGenTextures(java.nio.IntBuffer p0) {
        BridgeSupport.blockingWaitResource(() -> org.lwjgl.opengl.GL11.glGenTextures(p0));
    }

    // 阻塞取值型
    public static boolean glGetBoolean(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL11.glGetBoolean(p0));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetBoolean(int p0, java.nio.ByteBuffer p1) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillBooleans(p1, 16, buf -> org.lwjgl.opengl.GL11.glGetBoolean(p0, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetClipPlane(int p0, java.nio.DoubleBuffer p1) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillDoubles(p1, 16, buf -> org.lwjgl.opengl.GL11.glGetClipPlane(p0, buf)));
    }

    // 阻塞取值型
    public static double glGetDouble(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL11.glGetDouble(p0));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetDouble(int p0, java.nio.DoubleBuffer p1) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillDoubles(p1, 16, buf -> org.lwjgl.opengl.GL11.glGetDouble(p0, buf)));
    }

    // 阻塞取值型
    public static int glGetError() {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL11.glGetError());
    }

    // 阻塞取值型
    public static float glGetFloat(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL11.glGetFloat(p0));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetFloat(int p0, java.nio.FloatBuffer p1) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p1, 16, buf -> org.lwjgl.opengl.GL11.glGetFloat(p0, buf)));
    }

    // 阻塞取值型
    public static int glGetInteger(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL11.glGetInteger(p0));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetInteger(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p1, 16, buf -> org.lwjgl.opengl.GL11.glGetInteger(p0, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetLight(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p2, 16, buf -> org.lwjgl.opengl.GL11.glGetLight(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetLight(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.GL11.glGetLight(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetMap(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillDoubles(p2, 16, buf -> org.lwjgl.opengl.GL11.glGetMap(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetMap(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p2, 16, buf -> org.lwjgl.opengl.GL11.glGetMap(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetMap(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.GL11.glGetMap(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetMaterial(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p2, 16, buf -> org.lwjgl.opengl.GL11.glGetMaterial(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetMaterial(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.GL11.glGetMaterial(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetPixelMap(int p0, java.nio.FloatBuffer p1) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p1, 16, buf -> org.lwjgl.opengl.GL11.glGetPixelMap(p0, buf)));
    }

    // 命令型
    public static void glGetPixelMapfv(int p0, long p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glGetPixelMapfv(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetPixelMapu(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p1, 16, buf -> org.lwjgl.opengl.GL11.glGetPixelMapu(p0, buf)));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetPixelMapu(int p0, java.nio.ShortBuffer p1) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.GL11.glGetPixelMapu(p0, p1));
    }

    // 命令型
    public static void glGetPixelMapuiv(int p0, long p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glGetPixelMapuiv(p0, p1));
    }

    // 命令型
    public static void glGetPixelMapusv(int p0, long p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glGetPixelMapusv(p0, p1));
    }

    // 阻塞取值型
    public static java.nio.ByteBuffer glGetPointer(int p0, long p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL11.glGetPointer(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetPolygonStipple(java.nio.ByteBuffer p0) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillBooleans(p0, 16, buf -> org.lwjgl.opengl.GL11.glGetPolygonStipple(buf)));
    }

    // 命令型
    public static void glGetPolygonStipple(long p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glGetPolygonStipple(p0));
    }

    // 阻塞取值型
    public static java.lang.String glGetString(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL11.glGetString(p0));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTexEnv(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p2, 16, buf -> org.lwjgl.opengl.GL11.glGetTexEnv(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTexEnv(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.GL11.glGetTexEnv(p0, p1, buf)));
    }

    // 阻塞取值型
    public static float glGetTexEnvf(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL11.glGetTexEnvf(p0, p1));
    }

    // 阻塞取值型
    public static int glGetTexEnvi(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL11.glGetTexEnvi(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTexGen(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillDoubles(p2, 16, buf -> org.lwjgl.opengl.GL11.glGetTexGen(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTexGen(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p2, 16, buf -> org.lwjgl.opengl.GL11.glGetTexGen(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTexGen(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.GL11.glGetTexGen(p0, p1, buf)));
    }

    // 阻塞取值型
    public static double glGetTexGend(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL11.glGetTexGend(p0, p1));
    }

    // 阻塞取值型
    public static float glGetTexGenf(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL11.glGetTexGenf(p0, p1));
    }

    // 阻塞取值型
    public static int glGetTexGeni(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL11.glGetTexGeni(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTexImage(int p0, int p1, int p2, int p3, java.nio.ByteBuffer p4) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillBooleans(p4, 16, buf -> org.lwjgl.opengl.GL11.glGetTexImage(p0, p1, p2, p3, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTexImage(int p0, int p1, int p2, int p3, java.nio.DoubleBuffer p4) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillDoubles(p4, 16, buf -> org.lwjgl.opengl.GL11.glGetTexImage(p0, p1, p2, p3, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTexImage(int p0, int p1, int p2, int p3, java.nio.FloatBuffer p4) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p4, 16, buf -> org.lwjgl.opengl.GL11.glGetTexImage(p0, p1, p2, p3, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTexImage(int p0, int p1, int p2, int p3, java.nio.IntBuffer p4) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p4, 16, buf -> org.lwjgl.opengl.GL11.glGetTexImage(p0, p1, p2, p3, buf)));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetTexImage(int p0, int p1, int p2, int p3, java.nio.ShortBuffer p4) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.GL11.glGetTexImage(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glGetTexImage(int p0, int p1, int p2, int p3, long p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glGetTexImage(p0, p1, p2, p3, p4));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTexLevelParameter(int p0, int p1, int p2, java.nio.FloatBuffer p3) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p3, 16, buf -> org.lwjgl.opengl.GL11.glGetTexLevelParameter(p0, p1, p2, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTexLevelParameter(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p3, 16, buf -> org.lwjgl.opengl.GL11.glGetTexLevelParameter(p0, p1, p2, buf)));
    }

    // 阻塞取值型
    public static float glGetTexLevelParameterf(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL11.glGetTexLevelParameterf(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetTexLevelParameteri(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL11.glGetTexLevelParameteri(p0, p1, p2));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTexParameter(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p2, 16, buf -> org.lwjgl.opengl.GL11.glGetTexParameter(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTexParameter(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.GL11.glGetTexParameter(p0, p1, buf)));
    }

    // 阻塞取值型
    public static float glGetTexParameterf(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL11.glGetTexParameterf(p0, p1));
    }

    // 阻塞取值型
    public static int glGetTexParameteri(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL11.glGetTexParameteri(p0, p1));
    }

    // 命令型
    public static void glHint(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glHint(p0, p1));
    }

    // 命令型
    public static void glInitNames() {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glInitNames());
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glInterleavedArrays(int p0, int p1, java.nio.ByteBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glInterleavedArrays(p0, p1, snapshot));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glInterleavedArrays(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glInterleavedArrays(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glInterleavedArrays(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glInterleavedArrays(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glInterleavedArrays(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glInterleavedArrays(p0, p1, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glInterleavedArrays(int p0, int p1, java.nio.ShortBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glInterleavedArrays(p0, p1, snapshot.asShortBuffer()));
    }

    // 命令型
    public static void glInterleavedArrays(int p0, int p1, long p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glInterleavedArrays(p0, p1, p2));
    }

    // 阻塞取值型
    public static boolean glIsEnabled(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL11.glIsEnabled(p0));
    }

    // 阻塞取值型
    public static boolean glIsList(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL11.glIsList(p0));
    }

    // 阻塞取值型
    public static boolean glIsTexture(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL11.glIsTexture(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glLight(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glLight(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glLight(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glLight(p0, p1, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glLightModel(int p0, java.nio.FloatBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL11.glLightModel(p0, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glLightModel(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL11.glLightModel(p0, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glLightModelf(int p0, float p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glLightModelf(p0, p1));
    }

    // 命令型
    public static void glLightModeli(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glLightModeli(p0, p1));
    }

    // 命令型
    public static void glLightf(int p0, int p1, float p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glLightf(p0, p1, p2));
    }

    // 命令型
    public static void glLighti(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glLighti(p0, p1, p2));
    }

    // 命令型
    public static void glLineStipple(int p0, short p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glLineStipple(p0, p1));
    }

    // 命令型
    public static void glLineWidth(float p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glLineWidth(p0));
    }

    // 命令型
    public static void glListBase(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glListBase(p0));
    }

    // 命令型
    public static void glLoadIdentity() {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glLoadIdentity());
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glLoadMatrix(java.nio.DoubleBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.GL11.glLoadMatrix(snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glLoadMatrix(java.nio.FloatBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.GL11.glLoadMatrix(snapshot.asFloatBuffer()));
    }

    // 命令型
    public static void glLoadName(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glLoadName(p0));
    }

    // 命令型
    public static void glLogicOp(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glLogicOp(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glMap1d(int p0, double p1, double p2, int p3, int p4, java.nio.DoubleBuffer p5) {
        BridgeSupport.enqueueSnapshot(p5, snapshot -> org.lwjgl.opengl.GL11.glMap1d(p0, p1, p2, p3, p4, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glMap1f(int p0, float p1, float p2, int p3, int p4, java.nio.FloatBuffer p5) {
        BridgeSupport.enqueueSnapshot(p5, snapshot -> org.lwjgl.opengl.GL11.glMap1f(p0, p1, p2, p3, p4, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glMap2d(int p0, double p1, double p2, int p3, int p4, double p5, double p6, int p7, int p8, java.nio.DoubleBuffer p9) {
        BridgeSupport.enqueueSnapshot(p9, snapshot -> org.lwjgl.opengl.GL11.glMap2d(p0, p1, p2, p3, p4, p5, p6, p7, p8, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glMap2f(int p0, float p1, float p2, int p3, int p4, float p5, float p6, int p7, int p8, java.nio.FloatBuffer p9) {
        BridgeSupport.enqueueSnapshot(p9, snapshot -> org.lwjgl.opengl.GL11.glMap2f(p0, p1, p2, p3, p4, p5, p6, p7, p8, snapshot.asFloatBuffer()));
    }

    // 命令型
    public static void glMapGrid1d(int p0, double p1, double p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glMapGrid1d(p0, p1, p2));
    }

    // 命令型
    public static void glMapGrid1f(int p0, float p1, float p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glMapGrid1f(p0, p1, p2));
    }

    // 命令型
    public static void glMapGrid2d(int p0, double p1, double p2, int p3, double p4, double p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glMapGrid2d(p0, p1, p2, p3, p4, p5));
    }

    // 命令型
    public static void glMapGrid2f(int p0, float p1, float p2, int p3, float p4, float p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glMapGrid2f(p0, p1, p2, p3, p4, p5));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glMaterial(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glMaterial(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glMaterial(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glMaterial(p0, p1, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glMaterialf(int p0, int p1, float p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glMaterialf(p0, p1, p2));
    }

    // 命令型
    public static void glMateriali(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glMateriali(p0, p1, p2));
    }

    // 命令型
    public static void glMatrixMode(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glMatrixMode(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glMultMatrix(java.nio.DoubleBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.GL11.glMultMatrix(snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glMultMatrix(java.nio.FloatBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.GL11.glMultMatrix(snapshot.asFloatBuffer()));
    }

    // 命令型
    public static void glNewList(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glNewList(p0, p1));
    }

    // 命令型
    public static void glNormal3b(byte p0, byte p1, byte p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glNormal3b(p0, p1, p2));
    }

    // 命令型
    public static void glNormal3d(double p0, double p1, double p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glNormal3d(p0, p1, p2));
    }

    // 命令型
    public static void glNormal3f(float p0, float p1, float p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glNormal3f(p0, p1, p2));
    }

    // 命令型
    public static void glNormal3i(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glNormal3i(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNormalPointer(int p0, java.nio.ByteBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL11.glNormalPointer(p0, snapshot));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNormalPointer(int p0, java.nio.DoubleBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL11.glNormalPointer(p0, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNormalPointer(int p0, java.nio.FloatBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL11.glNormalPointer(p0, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNormalPointer(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL11.glNormalPointer(p0, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glNormalPointer(int p0, int p1, java.nio.ByteBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glNormalPointer(p0, p1, snapshot));
    }

    // 命令型
    public static void glNormalPointer(int p0, int p1, long p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glNormalPointer(p0, p1, p2));
    }

    // 命令型
    public static void glOrtho(double p0, double p1, double p2, double p3, double p4, double p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glOrtho(p0, p1, p2, p3, p4, p5));
    }

    // 命令型
    public static void glPassThrough(float p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glPassThrough(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glPixelMap(int p0, java.nio.FloatBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL11.glPixelMap(p0, snapshot.asFloatBuffer()));
    }

    // 命令型
    public static void glPixelMapfv(int p0, int p1, long p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glPixelMapfv(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glPixelMapu(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL11.glPixelMapu(p0, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glPixelMapu(int p0, java.nio.ShortBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL11.glPixelMapu(p0, snapshot.asShortBuffer()));
    }

    // 命令型
    public static void glPixelMapuiv(int p0, int p1, long p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glPixelMapuiv(p0, p1, p2));
    }

    // 命令型
    public static void glPixelMapusv(int p0, int p1, long p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glPixelMapusv(p0, p1, p2));
    }

    // 命令型
    public static void glPixelStoref(int p0, float p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glPixelStoref(p0, p1));
    }

    // 命令型
    public static void glPixelStorei(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glPixelStorei(p0, p1));
    }

    // 命令型
    public static void glPixelTransferf(int p0, float p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glPixelTransferf(p0, p1));
    }

    // 命令型
    public static void glPixelTransferi(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glPixelTransferi(p0, p1));
    }

    // 命令型
    public static void glPixelZoom(float p0, float p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glPixelZoom(p0, p1));
    }

    // 命令型
    public static void glPointSize(float p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glPointSize(p0));
    }

    // 命令型
    public static void glPolygonMode(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glPolygonMode(p0, p1));
    }

    // 命令型
    public static void glPolygonOffset(float p0, float p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glPolygonOffset(p0, p1));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glPolygonStipple(java.nio.ByteBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.GL11.glPolygonStipple(snapshot));
    }

    // 命令型
    public static void glPolygonStipple(long p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glPolygonStipple(p0));
    }

    // 命令型
    public static void glPopAttrib() {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glPopAttrib());
    }

    // 命令型
    public static void glPopClientAttrib() {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glPopClientAttrib());
    }

    // 命令型
    public static void glPopMatrix() {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glPopMatrix());
    }

    // 命令型
    public static void glPopName() {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glPopName());
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glPrioritizeTextures(java.nio.IntBuffer p0, java.nio.FloatBuffer p1) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.GL11.glPrioritizeTextures(p0, p1));
    }

    // 命令型
    public static void glPushAttrib(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glPushAttrib(p0));
    }

    // 命令型
    public static void glPushClientAttrib(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glPushClientAttrib(p0));
    }

    // 命令型
    public static void glPushMatrix() {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glPushMatrix());
    }

    // 命令型
    public static void glPushName(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glPushName(p0));
    }

    // 命令型
    public static void glRasterPos2d(double p0, double p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glRasterPos2d(p0, p1));
    }

    // 命令型
    public static void glRasterPos2f(float p0, float p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glRasterPos2f(p0, p1));
    }

    // 命令型
    public static void glRasterPos2i(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glRasterPos2i(p0, p1));
    }

    // 命令型
    public static void glRasterPos3d(double p0, double p1, double p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glRasterPos3d(p0, p1, p2));
    }

    // 命令型
    public static void glRasterPos3f(float p0, float p1, float p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glRasterPos3f(p0, p1, p2));
    }

    // 命令型
    public static void glRasterPos3i(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glRasterPos3i(p0, p1, p2));
    }

    // 命令型
    public static void glRasterPos4d(double p0, double p1, double p2, double p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glRasterPos4d(p0, p1, p2, p3));
    }

    // 命令型
    public static void glRasterPos4f(float p0, float p1, float p2, float p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glRasterPos4f(p0, p1, p2, p3));
    }

    // 命令型
    public static void glRasterPos4i(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glRasterPos4i(p0, p1, p2, p3));
    }

    // 命令型
    public static void glReadBuffer(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glReadBuffer(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glReadPixels(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.ByteBuffer p6) {
        BridgeSupport.enqueueSnapshot(p6, snapshot -> org.lwjgl.opengl.GL11.glReadPixels(p0, p1, p2, p3, p4, p5, snapshot));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glReadPixels(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.DoubleBuffer p6) {
        BridgeSupport.enqueueSnapshot(p6, snapshot -> org.lwjgl.opengl.GL11.glReadPixels(p0, p1, p2, p3, p4, p5, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glReadPixels(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.FloatBuffer p6) {
        BridgeSupport.enqueueSnapshot(p6, snapshot -> org.lwjgl.opengl.GL11.glReadPixels(p0, p1, p2, p3, p4, p5, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glReadPixels(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.IntBuffer p6) {
        BridgeSupport.enqueueSnapshot(p6, snapshot -> org.lwjgl.opengl.GL11.glReadPixels(p0, p1, p2, p3, p4, p5, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glReadPixels(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.ShortBuffer p6) {
        BridgeSupport.enqueueSnapshot(p6, snapshot -> org.lwjgl.opengl.GL11.glReadPixels(p0, p1, p2, p3, p4, p5, snapshot.asShortBuffer()));
    }

    // 命令型
    public static void glReadPixels(int p0, int p1, int p2, int p3, int p4, int p5, long p6) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glReadPixels(p0, p1, p2, p3, p4, p5, p6));
    }

    // 命令型
    public static void glRectd(double p0, double p1, double p2, double p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glRectd(p0, p1, p2, p3));
    }

    // 命令型
    public static void glRectf(float p0, float p1, float p2, float p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glRectf(p0, p1, p2, p3));
    }

    // 命令型
    public static void glRecti(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glRecti(p0, p1, p2, p3));
    }

    // 阻塞取值型
    public static int glRenderMode(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL11.glRenderMode(p0));
    }

    // 命令型
    public static void glRotated(double p0, double p1, double p2, double p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glRotated(p0, p1, p2, p3));
    }

    // 命令型
    public static void glRotatef(float p0, float p1, float p2, float p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glRotatef(p0, p1, p2, p3));
    }

    // 命令型
    public static void glScaled(double p0, double p1, double p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glScaled(p0, p1, p2));
    }

    // 命令型
    public static void glScalef(float p0, float p1, float p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glScalef(p0, p1, p2));
    }

    // 命令型
    public static void glScissor(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glScissor(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glSelectBuffer(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.GL11.glSelectBuffer(snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glShadeModel(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glShadeModel(p0));
    }

    // 命令型
    public static void glStencilFunc(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glStencilFunc(p0, p1, p2));
    }

    // 命令型
    public static void glStencilMask(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glStencilMask(p0));
    }

    // 命令型
    public static void glStencilOp(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glStencilOp(p0, p1, p2));
    }

    // 命令型
    public static void glTexCoord1d(double p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glTexCoord1d(p0));
    }

    // 命令型
    public static void glTexCoord1f(float p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glTexCoord1f(p0));
    }

    // 命令型
    public static void glTexCoord2d(double p0, double p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glTexCoord2d(p0, p1));
    }

    // 命令型
    public static void glTexCoord2f(float p0, float p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glTexCoord2f(p0, p1));
    }

    // 命令型
    public static void glTexCoord3d(double p0, double p1, double p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glTexCoord3d(p0, p1, p2));
    }

    // 命令型
    public static void glTexCoord3f(float p0, float p1, float p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glTexCoord3f(p0, p1, p2));
    }

    // 命令型
    public static void glTexCoord4d(double p0, double p1, double p2, double p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glTexCoord4d(p0, p1, p2, p3));
    }

    // 命令型
    public static void glTexCoord4f(float p0, float p1, float p2, float p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glTexCoord4f(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexCoordPointer(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glTexCoordPointer(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexCoordPointer(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glTexCoordPointer(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexCoordPointer(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glTexCoordPointer(p0, p1, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexCoordPointer(int p0, int p1, java.nio.ShortBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glTexCoordPointer(p0, p1, snapshot.asShortBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexCoordPointer(int p0, int p1, int p2, java.nio.ByteBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL11.glTexCoordPointer(p0, p1, p2, snapshot));
    }

    // 命令型
    public static void glTexCoordPointer(int p0, int p1, int p2, long p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glTexCoordPointer(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexEnv(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glTexEnv(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexEnv(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glTexEnv(p0, p1, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glTexEnvf(int p0, int p1, float p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glTexEnvf(p0, p1, p2));
    }

    // 命令型
    public static void glTexEnvi(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glTexEnvi(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexGen(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glTexGen(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexGen(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glTexGen(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexGen(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glTexGen(p0, p1, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glTexGend(int p0, int p1, double p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glTexGend(p0, p1, p2));
    }

    // 命令型
    public static void glTexGenf(int p0, int p1, float p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glTexGenf(p0, p1, p2));
    }

    // 命令型
    public static void glTexGeni(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glTexGeni(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexImage1D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, java.nio.ByteBuffer p7) {
        BridgeSupport.enqueueSnapshot(p7, snapshot -> org.lwjgl.opengl.GL11.glTexImage1D(p0, p1, p2, p3, p4, p5, p6, snapshot));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexImage1D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, java.nio.DoubleBuffer p7) {
        BridgeSupport.enqueueSnapshot(p7, snapshot -> org.lwjgl.opengl.GL11.glTexImage1D(p0, p1, p2, p3, p4, p5, p6, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexImage1D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, java.nio.FloatBuffer p7) {
        BridgeSupport.enqueueSnapshot(p7, snapshot -> org.lwjgl.opengl.GL11.glTexImage1D(p0, p1, p2, p3, p4, p5, p6, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexImage1D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, java.nio.IntBuffer p7) {
        BridgeSupport.enqueueSnapshot(p7, snapshot -> org.lwjgl.opengl.GL11.glTexImage1D(p0, p1, p2, p3, p4, p5, p6, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexImage1D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, java.nio.ShortBuffer p7) {
        BridgeSupport.enqueueSnapshot(p7, snapshot -> org.lwjgl.opengl.GL11.glTexImage1D(p0, p1, p2, p3, p4, p5, p6, snapshot.asShortBuffer()));
    }

    // 命令型
    public static void glTexImage1D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, long p7) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glTexImage1D(p0, p1, p2, p3, p4, p5, p6, p7));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.ByteBuffer p8) {
        BridgeSupport.enqueueSnapshot(p8, snapshot -> org.lwjgl.opengl.GL11.glTexImage2D(p0, p1, p2, p3, p4, p5, p6, p7, snapshot));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.DoubleBuffer p8) {
        BridgeSupport.enqueueSnapshot(p8, snapshot -> org.lwjgl.opengl.GL11.glTexImage2D(p0, p1, p2, p3, p4, p5, p6, p7, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.FloatBuffer p8) {
        BridgeSupport.enqueueSnapshot(p8, snapshot -> org.lwjgl.opengl.GL11.glTexImage2D(p0, p1, p2, p3, p4, p5, p6, p7, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.IntBuffer p8) {
        BridgeSupport.enqueueSnapshot(p8, snapshot -> org.lwjgl.opengl.GL11.glTexImage2D(p0, p1, p2, p3, p4, p5, p6, p7, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.ShortBuffer p8) {
        BridgeSupport.enqueueSnapshot(p8, snapshot -> org.lwjgl.opengl.GL11.glTexImage2D(p0, p1, p2, p3, p4, p5, p6, p7, snapshot.asShortBuffer()));
    }

    // 命令型
    public static void glTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, long p8) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glTexImage2D(p0, p1, p2, p3, p4, p5, p6, p7, p8));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexParameter(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glTexParameter(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexParameter(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glTexParameter(p0, p1, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glTexParameterf(int p0, int p1, float p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glTexParameterf(p0, p1, p2));
    }

    // 命令型
    public static void glTexParameteri(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glTexParameteri(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexSubImage1D(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.ByteBuffer p6) {
        BridgeSupport.enqueueSnapshot(p6, snapshot -> org.lwjgl.opengl.GL11.glTexSubImage1D(p0, p1, p2, p3, p4, p5, snapshot));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexSubImage1D(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.DoubleBuffer p6) {
        BridgeSupport.enqueueSnapshot(p6, snapshot -> org.lwjgl.opengl.GL11.glTexSubImage1D(p0, p1, p2, p3, p4, p5, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexSubImage1D(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.FloatBuffer p6) {
        BridgeSupport.enqueueSnapshot(p6, snapshot -> org.lwjgl.opengl.GL11.glTexSubImage1D(p0, p1, p2, p3, p4, p5, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexSubImage1D(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.IntBuffer p6) {
        BridgeSupport.enqueueSnapshot(p6, snapshot -> org.lwjgl.opengl.GL11.glTexSubImage1D(p0, p1, p2, p3, p4, p5, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexSubImage1D(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.ShortBuffer p6) {
        BridgeSupport.enqueueSnapshot(p6, snapshot -> org.lwjgl.opengl.GL11.glTexSubImage1D(p0, p1, p2, p3, p4, p5, snapshot.asShortBuffer()));
    }

    // 命令型
    public static void glTexSubImage1D(int p0, int p1, int p2, int p3, int p4, int p5, long p6) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glTexSubImage1D(p0, p1, p2, p3, p4, p5, p6));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.ByteBuffer p8) {
        BridgeSupport.enqueueSnapshot(p8, snapshot -> org.lwjgl.opengl.GL11.glTexSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7, snapshot));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.DoubleBuffer p8) {
        BridgeSupport.enqueueSnapshot(p8, snapshot -> org.lwjgl.opengl.GL11.glTexSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.FloatBuffer p8) {
        BridgeSupport.enqueueSnapshot(p8, snapshot -> org.lwjgl.opengl.GL11.glTexSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.IntBuffer p8) {
        BridgeSupport.enqueueSnapshot(p8, snapshot -> org.lwjgl.opengl.GL11.glTexSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTexSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.ShortBuffer p8) {
        BridgeSupport.enqueueSnapshot(p8, snapshot -> org.lwjgl.opengl.GL11.glTexSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7, snapshot.asShortBuffer()));
    }

    // 命令型
    public static void glTexSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, long p8) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glTexSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7, p8));
    }

    // 命令型
    public static void glTranslated(double p0, double p1, double p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glTranslated(p0, p1, p2));
    }

    // 命令型
    public static void glTranslatef(float p0, float p1, float p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glTranslatef(p0, p1, p2));
    }

    // 命令型
    public static void glVertex2d(double p0, double p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glVertex2d(p0, p1));
    }

    // 命令型
    public static void glVertex2f(float p0, float p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glVertex2f(p0, p1));
    }

    // 命令型
    public static void glVertex2i(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glVertex2i(p0, p1));
    }

    // 命令型
    public static void glVertex3d(double p0, double p1, double p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glVertex3d(p0, p1, p2));
    }

    // 命令型
    public static void glVertex3f(float p0, float p1, float p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glVertex3f(p0, p1, p2));
    }

    // 命令型
    public static void glVertex3i(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glVertex3i(p0, p1, p2));
    }

    // 命令型
    public static void glVertex4d(double p0, double p1, double p2, double p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glVertex4d(p0, p1, p2, p3));
    }

    // 命令型
    public static void glVertex4f(float p0, float p1, float p2, float p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glVertex4f(p0, p1, p2, p3));
    }

    // 命令型
    public static void glVertex4i(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glVertex4i(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexPointer(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glVertexPointer(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexPointer(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glVertexPointer(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexPointer(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glVertexPointer(p0, p1, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexPointer(int p0, int p1, java.nio.ShortBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL11.glVertexPointer(p0, p1, snapshot.asShortBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexPointer(int p0, int p1, int p2, java.nio.ByteBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL11.glVertexPointer(p0, p1, p2, snapshot));
    }

    // 命令型
    public static void glVertexPointer(int p0, int p1, int p2, long p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glVertexPointer(p0, p1, p2, p3));
    }

    // 命令型
    public static void glViewport(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL11.glViewport(p0, p1, p2, p3));
    }
}
