// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.GL13 的 bridge 镜像生成基类（全量镜像兜底面）。
 * <p>
 * 手写类 {@link GL13} extends 本类：invokestatic 的方法解析先命中手写类
 * 自身声明（顶点流/状态仿真/id stash/map 仿真等精心语义），未覆盖的
 * 落到本基类的通用录制/阻塞语义——手写永远优先，生成物只兜底。
 */
public class GL13Gen {
    protected GL13Gen() {
    }

    // 命令型
    public static void glActiveTexture(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL13.glActiveTexture(p0));
    }

    // 命令型
    public static void glClientActiveTexture(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL13.glClientActiveTexture(p0));
    }

    // 命令型
    public static void glCompressedTexImage1D(int p0, int p1, int p2, int p3, int p4, int p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL13.glCompressedTexImage1D(p0, p1, p2, p3, p4, p5));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCompressedTexImage1D(int p0, int p1, int p2, int p3, int p4, java.nio.ByteBuffer p5) {
        BridgeSupport.enqueueSnapshot(p5, snapshot -> org.lwjgl.opengl.GL13.glCompressedTexImage1D(p0, p1, p2, p3, p4, snapshot));
    }

    // 命令型
    public static void glCompressedTexImage1D(int p0, int p1, int p2, int p3, int p4, int p5, long p6) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL13.glCompressedTexImage1D(p0, p1, p2, p3, p4, p5, p6));
    }

    // 命令型
    public static void glCompressedTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL13.glCompressedTexImage2D(p0, p1, p2, p3, p4, p5, p6));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCompressedTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.ByteBuffer p6) {
        BridgeSupport.enqueueSnapshot(p6, snapshot -> org.lwjgl.opengl.GL13.glCompressedTexImage2D(p0, p1, p2, p3, p4, p5, snapshot));
    }

    // 命令型
    public static void glCompressedTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, long p7) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL13.glCompressedTexImage2D(p0, p1, p2, p3, p4, p5, p6, p7));
    }

    // 命令型
    public static void glCompressedTexImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL13.glCompressedTexImage3D(p0, p1, p2, p3, p4, p5, p6, p7));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCompressedTexImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, java.nio.ByteBuffer p7) {
        BridgeSupport.enqueueSnapshot(p7, snapshot -> org.lwjgl.opengl.GL13.glCompressedTexImage3D(p0, p1, p2, p3, p4, p5, p6, snapshot));
    }

    // 命令型
    public static void glCompressedTexImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, long p8) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL13.glCompressedTexImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCompressedTexSubImage1D(int p0, int p1, int p2, int p3, int p4, java.nio.ByteBuffer p5) {
        BridgeSupport.enqueueSnapshot(p5, snapshot -> org.lwjgl.opengl.GL13.glCompressedTexSubImage1D(p0, p1, p2, p3, p4, snapshot));
    }

    // 命令型
    public static void glCompressedTexSubImage1D(int p0, int p1, int p2, int p3, int p4, int p5, long p6) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL13.glCompressedTexSubImage1D(p0, p1, p2, p3, p4, p5, p6));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCompressedTexSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, java.nio.ByteBuffer p7) {
        BridgeSupport.enqueueSnapshot(p7, snapshot -> org.lwjgl.opengl.GL13.glCompressedTexSubImage2D(p0, p1, p2, p3, p4, p5, p6, snapshot));
    }

    // 命令型
    public static void glCompressedTexSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, long p8) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL13.glCompressedTexSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7, p8));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCompressedTexSubImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, java.nio.ByteBuffer p9) {
        BridgeSupport.enqueueSnapshot(p9, snapshot -> org.lwjgl.opengl.GL13.glCompressedTexSubImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8, snapshot));
    }

    // 命令型
    public static void glCompressedTexSubImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, long p10) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL13.glCompressedTexSubImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetCompressedTexImage(int p0, int p1, java.nio.ByteBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillBooleans(p2, 16, buf -> org.lwjgl.opengl.GL13.glGetCompressedTexImage(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetCompressedTexImage(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.GL13.glGetCompressedTexImage(p0, p1, buf)));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetCompressedTexImage(int p0, int p1, java.nio.ShortBuffer p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.GL13.glGetCompressedTexImage(p0, p1, p2));
    }

    // 命令型
    public static void glGetCompressedTexImage(int p0, int p1, long p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL13.glGetCompressedTexImage(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glLoadTransposeMatrix(java.nio.DoubleBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.GL13.glLoadTransposeMatrix(snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glLoadTransposeMatrix(java.nio.FloatBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.GL13.glLoadTransposeMatrix(snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glMultTransposeMatrix(java.nio.DoubleBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.GL13.glMultTransposeMatrix(snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glMultTransposeMatrix(java.nio.FloatBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.GL13.glMultTransposeMatrix(snapshot.asFloatBuffer()));
    }

    // 命令型
    public static void glMultiTexCoord1d(int p0, double p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL13.glMultiTexCoord1d(p0, p1));
    }

    // 命令型
    public static void glMultiTexCoord1f(int p0, float p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL13.glMultiTexCoord1f(p0, p1));
    }

    // 命令型
    public static void glMultiTexCoord2d(int p0, double p1, double p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL13.glMultiTexCoord2d(p0, p1, p2));
    }

    // 命令型
    public static void glMultiTexCoord2f(int p0, float p1, float p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL13.glMultiTexCoord2f(p0, p1, p2));
    }

    // 命令型
    public static void glMultiTexCoord3d(int p0, double p1, double p2, double p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL13.glMultiTexCoord3d(p0, p1, p2, p3));
    }

    // 命令型
    public static void glMultiTexCoord3f(int p0, float p1, float p2, float p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL13.glMultiTexCoord3f(p0, p1, p2, p3));
    }

    // 命令型
    public static void glMultiTexCoord4d(int p0, double p1, double p2, double p3, double p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL13.glMultiTexCoord4d(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glMultiTexCoord4f(int p0, float p1, float p2, float p3, float p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL13.glMultiTexCoord4f(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glSampleCoverage(float p0, boolean p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL13.glSampleCoverage(p0, p1));
    }
}
