// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.GL15 的 bridge 镜像生成基类（全量镜像兜底面）。
 * <p>
 * 手写类 {@link GL15} extends 本类：invokestatic 的方法解析先命中手写类
 * 自身声明（顶点流/状态仿真/id stash/map 仿真等精心语义），未覆盖的
 * 落到本基类的通用录制/阻塞语义——手写永远优先，生成物只兜底。
 */
public class GL15Gen {
    protected GL15Gen() {
    }

    // 命令型
    public static void glBeginQuery(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL15.glBeginQuery(p0, p1));
    }

    // 命令型
    public static void glBindBuffer(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL15.glBindBuffer(p0, p1));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferData(int p0, java.nio.ByteBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL15.glBufferData(p0, snapshot, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferData(int p0, java.nio.DoubleBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL15.glBufferData(p0, snapshot.asDoubleBuffer(), p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferData(int p0, java.nio.FloatBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL15.glBufferData(p0, snapshot.asFloatBuffer(), p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferData(int p0, java.nio.IntBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL15.glBufferData(p0, snapshot.asIntBuffer(), p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferData(int p0, java.nio.ShortBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL15.glBufferData(p0, snapshot.asShortBuffer(), p2));
    }

    // 命令型
    public static void glBufferData(int p0, long p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL15.glBufferData(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferSubData(int p0, long p1, java.nio.ByteBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL15.glBufferSubData(p0, p1, snapshot));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferSubData(int p0, long p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL15.glBufferSubData(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferSubData(int p0, long p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL15.glBufferSubData(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferSubData(int p0, long p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL15.glBufferSubData(p0, p1, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBufferSubData(int p0, long p1, java.nio.ShortBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL15.glBufferSubData(p0, p1, snapshot.asShortBuffer()));
    }

    // 命令型
    public static void glDeleteBuffers(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL15.glDeleteBuffers(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDeleteBuffers(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.GL15.glDeleteBuffers(snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glDeleteQueries(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL15.glDeleteQueries(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDeleteQueries(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.GL15.glDeleteQueries(snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glEndQuery(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL15.glEndQuery(p0));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glGenBuffers() {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.GL15.glGenBuffers());
    }

    // 阻塞资源型（glGen 族，不计 StallDetector）
    public static void glGenBuffers(java.nio.IntBuffer p0) {
        BridgeSupport.blockingWaitResource(() -> org.lwjgl.opengl.GL15.glGenBuffers(p0));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glGenQueries() {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.GL15.glGenQueries());
    }

    // 阻塞资源型（glGen 族，不计 StallDetector）
    public static void glGenQueries(java.nio.IntBuffer p0) {
        BridgeSupport.blockingWaitResource(() -> org.lwjgl.opengl.GL15.glGenQueries(p0));
    }

    // 阻塞取值型
    public static int glGetBufferParameter(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL15.glGetBufferParameter(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetBufferParameter(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.GL15.glGetBufferParameter(p0, p1, buf)));
    }

    // 阻塞取值型
    public static int glGetBufferParameteri(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL15.glGetBufferParameteri(p0, p1));
    }

    // 阻塞取值型
    public static java.nio.ByteBuffer glGetBufferPointer(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL15.glGetBufferPointer(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetBufferSubData(int p0, long p1, java.nio.ByteBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillBooleans(p2, 16, buf -> org.lwjgl.opengl.GL15.glGetBufferSubData(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetBufferSubData(int p0, long p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillDoubles(p2, 16, buf -> org.lwjgl.opengl.GL15.glGetBufferSubData(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetBufferSubData(int p0, long p1, java.nio.FloatBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p2, 16, buf -> org.lwjgl.opengl.GL15.glGetBufferSubData(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetBufferSubData(int p0, long p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.GL15.glGetBufferSubData(p0, p1, buf)));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetBufferSubData(int p0, long p1, java.nio.ShortBuffer p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.GL15.glGetBufferSubData(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetQuery(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL15.glGetQuery(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetQuery(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.GL15.glGetQuery(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetQueryObject(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.GL15.glGetQueryObject(p0, p1, buf)));
    }

    // 阻塞取值型
    public static int glGetQueryObjecti(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL15.glGetQueryObjecti(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetQueryObjectu(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.GL15.glGetQueryObjectu(p0, p1, buf)));
    }

    // 阻塞取值型
    public static int glGetQueryObjectui(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL15.glGetQueryObjectui(p0, p1));
    }

    // 阻塞取值型
    public static int glGetQueryi(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL15.glGetQueryi(p0, p1));
    }

    // 阻塞取值型
    public static boolean glIsBuffer(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL15.glIsBuffer(p0));
    }

    // 阻塞取值型
    public static boolean glIsQuery(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL15.glIsQuery(p0));
    }

    // 阻塞取值型
    public static java.nio.ByteBuffer glMapBuffer(int p0, int p1, java.nio.ByteBuffer p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL15.glMapBuffer(p0, p1, p2));
    }

    // 阻塞取值型
    public static java.nio.ByteBuffer glMapBuffer(int p0, int p1, long p2, java.nio.ByteBuffer p3) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL15.glMapBuffer(p0, p1, p2, p3));
    }

    // 阻塞取值型
    public static boolean glUnmapBuffer(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL15.glUnmapBuffer(p0));
    }
}
