// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.GL20 的 bridge 镜像生成基类（全量镜像兜底面）。
 * <p>
 * 手写类 {@link GL20} extends 本类：invokestatic 的方法解析先命中手写类
 * 自身声明（顶点流/状态仿真/id stash/map 仿真等精心语义），未覆盖的
 * 落到本基类的通用录制/阻塞语义——手写永远优先，生成物只兜底。
 */
public class GL20Gen {
    protected GL20Gen() {
    }

    // 命令型
    public static void glAttachShader(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glAttachShader(p0, p1));
    }

    // 命令型（字符串捕获，不可变）
    public static void glBindAttribLocation(int p0, int p1, java.lang.CharSequence p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glBindAttribLocation(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glBindAttribLocation(int p0, int p1, java.nio.ByteBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL20.glBindAttribLocation(p0, p1, snapshot));
    }

    // 命令型
    public static void glBlendEquationSeparate(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glBlendEquationSeparate(p0, p1));
    }

    // 命令型
    public static void glCompileShader(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glCompileShader(p0));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glCreateProgram() {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.GL20.glCreateProgram());
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glCreateShader(int p0) {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.GL20.glCreateShader(p0));
    }

    // 命令型
    public static void glDeleteProgram(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glDeleteProgram(p0));
    }

    // 命令型
    public static void glDeleteShader(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glDeleteShader(p0));
    }

    // 命令型
    public static void glDetachShader(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glDetachShader(p0, p1));
    }

    // 命令型
    public static void glDisableVertexAttribArray(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glDisableVertexAttribArray(p0));
    }

    // 命令型
    public static void glDrawBuffers(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glDrawBuffers(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawBuffers(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.GL20.glDrawBuffers(snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glEnableVertexAttribArray(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glEnableVertexAttribArray(p0));
    }

    // 阻塞取值型
    public static java.lang.String glGetActiveAttrib(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL20.glGetActiveAttrib(p0, p1, p2));
    }

    // 阻塞取值型
    public static java.lang.String glGetActiveAttrib(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL20.glGetActiveAttrib(p0, p1, p2, p3));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetActiveAttrib(int p0, int p1, java.nio.IntBuffer p2, java.nio.IntBuffer p3, java.nio.IntBuffer p4, java.nio.ByteBuffer p5) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.GL20.glGetActiveAttrib(p0, p1, p2, p3, p4, p5));
    }

    // 阻塞取值型
    public static int glGetActiveAttribSize(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL20.glGetActiveAttribSize(p0, p1));
    }

    // 阻塞取值型
    public static int glGetActiveAttribType(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL20.glGetActiveAttribType(p0, p1));
    }

    // 阻塞取值型
    public static java.lang.String glGetActiveUniform(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL20.glGetActiveUniform(p0, p1, p2));
    }

    // 阻塞取值型
    public static java.lang.String glGetActiveUniform(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL20.glGetActiveUniform(p0, p1, p2, p3));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetActiveUniform(int p0, int p1, java.nio.IntBuffer p2, java.nio.IntBuffer p3, java.nio.IntBuffer p4, java.nio.ByteBuffer p5) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.GL20.glGetActiveUniform(p0, p1, p2, p3, p4, p5));
    }

    // 阻塞取值型
    public static int glGetActiveUniformSize(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL20.glGetActiveUniformSize(p0, p1));
    }

    // 阻塞取值型
    public static int glGetActiveUniformType(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL20.glGetActiveUniformType(p0, p1));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetAttachedShaders(int p0, java.nio.IntBuffer p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.GL20.glGetAttachedShaders(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetAttribLocation(int p0, java.lang.CharSequence p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL20.glGetAttribLocation(p0, p1));
    }

    // 阻塞取值型
    public static int glGetAttribLocation(int p0, java.nio.ByteBuffer p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL20.glGetAttribLocation(p0, p1));
    }

    // 阻塞取值型
    public static int glGetProgram(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL20.glGetProgram(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetProgram(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.GL20.glGetProgram(p0, p1, buf)));
    }

    // 阻塞取值型
    public static java.lang.String glGetProgramInfoLog(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL20.glGetProgramInfoLog(p0, p1));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetProgramInfoLog(int p0, java.nio.IntBuffer p1, java.nio.ByteBuffer p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.GL20.glGetProgramInfoLog(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetProgrami(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL20.glGetProgrami(p0, p1));
    }

    // 阻塞取值型
    public static int glGetShader(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL20.glGetShader(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetShader(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.GL20.glGetShader(p0, p1, buf)));
    }

    // 阻塞取值型
    public static java.lang.String glGetShaderInfoLog(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL20.glGetShaderInfoLog(p0, p1));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetShaderInfoLog(int p0, java.nio.IntBuffer p1, java.nio.ByteBuffer p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.GL20.glGetShaderInfoLog(p0, p1, p2));
    }

    // 阻塞取值型
    public static java.lang.String glGetShaderSource(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL20.glGetShaderSource(p0, p1));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetShaderSource(int p0, java.nio.IntBuffer p1, java.nio.ByteBuffer p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.GL20.glGetShaderSource(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetShaderi(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL20.glGetShaderi(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetUniform(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p2, 16, buf -> org.lwjgl.opengl.GL20.glGetUniform(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetUniform(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.GL20.glGetUniform(p0, p1, buf)));
    }

    // 阻塞取值型
    public static int glGetUniformLocation(int p0, java.lang.CharSequence p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL20.glGetUniformLocation(p0, p1));
    }

    // 阻塞取值型
    public static int glGetUniformLocation(int p0, java.nio.ByteBuffer p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL20.glGetUniformLocation(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetVertexAttrib(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillDoubles(p2, 16, buf -> org.lwjgl.opengl.GL20.glGetVertexAttrib(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetVertexAttrib(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p2, 16, buf -> org.lwjgl.opengl.GL20.glGetVertexAttrib(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetVertexAttrib(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.GL20.glGetVertexAttrib(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetVertexAttribPointer(int p0, int p1, java.nio.ByteBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillBooleans(p2, 16, buf -> org.lwjgl.opengl.GL20.glGetVertexAttribPointer(p0, p1, buf)));
    }

    // 阻塞取值型
    public static java.nio.ByteBuffer glGetVertexAttribPointer(int p0, int p1, long p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL20.glGetVertexAttribPointer(p0, p1, p2));
    }

    // 阻塞取值型
    public static boolean glIsProgram(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL20.glIsProgram(p0));
    }

    // 阻塞取值型
    public static boolean glIsShader(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL20.glIsShader(p0));
    }

    // 命令型
    public static void glLinkProgram(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glLinkProgram(p0));
    }

    // 命令型（字符串捕获，不可变）
    public static void glShaderSource(int p0, java.lang.CharSequence p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glShaderSource(p0, p1));
    }

    // 命令型（字符串数组录制时刻快照）
    public static void glShaderSource(int p0, java.lang.CharSequence[] p1) {
        final java.lang.CharSequence[] copy = p1.clone();
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glShaderSource(p0, copy));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glShaderSource(int p0, java.nio.ByteBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL20.glShaderSource(p0, snapshot));
    }

    // 命令型
    public static void glStencilFuncSeparate(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glStencilFuncSeparate(p0, p1, p2, p3));
    }

    // 命令型
    public static void glStencilMaskSeparate(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glStencilMaskSeparate(p0, p1));
    }

    // 命令型
    public static void glStencilOpSeparate(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glStencilOpSeparate(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniform1(int p0, java.nio.FloatBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL20.glUniform1(p0, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniform1(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL20.glUniform1(p0, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glUniform1f(int p0, float p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glUniform1f(p0, p1));
    }

    // 命令型
    public static void glUniform1i(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glUniform1i(p0, p1));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniform2(int p0, java.nio.FloatBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL20.glUniform2(p0, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniform2(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL20.glUniform2(p0, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glUniform2f(int p0, float p1, float p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glUniform2f(p0, p1, p2));
    }

    // 命令型
    public static void glUniform2i(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glUniform2i(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniform3(int p0, java.nio.FloatBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL20.glUniform3(p0, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniform3(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL20.glUniform3(p0, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glUniform3f(int p0, float p1, float p2, float p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glUniform3f(p0, p1, p2, p3));
    }

    // 命令型
    public static void glUniform3i(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glUniform3i(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniform4(int p0, java.nio.FloatBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL20.glUniform4(p0, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniform4(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL20.glUniform4(p0, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glUniform4f(int p0, float p1, float p2, float p3, float p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glUniform4f(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glUniform4i(int p0, int p1, int p2, int p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glUniform4i(p0, p1, p2, p3, p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniformMatrix2(int p0, boolean p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL20.glUniformMatrix2(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniformMatrix3(int p0, boolean p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL20.glUniformMatrix3(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glUniformMatrix4(int p0, boolean p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL20.glUniformMatrix4(p0, p1, snapshot.asFloatBuffer()));
    }

    // 命令型
    public static void glUseProgram(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glUseProgram(p0));
    }

    // 命令型
    public static void glValidateProgram(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glValidateProgram(p0));
    }

    // 命令型
    public static void glVertexAttrib1d(int p0, double p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glVertexAttrib1d(p0, p1));
    }

    // 命令型
    public static void glVertexAttrib1f(int p0, float p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glVertexAttrib1f(p0, p1));
    }

    // 命令型
    public static void glVertexAttrib1s(int p0, short p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glVertexAttrib1s(p0, p1));
    }

    // 命令型
    public static void glVertexAttrib2d(int p0, double p1, double p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glVertexAttrib2d(p0, p1, p2));
    }

    // 命令型
    public static void glVertexAttrib2f(int p0, float p1, float p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glVertexAttrib2f(p0, p1, p2));
    }

    // 命令型
    public static void glVertexAttrib2s(int p0, short p1, short p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glVertexAttrib2s(p0, p1, p2));
    }

    // 命令型
    public static void glVertexAttrib3d(int p0, double p1, double p2, double p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glVertexAttrib3d(p0, p1, p2, p3));
    }

    // 命令型
    public static void glVertexAttrib3f(int p0, float p1, float p2, float p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glVertexAttrib3f(p0, p1, p2, p3));
    }

    // 命令型
    public static void glVertexAttrib3s(int p0, short p1, short p2, short p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glVertexAttrib3s(p0, p1, p2, p3));
    }

    // 命令型
    public static void glVertexAttrib4Nub(int p0, byte p1, byte p2, byte p3, byte p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glVertexAttrib4Nub(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glVertexAttrib4d(int p0, double p1, double p2, double p3, double p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glVertexAttrib4d(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glVertexAttrib4f(int p0, float p1, float p2, float p3, float p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glVertexAttrib4f(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glVertexAttrib4s(int p0, short p1, short p2, short p3, short p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glVertexAttrib4s(p0, p1, p2, p3, p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribPointer(int p0, int p1, boolean p2, int p3, java.nio.DoubleBuffer p4) {
        BridgeSupport.enqueueSnapshot(p4, snapshot -> org.lwjgl.opengl.GL20.glVertexAttribPointer(p0, p1, p2, p3, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribPointer(int p0, int p1, boolean p2, int p3, java.nio.FloatBuffer p4) {
        BridgeSupport.enqueueSnapshot(p4, snapshot -> org.lwjgl.opengl.GL20.glVertexAttribPointer(p0, p1, p2, p3, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribPointer(int p0, int p1, boolean p2, boolean p3, int p4, java.nio.ByteBuffer p5) {
        BridgeSupport.enqueueSnapshot(p5, snapshot -> org.lwjgl.opengl.GL20.glVertexAttribPointer(p0, p1, p2, p3, p4, snapshot));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribPointer(int p0, int p1, boolean p2, boolean p3, int p4, java.nio.IntBuffer p5) {
        BridgeSupport.enqueueSnapshot(p5, snapshot -> org.lwjgl.opengl.GL20.glVertexAttribPointer(p0, p1, p2, p3, p4, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribPointer(int p0, int p1, boolean p2, boolean p3, int p4, java.nio.ShortBuffer p5) {
        BridgeSupport.enqueueSnapshot(p5, snapshot -> org.lwjgl.opengl.GL20.glVertexAttribPointer(p0, p1, p2, p3, p4, snapshot.asShortBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribPointer(int p0, int p1, int p2, boolean p3, int p4, java.nio.ByteBuffer p5) {
        BridgeSupport.enqueueSnapshot(p5, snapshot -> org.lwjgl.opengl.GL20.glVertexAttribPointer(p0, p1, p2, p3, p4, snapshot));
    }

    // 命令型
    public static void glVertexAttribPointer(int p0, int p1, int p2, boolean p3, int p4, long p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL20.glVertexAttribPointer(p0, p1, p2, p3, p4, p5));
    }
}
