// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.GL31 的 bridge 镜像生成基类（全量镜像兜底面）。
 * <p>
 * 手写类 {@link GL31} extends 本类：invokestatic 的方法解析先命中手写类
 * 自身声明（顶点流/状态仿真/id stash/map 仿真等精心语义），未覆盖的
 * 落到本基类的通用录制/阻塞语义——手写永远优先，生成物只兜底。
 */
public class GL31Gen {
    protected GL31Gen() {
    }

    // 命令型
    public static void glCopyBufferSubData(int p0, int p1, long p2, long p3, long p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL31.glCopyBufferSubData(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glDrawArraysInstanced(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL31.glDrawArraysInstanced(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElementsInstanced(int p0, java.nio.ByteBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL31.glDrawElementsInstanced(p0, snapshot, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElementsInstanced(int p0, java.nio.IntBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL31.glDrawElementsInstanced(p0, snapshot.asIntBuffer(), p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElementsInstanced(int p0, java.nio.ShortBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL31.glDrawElementsInstanced(p0, snapshot.asShortBuffer(), p2));
    }

    // 命令型
    public static void glDrawElementsInstanced(int p0, int p1, int p2, long p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL31.glDrawElementsInstanced(p0, p1, p2, p3, p4));
    }

    // 阻塞取值型
    public static int glGetActiveUniformBlock(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL31.glGetActiveUniformBlock(p0, p1, p2));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetActiveUniformBlock(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p3, 16, buf -> org.lwjgl.opengl.GL31.glGetActiveUniformBlock(p0, p1, p2, buf)));
    }

    // 阻塞取值型
    public static java.lang.String glGetActiveUniformBlockName(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL31.glGetActiveUniformBlockName(p0, p1, p2));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetActiveUniformBlockName(int p0, int p1, java.nio.IntBuffer p2, java.nio.ByteBuffer p3) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.GL31.glGetActiveUniformBlockName(p0, p1, p2, p3));
    }

    // 阻塞取值型
    public static int glGetActiveUniformBlocki(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL31.glGetActiveUniformBlocki(p0, p1, p2));
    }

    // 阻塞取值型
    public static java.lang.String glGetActiveUniformName(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL31.glGetActiveUniformName(p0, p1, p2));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetActiveUniformName(int p0, int p1, java.nio.IntBuffer p2, java.nio.ByteBuffer p3) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.GL31.glGetActiveUniformName(p0, p1, p2, p3));
    }

    // 阻塞取值型
    public static int glGetActiveUniforms(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL31.glGetActiveUniforms(p0, p1, p2));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetActiveUniforms(int p0, java.nio.IntBuffer p1, int p2, java.nio.IntBuffer p3) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.GL31.glGetActiveUniforms(p0, p1, p2, p3));
    }

    // 阻塞取值型
    public static int glGetActiveUniformsi(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL31.glGetActiveUniformsi(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetUniformBlockIndex(int p0, java.lang.CharSequence p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL31.glGetUniformBlockIndex(p0, p1));
    }

    // 阻塞取值型
    public static int glGetUniformBlockIndex(int p0, java.nio.ByteBuffer p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL31.glGetUniformBlockIndex(p0, p1));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetUniformIndices(int p0, java.lang.CharSequence[] p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.GL31.glGetUniformIndices(p0, p1, p2));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetUniformIndices(int p0, java.nio.ByteBuffer p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.GL31.glGetUniformIndices(p0, p1, p2));
    }

    // 命令型
    public static void glPrimitiveRestartIndex(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL31.glPrimitiveRestartIndex(p0));
    }

    // 命令型
    public static void glTexBuffer(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL31.glTexBuffer(p0, p1, p2));
    }

    // 命令型
    public static void glUniformBlockBinding(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL31.glUniformBlockBinding(p0, p1, p2));
    }
}
