// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.GL32 的 bridge 镜像生成基类（全量镜像兜底面）。
 * <p>
 * 手写类 {@link GL32} extends 本类：invokestatic 的方法解析先命中手写类
 * 自身声明（顶点流/状态仿真/id stash/map 仿真等精心语义），未覆盖的
 * 落到本基类的通用录制/阻塞语义——手写永远优先，生成物只兜底。
 */
public class GL32Gen {
    protected GL32Gen() {
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElementsBaseVertex(int p0, java.nio.ByteBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL32.glDrawElementsBaseVertex(p0, snapshot, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElementsBaseVertex(int p0, java.nio.IntBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL32.glDrawElementsBaseVertex(p0, snapshot.asIntBuffer(), p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElementsBaseVertex(int p0, java.nio.ShortBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL32.glDrawElementsBaseVertex(p0, snapshot.asShortBuffer(), p2));
    }

    // 命令型
    public static void glDrawElementsBaseVertex(int p0, int p1, int p2, long p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL32.glDrawElementsBaseVertex(p0, p1, p2, p3, p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElementsInstancedBaseVertex(int p0, java.nio.ByteBuffer p1, int p2, int p3) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL32.glDrawElementsInstancedBaseVertex(p0, snapshot, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElementsInstancedBaseVertex(int p0, java.nio.IntBuffer p1, int p2, int p3) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL32.glDrawElementsInstancedBaseVertex(p0, snapshot.asIntBuffer(), p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElementsInstancedBaseVertex(int p0, java.nio.ShortBuffer p1, int p2, int p3) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL32.glDrawElementsInstancedBaseVertex(p0, snapshot.asShortBuffer(), p2, p3));
    }

    // 命令型
    public static void glDrawElementsInstancedBaseVertex(int p0, int p1, int p2, long p3, int p4, int p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL32.glDrawElementsInstancedBaseVertex(p0, p1, p2, p3, p4, p5));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawRangeElementsBaseVertex(int p0, int p1, int p2, java.nio.ByteBuffer p3, int p4) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL32.glDrawRangeElementsBaseVertex(p0, p1, p2, snapshot, p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawRangeElementsBaseVertex(int p0, int p1, int p2, java.nio.IntBuffer p3, int p4) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL32.glDrawRangeElementsBaseVertex(p0, p1, p2, snapshot.asIntBuffer(), p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawRangeElementsBaseVertex(int p0, int p1, int p2, java.nio.ShortBuffer p3, int p4) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL32.glDrawRangeElementsBaseVertex(p0, p1, p2, snapshot.asShortBuffer(), p4));
    }

    // 命令型
    public static void glDrawRangeElementsBaseVertex(int p0, int p1, int p2, int p3, int p4, long p5, int p6) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL32.glDrawRangeElementsBaseVertex(p0, p1, p2, p3, p4, p5, p6));
    }

    // 命令型
    public static void glFramebufferTexture(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL32.glFramebufferTexture(p0, p1, p2, p3));
    }

    // 阻塞取值型
    public static long glGetBufferParameter(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL32.glGetBufferParameter(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetBufferParameter(int p0, int p1, java.nio.LongBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillLongs(p2, 16, buf -> org.lwjgl.opengl.GL32.glGetBufferParameter(p0, p1, buf)));
    }

    // 阻塞取值型
    public static long glGetBufferParameteri64(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL32.glGetBufferParameteri64(p0, p1));
    }

    // 阻塞取值型
    public static long glGetInteger64(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL32.glGetInteger64(p0));
    }

    // 阻塞取值型
    public static long glGetInteger64(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL32.glGetInteger64(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetInteger64(int p0, java.nio.LongBuffer p1) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillLongs(p1, 16, buf -> org.lwjgl.opengl.GL32.glGetInteger64(p0, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetInteger64(int p0, int p1, java.nio.LongBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillLongs(p2, 16, buf -> org.lwjgl.opengl.GL32.glGetInteger64(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetMultisample(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p2, 16, buf -> org.lwjgl.opengl.GL32.glGetMultisample(p0, p1, buf)));
    }

    // 命令型
    public static void glProvokingVertex(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL32.glProvokingVertex(p0));
    }

    // 命令型
    public static void glSampleMaski(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL32.glSampleMaski(p0, p1));
    }

    // 命令型
    public static void glTexImage2DMultisample(int p0, int p1, int p2, int p3, int p4, boolean p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL32.glTexImage2DMultisample(p0, p1, p2, p3, p4, p5));
    }

    // 命令型
    public static void glTexImage3DMultisample(int p0, int p1, int p2, int p3, int p4, int p5, boolean p6) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL32.glTexImage3DMultisample(p0, p1, p2, p3, p4, p5, p6));
    }
}
