// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.GL41 的 bridge 镜像生成基类（全量镜像兜底面）。
 * <p>
 * 手写类 {@link GL41} extends 本类：invokestatic 的方法解析先命中手写类
 * 自身声明（顶点流/状态仿真/id stash/map 仿真等精心语义），未覆盖的
 * 落到本基类的通用录制/阻塞语义——手写永远优先，生成物只兜底。
 */
public class GL41Gen {
    protected GL41Gen() {
    }

    // 命令型
    public static void glActiveShaderProgram(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glActiveShaderProgram(p0, p1));
    }

    // 命令型
    public static void glBindProgramPipeline(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glBindProgramPipeline(p0));
    }

    // 命令型
    public static void glClearDepthf(float p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glClearDepthf(p0));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glCreateShaderProgram(int p0, java.lang.CharSequence p1) {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.GL41.glCreateShaderProgram(p0, p1));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glCreateShaderProgram(int p0, java.lang.CharSequence[] p1) {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.GL41.glCreateShaderProgram(p0, p1));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glCreateShaderProgram(int p0, java.nio.ByteBuffer p1) {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.GL41.glCreateShaderProgram(p0, p1));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glCreateShaderProgram(int p0, java.nio.ByteBuffer[] p1) {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.GL41.glCreateShaderProgram(p0, p1));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glCreateShaderProgram(int p0, int p1, java.nio.ByteBuffer p2) {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.GL41.glCreateShaderProgram(p0, p1, p2));
    }

    // 命令型
    public static void glDeleteProgramPipelines(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glDeleteProgramPipelines(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDeleteProgramPipelines(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.GL41.glDeleteProgramPipelines(snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDepthRangeArray(int p0, java.nio.DoubleBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL41.glDepthRangeArray(p0, snapshot.asDoubleBuffer()));
    }

    // 命令型
    public static void glDepthRangeIndexed(int p0, double p1, double p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glDepthRangeIndexed(p0, p1, p2));
    }

    // 命令型
    public static void glDepthRangef(float p0, float p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glDepthRangef(p0, p1));
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glGenProgramPipelines() {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.GL41.glGenProgramPipelines());
    }

    // 阻塞资源型（glGen 族，不计 StallDetector）
    public static void glGenProgramPipelines(java.nio.IntBuffer p0) {
        BridgeSupport.blockingWaitResource(() -> org.lwjgl.opengl.GL41.glGenProgramPipelines(p0));
    }

    // 阻塞取值型
    public static double glGetDouble(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL41.glGetDouble(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetDouble(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillDoubles(p2, 16, buf -> org.lwjgl.opengl.GL41.glGetDouble(p0, p1, buf)));
    }

    // 阻塞取值型
    public static float glGetFloat(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL41.glGetFloat(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetFloat(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p2, 16, buf -> org.lwjgl.opengl.GL41.glGetFloat(p0, p1, buf)));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetProgramBinary(int p0, java.nio.IntBuffer p1, java.nio.IntBuffer p2, java.nio.ByteBuffer p3) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.GL41.glGetProgramBinary(p0, p1, p2, p3));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetProgramPipeline(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.GL41.glGetProgramPipeline(p0, p1, buf)));
    }

    // 阻塞取值型
    public static java.lang.String glGetProgramPipelineInfoLog(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL41.glGetProgramPipelineInfoLog(p0, p1));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetProgramPipelineInfoLog(int p0, java.nio.IntBuffer p1, java.nio.ByteBuffer p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.GL41.glGetProgramPipelineInfoLog(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetProgramPipelinei(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL41.glGetProgramPipelinei(p0, p1));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetShaderPrecisionFormat(int p0, int p1, java.nio.IntBuffer p2, java.nio.IntBuffer p3) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.GL41.glGetShaderPrecisionFormat(p0, p1, p2, p3));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetVertexAttribL(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillDoubles(p2, 16, buf -> org.lwjgl.opengl.GL41.glGetVertexAttribL(p0, p1, buf)));
    }

    // 阻塞取值型
    public static boolean glIsProgramPipeline(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL41.glIsProgramPipeline(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramBinary(int p0, int p1, java.nio.ByteBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL41.glProgramBinary(p0, p1, snapshot));
    }

    // 命令型
    public static void glProgramParameteri(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glProgramParameteri(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform1(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL41.glProgramUniform1(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform1(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL41.glProgramUniform1(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform1(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL41.glProgramUniform1(p0, p1, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glProgramUniform1d(int p0, int p1, double p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glProgramUniform1d(p0, p1, p2));
    }

    // 命令型
    public static void glProgramUniform1f(int p0, int p1, float p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glProgramUniform1f(p0, p1, p2));
    }

    // 命令型
    public static void glProgramUniform1i(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glProgramUniform1i(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform1u(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL41.glProgramUniform1u(p0, p1, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glProgramUniform1ui(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glProgramUniform1ui(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform2(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL41.glProgramUniform2(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform2(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL41.glProgramUniform2(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform2(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL41.glProgramUniform2(p0, p1, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glProgramUniform2d(int p0, int p1, double p2, double p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glProgramUniform2d(p0, p1, p2, p3));
    }

    // 命令型
    public static void glProgramUniform2f(int p0, int p1, float p2, float p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glProgramUniform2f(p0, p1, p2, p3));
    }

    // 命令型
    public static void glProgramUniform2i(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glProgramUniform2i(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform2u(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL41.glProgramUniform2u(p0, p1, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glProgramUniform2ui(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glProgramUniform2ui(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform3(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL41.glProgramUniform3(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform3(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL41.glProgramUniform3(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform3(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL41.glProgramUniform3(p0, p1, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glProgramUniform3d(int p0, int p1, double p2, double p3, double p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glProgramUniform3d(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glProgramUniform3f(int p0, int p1, float p2, float p3, float p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glProgramUniform3f(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glProgramUniform3i(int p0, int p1, int p2, int p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glProgramUniform3i(p0, p1, p2, p3, p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform3u(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL41.glProgramUniform3u(p0, p1, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glProgramUniform3ui(int p0, int p1, int p2, int p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glProgramUniform3ui(p0, p1, p2, p3, p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform4(int p0, int p1, java.nio.DoubleBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL41.glProgramUniform4(p0, p1, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform4(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL41.glProgramUniform4(p0, p1, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform4(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL41.glProgramUniform4(p0, p1, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glProgramUniform4d(int p0, int p1, double p2, double p3, double p4, double p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glProgramUniform4d(p0, p1, p2, p3, p4, p5));
    }

    // 命令型
    public static void glProgramUniform4f(int p0, int p1, float p2, float p3, float p4, float p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glProgramUniform4f(p0, p1, p2, p3, p4, p5));
    }

    // 命令型
    public static void glProgramUniform4i(int p0, int p1, int p2, int p3, int p4, int p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glProgramUniform4i(p0, p1, p2, p3, p4, p5));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniform4u(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.GL41.glProgramUniform4u(p0, p1, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glProgramUniform4ui(int p0, int p1, int p2, int p3, int p4, int p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glProgramUniform4ui(p0, p1, p2, p3, p4, p5));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix2(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL41.glProgramUniformMatrix2(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix2(int p0, int p1, boolean p2, java.nio.FloatBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL41.glProgramUniformMatrix2(p0, p1, p2, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix2x3(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL41.glProgramUniformMatrix2x3(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix2x3(int p0, int p1, boolean p2, java.nio.FloatBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL41.glProgramUniformMatrix2x3(p0, p1, p2, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix2x4(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL41.glProgramUniformMatrix2x4(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix2x4(int p0, int p1, boolean p2, java.nio.FloatBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL41.glProgramUniformMatrix2x4(p0, p1, p2, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix3(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL41.glProgramUniformMatrix3(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix3(int p0, int p1, boolean p2, java.nio.FloatBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL41.glProgramUniformMatrix3(p0, p1, p2, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix3x2(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL41.glProgramUniformMatrix3x2(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix3x2(int p0, int p1, boolean p2, java.nio.FloatBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL41.glProgramUniformMatrix3x2(p0, p1, p2, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix3x4(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL41.glProgramUniformMatrix3x4(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix3x4(int p0, int p1, boolean p2, java.nio.FloatBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL41.glProgramUniformMatrix3x4(p0, p1, p2, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix4(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL41.glProgramUniformMatrix4(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix4(int p0, int p1, boolean p2, java.nio.FloatBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL41.glProgramUniformMatrix4(p0, p1, p2, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix4x2(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL41.glProgramUniformMatrix4x2(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix4x2(int p0, int p1, boolean p2, java.nio.FloatBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL41.glProgramUniformMatrix4x2(p0, p1, p2, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix4x3(int p0, int p1, boolean p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL41.glProgramUniformMatrix4x3(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramUniformMatrix4x3(int p0, int p1, boolean p2, java.nio.FloatBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL41.glProgramUniformMatrix4x3(p0, p1, p2, snapshot.asFloatBuffer()));
    }

    // 命令型
    public static void glReleaseShaderCompiler() {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glReleaseShaderCompiler());
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glScissorArray(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL41.glScissorArray(p0, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glScissorIndexed(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL41.glScissorIndexed(p0, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glScissorIndexed(int p0, int p1, int p2, int p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glScissorIndexed(p0, p1, p2, p3, p4));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glShaderBinary(java.nio.IntBuffer p0, int p1, java.nio.ByteBuffer p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.GL41.glShaderBinary(p0, p1, p2));
    }

    // 命令型
    public static void glUseProgramStages(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glUseProgramStages(p0, p1, p2));
    }

    // 命令型
    public static void glValidateProgramPipeline(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glValidateProgramPipeline(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribL1(int p0, java.nio.DoubleBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL41.glVertexAttribL1(p0, snapshot.asDoubleBuffer()));
    }

    // 命令型
    public static void glVertexAttribL1d(int p0, double p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glVertexAttribL1d(p0, p1));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribL2(int p0, java.nio.DoubleBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL41.glVertexAttribL2(p0, snapshot.asDoubleBuffer()));
    }

    // 命令型
    public static void glVertexAttribL2d(int p0, double p1, double p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glVertexAttribL2d(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribL3(int p0, java.nio.DoubleBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL41.glVertexAttribL3(p0, snapshot.asDoubleBuffer()));
    }

    // 命令型
    public static void glVertexAttribL3d(int p0, double p1, double p2, double p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glVertexAttribL3d(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribL4(int p0, java.nio.DoubleBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL41.glVertexAttribL4(p0, snapshot.asDoubleBuffer()));
    }

    // 命令型
    public static void glVertexAttribL4d(int p0, double p1, double p2, double p3, double p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glVertexAttribL4d(p0, p1, p2, p3, p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVertexAttribLPointer(int p0, int p1, int p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.GL41.glVertexAttribLPointer(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 命令型
    public static void glVertexAttribLPointer(int p0, int p1, int p2, long p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glVertexAttribLPointer(p0, p1, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glViewportArray(int p0, java.nio.FloatBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL41.glViewportArray(p0, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glViewportIndexed(int p0, java.nio.FloatBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL41.glViewportIndexed(p0, snapshot.asFloatBuffer()));
    }

    // 命令型
    public static void glViewportIndexedf(int p0, float p1, float p2, float p3, float p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL41.glViewportIndexedf(p0, p1, p2, p3, p4));
    }
}
