// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.GL42 的 bridge 镜像生成基类（全量镜像兜底面）。
 * <p>
 * 手写类 {@link GL42} extends 本类：invokestatic 的方法解析先命中手写类
 * 自身声明（顶点流/状态仿真/id stash/map 仿真等精心语义），未覆盖的
 * 落到本基类的通用录制/阻塞语义——手写永远优先，生成物只兜底。
 */
public class GL42Gen {
    protected GL42Gen() {
    }

    // 命令型
    public static void glBindImageTexture(int p0, int p1, int p2, boolean p3, int p4, int p5, int p6) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL42.glBindImageTexture(p0, p1, p2, p3, p4, p5, p6));
    }

    // 命令型
    public static void glDrawArraysInstancedBaseInstance(int p0, int p1, int p2, int p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL42.glDrawArraysInstancedBaseInstance(p0, p1, p2, p3, p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElementsInstancedBaseInstance(int p0, java.nio.ByteBuffer p1, int p2, int p3) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL42.glDrawElementsInstancedBaseInstance(p0, snapshot, p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElementsInstancedBaseInstance(int p0, java.nio.IntBuffer p1, int p2, int p3) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL42.glDrawElementsInstancedBaseInstance(p0, snapshot.asIntBuffer(), p2, p3));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElementsInstancedBaseInstance(int p0, java.nio.ShortBuffer p1, int p2, int p3) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL42.glDrawElementsInstancedBaseInstance(p0, snapshot.asShortBuffer(), p2, p3));
    }

    // 命令型
    public static void glDrawElementsInstancedBaseInstance(int p0, int p1, int p2, long p3, int p4, int p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL42.glDrawElementsInstancedBaseInstance(p0, p1, p2, p3, p4, p5));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElementsInstancedBaseVertexBaseInstance(int p0, java.nio.ByteBuffer p1, int p2, int p3, int p4) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL42.glDrawElementsInstancedBaseVertexBaseInstance(p0, snapshot, p2, p3, p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElementsInstancedBaseVertexBaseInstance(int p0, java.nio.IntBuffer p1, int p2, int p3, int p4) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL42.glDrawElementsInstancedBaseVertexBaseInstance(p0, snapshot.asIntBuffer(), p2, p3, p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDrawElementsInstancedBaseVertexBaseInstance(int p0, java.nio.ShortBuffer p1, int p2, int p3, int p4) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.GL42.glDrawElementsInstancedBaseVertexBaseInstance(p0, snapshot.asShortBuffer(), p2, p3, p4));
    }

    // 命令型
    public static void glDrawElementsInstancedBaseVertexBaseInstance(int p0, int p1, int p2, long p3, int p4, int p5, int p6) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL42.glDrawElementsInstancedBaseVertexBaseInstance(p0, p1, p2, p3, p4, p5, p6));
    }

    // 命令型
    public static void glDrawTransformFeedbackInstanced(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL42.glDrawTransformFeedbackInstanced(p0, p1, p2));
    }

    // 命令型
    public static void glDrawTransformFeedbackStreamInstanced(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL42.glDrawTransformFeedbackStreamInstanced(p0, p1, p2, p3));
    }

    // 阻塞取值型
    public static int glGetActiveAtomicCounterBuffer(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL42.glGetActiveAtomicCounterBuffer(p0, p1, p2));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetActiveAtomicCounterBuffer(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p3, 16, buf -> org.lwjgl.opengl.GL42.glGetActiveAtomicCounterBuffer(p0, p1, p2, buf)));
    }

    // 阻塞取值型
    public static int glGetInternalformat(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.GL42.glGetInternalformat(p0, p1, p2));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetInternalformat(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p3, 16, buf -> org.lwjgl.opengl.GL42.glGetInternalformat(p0, p1, p2, buf)));
    }

    // 命令型
    public static void glMemoryBarrier(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL42.glMemoryBarrier(p0));
    }

    // 命令型
    public static void glTexStorage1D(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL42.glTexStorage1D(p0, p1, p2, p3));
    }

    // 命令型
    public static void glTexStorage2D(int p0, int p1, int p2, int p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL42.glTexStorage2D(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glTexStorage3D(int p0, int p1, int p2, int p3, int p4, int p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GL42.glTexStorage3D(p0, p1, p2, p3, p4, p5));
    }
}
