// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.GREMEDYStringMarker 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class GREMEDYStringMarker {
    private GREMEDYStringMarker() {
    }

    // 命令型（字符串捕获，不可变）
    public static void glStringMarkerGREMEDY(java.lang.CharSequence p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.GREMEDYStringMarker.glStringMarkerGREMEDY(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glStringMarkerGREMEDY(java.nio.ByteBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.GREMEDYStringMarker.glStringMarkerGREMEDY(snapshot));
    }
}
