// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.INTELMapTexture 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class INTELMapTexture {
    private INTELMapTexture() {
    }

    // 阻塞取值型
    public static java.nio.ByteBuffer glMapTexture2DINTEL(int p0, int p1, long p2, int p3, java.nio.IntBuffer p4, java.nio.IntBuffer p5, java.nio.ByteBuffer p6) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.INTELMapTexture.glMapTexture2DINTEL(p0, p1, p2, p3, p4, p5, p6));
    }

    // 命令型
    public static void glSyncTextureINTEL(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.INTELMapTexture.glSyncTextureINTEL(p0));
    }

    // 命令型
    public static void glUnmapTexture2DINTEL(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.INTELMapTexture.glUnmapTexture2DINTEL(p0, p1));
    }
}
