// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.KHRDebug 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class KHRDebug {
    private KHRDebug() {
    }

    // 命令型（回调引用捕获，回调随后在渲染线程触发）
    public static void glDebugMessageCallback(org.lwjgl.opengl.KHRDebugCallback p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.KHRDebug.glDebugMessageCallback(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDebugMessageControl(int p0, int p1, int p2, java.nio.IntBuffer p3, boolean p4) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.KHRDebug.glDebugMessageControl(p0, p1, p2, snapshot.asIntBuffer(), p4));
    }

    // 命令型（字符串捕获，不可变）
    public static void glDebugMessageInsert(int p0, int p1, int p2, int p3, java.lang.CharSequence p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.KHRDebug.glDebugMessageInsert(p0, p1, p2, p3, p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDebugMessageInsert(int p0, int p1, int p2, int p3, java.nio.ByteBuffer p4) {
        BridgeSupport.enqueueSnapshot(p4, snapshot -> org.lwjgl.opengl.KHRDebug.glDebugMessageInsert(p0, p1, p2, p3, snapshot));
    }

    // 阻塞取值型
    public static int glGetDebugMessageLog(int p0, java.nio.IntBuffer p1, java.nio.IntBuffer p2, java.nio.IntBuffer p3, java.nio.IntBuffer p4, java.nio.IntBuffer p5, java.nio.ByteBuffer p6) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.KHRDebug.glGetDebugMessageLog(p0, p1, p2, p3, p4, p5, p6));
    }

    // 阻塞取值型
    public static java.lang.String glGetObjectLabel(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.KHRDebug.glGetObjectLabel(p0, p1, p2));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetObjectLabel(int p0, int p1, java.nio.IntBuffer p2, java.nio.ByteBuffer p3) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.KHRDebug.glGetObjectLabel(p0, p1, p2, p3));
    }

    // 阻塞取值型
    public static java.lang.String glGetObjectPtrLabel(org.lwjgl.PointerWrapper p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.KHRDebug.glGetObjectPtrLabel(p0, p1));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetObjectPtrLabel(org.lwjgl.PointerWrapper p0, java.nio.IntBuffer p1, java.nio.ByteBuffer p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.KHRDebug.glGetObjectPtrLabel(p0, p1, p2));
    }

    // 命令型（字符串捕获，不可变）
    public static void glObjectLabel(int p0, int p1, java.lang.CharSequence p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.KHRDebug.glObjectLabel(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glObjectLabel(int p0, int p1, java.nio.ByteBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.KHRDebug.glObjectLabel(p0, p1, snapshot));
    }

    // 命令型（字符串捕获，不可变）
    public static void glObjectPtrLabel(org.lwjgl.PointerWrapper p0, java.lang.CharSequence p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.KHRDebug.glObjectPtrLabel(p0, p1));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glObjectPtrLabel(org.lwjgl.PointerWrapper p0, java.nio.ByteBuffer p1) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.KHRDebug.glObjectPtrLabel(p0, p1));
    }

    // 命令型
    public static void glPopDebugGroup() {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.KHRDebug.glPopDebugGroup());
    }

    // 命令型（字符串捕获，不可变）
    public static void glPushDebugGroup(int p0, int p1, java.lang.CharSequence p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.KHRDebug.glPushDebugGroup(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glPushDebugGroup(int p0, int p1, java.nio.ByteBuffer p2) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.KHRDebug.glPushDebugGroup(p0, p1, snapshot));
    }
}
