// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.NVBindlessTexture 的 bridge 镜像生成基类（全量镜像兜底面）。
 * <p>
 * 手写类 {@link NVBindlessTexture} extends 本类：invokestatic 的方法解析先命中手写类
 * 自身声明（顶点流/状态仿真/id stash/map 仿真等精心语义），未覆盖的
 * 落到本基类的通用录制/阻塞语义——手写永远优先，生成物只兜底。
 */
public class NVBindlessTextureGen {
    protected NVBindlessTextureGen() {
    }

    // 阻塞取值型
    public static long glGetImageHandleNV(int p0, int p1, boolean p2, int p3, int p4) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVBindlessTexture.glGetImageHandleNV(p0, p1, p2, p3, p4));
    }

    // 阻塞取值型
    public static long glGetTextureHandleNV(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVBindlessTexture.glGetTextureHandleNV(p0));
    }

    // 阻塞取值型
    public static long glGetTextureSamplerHandleNV(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVBindlessTexture.glGetTextureSamplerHandleNV(p0, p1));
    }

    // 阻塞取值型
    public static boolean glIsImageHandleResidentNV(long p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVBindlessTexture.glIsImageHandleResidentNV(p0));
    }

    // 阻塞取值型
    public static boolean glIsTextureHandleResidentNV(long p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVBindlessTexture.glIsTextureHandleResidentNV(p0));
    }

    // 命令型
    public static void glMakeImageHandleNonResidentNV(long p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVBindlessTexture.glMakeImageHandleNonResidentNV(p0));
    }

    // 命令型
    public static void glMakeImageHandleResidentNV(long p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVBindlessTexture.glMakeImageHandleResidentNV(p0, p1));
    }

    // 命令型
    public static void glMakeTextureHandleNonResidentNV(long p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVBindlessTexture.glMakeTextureHandleNonResidentNV(p0));
    }

    // 命令型
    public static void glMakeTextureHandleResidentNV(long p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVBindlessTexture.glMakeTextureHandleResidentNV(p0));
    }

    // 阻塞直通型（降级：enqueueSnapshot 无 LongBuffer 重载）
    public static void glProgramUniformHandleuNV(int p0, int p1, java.nio.LongBuffer p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.NVBindlessTexture.glProgramUniformHandleuNV(p0, p1, p2));
    }

    // 命令型
    public static void glProgramUniformHandleui64NV(int p0, int p1, long p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVBindlessTexture.glProgramUniformHandleui64NV(p0, p1, p2));
    }

    // 阻塞直通型（降级：enqueueSnapshot 无 LongBuffer 重载）
    public static void glUniformHandleuNV(int p0, java.nio.LongBuffer p1) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.NVBindlessTexture.glUniformHandleuNV(p0, p1));
    }

    // 命令型
    public static void glUniformHandleui64NV(int p0, long p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVBindlessTexture.glUniformHandleui64NV(p0, p1));
    }
}
