// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.NVBindlessMultiDrawIndirect 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class NVBindlessMultiDrawIndirect {
    private NVBindlessMultiDrawIndirect() {
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glMultiDrawArraysIndirectBindlessNV(int p0, java.nio.ByteBuffer p1, int p2, int p3, int p4) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.NVBindlessMultiDrawIndirect.glMultiDrawArraysIndirectBindlessNV(p0, snapshot, p2, p3, p4));
    }

    // 命令型
    public static void glMultiDrawArraysIndirectBindlessNV(int p0, long p1, int p2, int p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVBindlessMultiDrawIndirect.glMultiDrawArraysIndirectBindlessNV(p0, p1, p2, p3, p4));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glMultiDrawElementsIndirectBindlessNV(int p0, int p1, java.nio.ByteBuffer p2, int p3, int p4, int p5) {
        BridgeSupport.enqueueSnapshot(p2, snapshot -> org.lwjgl.opengl.NVBindlessMultiDrawIndirect.glMultiDrawElementsIndirectBindlessNV(p0, p1, snapshot, p3, p4, p5));
    }

    // 命令型
    public static void glMultiDrawElementsIndirectBindlessNV(int p0, int p1, long p2, int p3, int p4, int p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVBindlessMultiDrawIndirect.glMultiDrawElementsIndirectBindlessNV(p0, p1, p2, p3, p4, p5));
    }
}
