// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.NVDrawTexture 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class NVDrawTexture {
    private NVDrawTexture() {
    }

    // 命令型
    public static void glDrawTextureNV(int p0, int p1, float p2, float p3, float p4, float p5, float p6, float p7, float p8, float p9, float p10) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVDrawTexture.glDrawTextureNV(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    }
}
