// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.NVExplicitMultisample 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class NVExplicitMultisample {
    private NVExplicitMultisample() {
    }

    // 阻塞取值型
    public static boolean glGetBooleanIndexedEXT(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVExplicitMultisample.glGetBooleanIndexedEXT(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetBooleanIndexedEXT(int p0, int p1, java.nio.ByteBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillBooleans(p2, 16, buf -> org.lwjgl.opengl.NVExplicitMultisample.glGetBooleanIndexedEXT(p0, p1, buf)));
    }

    // 阻塞取值型
    public static int glGetIntegerIndexedEXT(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVExplicitMultisample.glGetIntegerIndexedEXT(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetIntegerIndexedEXT(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.NVExplicitMultisample.glGetIntegerIndexedEXT(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetMultisampleNV(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p2, 16, buf -> org.lwjgl.opengl.NVExplicitMultisample.glGetMultisampleNV(p0, p1, buf)));
    }

    // 命令型
    public static void glSampleMaskIndexedNV(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVExplicitMultisample.glSampleMaskIndexedNV(p0, p1));
    }

    // 命令型
    public static void glTexRenderbufferNV(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVExplicitMultisample.glTexRenderbufferNV(p0, p1));
    }
}
