// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.NVOcclusionQuery 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class NVOcclusionQuery {
    private NVOcclusionQuery() {
    }

    // 命令型
    public static void glBeginOcclusionQueryNV(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVOcclusionQuery.glBeginOcclusionQueryNV(p0));
    }

    // 命令型
    public static void glDeleteOcclusionQueriesNV(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVOcclusionQuery.glDeleteOcclusionQueriesNV(p0));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glDeleteOcclusionQueriesNV(java.nio.IntBuffer p0) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.NVOcclusionQuery.glDeleteOcclusionQueriesNV(snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glEndOcclusionQueryNV() {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVOcclusionQuery.glEndOcclusionQueryNV());
    }

    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）
    public static int glGenOcclusionQueriesNV() {
        return BridgeSupport.blockingGetResource(() -> org.lwjgl.opengl.NVOcclusionQuery.glGenOcclusionQueriesNV());
    }

    // 阻塞资源型（glGen 族，不计 StallDetector）
    public static void glGenOcclusionQueriesNV(java.nio.IntBuffer p0) {
        BridgeSupport.blockingWaitResource(() -> org.lwjgl.opengl.NVOcclusionQuery.glGenOcclusionQueriesNV(p0));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetOcclusionQueryNV(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.NVOcclusionQuery.glGetOcclusionQueryNV(p0, p1, buf)));
    }

    // 阻塞取值型
    public static int glGetOcclusionQueryiNV(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVOcclusionQuery.glGetOcclusionQueryiNV(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetOcclusionQueryuNV(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.NVOcclusionQuery.glGetOcclusionQueryuNV(p0, p1, buf)));
    }

    // 阻塞取值型
    public static int glGetOcclusionQueryuiNV(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVOcclusionQuery.glGetOcclusionQueryuiNV(p0, p1));
    }

    // 阻塞取值型
    public static boolean glIsOcclusionQueryNV(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVOcclusionQuery.glIsOcclusionQueryNV(p0));
    }
}
