// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.NVParameterBufferObject 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class NVParameterBufferObject {
    private NVParameterBufferObject() {
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramBufferParametersINV(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.NVParameterBufferObject.glProgramBufferParametersINV(p0, p1, p2, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramBufferParametersIuNV(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.NVParameterBufferObject.glProgramBufferParametersIuNV(p0, p1, p2, snapshot.asIntBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glProgramBufferParametersNV(int p0, int p1, int p2, java.nio.FloatBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.NVParameterBufferObject.glProgramBufferParametersNV(p0, p1, p2, snapshot.asFloatBuffer()));
    }
}
