// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.NVPointSprite 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class NVPointSprite {
    private NVPointSprite() {
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glPointParameterNV(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.NVPointSprite.glPointParameterNV(p0, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glPointParameteriNV(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVPointSprite.glPointParameteriNV(p0, p1));
    }
}
