// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.NVPresentVideo 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class NVPresentVideo {
    private NVPresentVideo() {
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetVideoNV(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.NVPresentVideo.glGetVideoNV(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetVideoNV(int p0, int p1, java.nio.LongBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillLongs(p2, 16, buf -> org.lwjgl.opengl.NVPresentVideo.glGetVideoNV(p0, p1, buf)));
    }

    // 阻塞取值型
    public static long glGetVideoi64NV(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVPresentVideo.glGetVideoi64NV(p0, p1));
    }

    // 阻塞取值型
    public static int glGetVideoiNV(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVPresentVideo.glGetVideoiNV(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetVideouNV(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.NVPresentVideo.glGetVideouNV(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetVideouNV(int p0, int p1, java.nio.LongBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillLongs(p2, 16, buf -> org.lwjgl.opengl.NVPresentVideo.glGetVideouNV(p0, p1, buf)));
    }

    // 阻塞取值型
    public static long glGetVideoui64NV(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVPresentVideo.glGetVideoui64NV(p0, p1));
    }

    // 阻塞取值型
    public static int glGetVideouiNV(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVPresentVideo.glGetVideouiNV(p0, p1));
    }

    // 命令型
    public static void glPresentFrameDualFillNV(int p0, long p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, int p10, int p11, int p12) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVPresentVideo.glPresentFrameDualFillNV(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12));
    }

    // 命令型
    public static void glPresentFrameKeyedNV(int p0, long p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, int p10) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVPresentVideo.glPresentFrameKeyedNV(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    }
}
