// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.NVRegisterCombiners 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class NVRegisterCombiners {
    private NVRegisterCombiners() {
    }

    // 命令型
    public static void glCombinerInputNV(int p0, int p1, int p2, int p3, int p4, int p5) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVRegisterCombiners.glCombinerInputNV(p0, p1, p2, p3, p4, p5));
    }

    // 命令型
    public static void glCombinerOutputNV(int p0, int p1, int p2, int p3, int p4, int p5, int p6, boolean p7, boolean p8, boolean p9) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVRegisterCombiners.glCombinerOutputNV(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCombinerParameterNV(int p0, java.nio.FloatBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.NVRegisterCombiners.glCombinerParameterNV(p0, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glCombinerParameterNV(int p0, java.nio.IntBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.NVRegisterCombiners.glCombinerParameterNV(p0, snapshot.asIntBuffer()));
    }

    // 命令型
    public static void glCombinerParameterfNV(int p0, float p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVRegisterCombiners.glCombinerParameterfNV(p0, p1));
    }

    // 命令型
    public static void glCombinerParameteriNV(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVRegisterCombiners.glCombinerParameteriNV(p0, p1));
    }

    // 命令型
    public static void glFinalCombinerInputNV(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVRegisterCombiners.glFinalCombinerInputNV(p0, p1, p2, p3));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetCombinerInputParameterNV(int p0, int p1, int p2, int p3, java.nio.FloatBuffer p4) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p4, 16, buf -> org.lwjgl.opengl.NVRegisterCombiners.glGetCombinerInputParameterNV(p0, p1, p2, p3, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetCombinerInputParameterNV(int p0, int p1, int p2, int p3, java.nio.IntBuffer p4) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p4, 16, buf -> org.lwjgl.opengl.NVRegisterCombiners.glGetCombinerInputParameterNV(p0, p1, p2, p3, buf)));
    }

    // 阻塞取值型
    public static float glGetCombinerInputParameterfNV(int p0, int p1, int p2, int p3) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVRegisterCombiners.glGetCombinerInputParameterfNV(p0, p1, p2, p3));
    }

    // 阻塞取值型
    public static int glGetCombinerInputParameteriNV(int p0, int p1, int p2, int p3) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVRegisterCombiners.glGetCombinerInputParameteriNV(p0, p1, p2, p3));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetCombinerOutputParameterNV(int p0, int p1, int p2, java.nio.FloatBuffer p3) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p3, 16, buf -> org.lwjgl.opengl.NVRegisterCombiners.glGetCombinerOutputParameterNV(p0, p1, p2, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetCombinerOutputParameterNV(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p3, 16, buf -> org.lwjgl.opengl.NVRegisterCombiners.glGetCombinerOutputParameterNV(p0, p1, p2, buf)));
    }

    // 阻塞取值型
    public static float glGetCombinerOutputParameterfNV(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVRegisterCombiners.glGetCombinerOutputParameterfNV(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetCombinerOutputParameteriNV(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVRegisterCombiners.glGetCombinerOutputParameteriNV(p0, p1, p2));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetFinalCombinerInputParameterNV(int p0, int p1, java.nio.FloatBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p2, 16, buf -> org.lwjgl.opengl.NVRegisterCombiners.glGetFinalCombinerInputParameterNV(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetFinalCombinerInputParameterNV(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.NVRegisterCombiners.glGetFinalCombinerInputParameterNV(p0, p1, buf)));
    }

    // 阻塞取值型
    public static float glGetFinalCombinerInputParameterfNV(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVRegisterCombiners.glGetFinalCombinerInputParameterfNV(p0, p1));
    }

    // 阻塞取值型
    public static int glGetFinalCombinerInputParameteriNV(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVRegisterCombiners.glGetFinalCombinerInputParameteriNV(p0, p1));
    }
}
