// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.NVShaderBufferLoad 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class NVShaderBufferLoad {
    private NVShaderBufferLoad() {
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetBufferParameteruNV(int p0, int p1, java.nio.LongBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillLongs(p2, 16, buf -> org.lwjgl.opengl.NVShaderBufferLoad.glGetBufferParameteruNV(p0, p1, buf)));
    }

    // 阻塞取值型
    public static long glGetBufferParameterui64NV(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVShaderBufferLoad.glGetBufferParameterui64NV(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetIntegeruNV(int p0, java.nio.LongBuffer p1) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillLongs(p1, 16, buf -> org.lwjgl.opengl.NVShaderBufferLoad.glGetIntegeruNV(p0, buf)));
    }

    // 阻塞取值型
    public static long glGetIntegerui64NV(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVShaderBufferLoad.glGetIntegerui64NV(p0));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetNamedBufferParameteruNV(int p0, int p1, java.nio.LongBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillLongs(p2, 16, buf -> org.lwjgl.opengl.NVShaderBufferLoad.glGetNamedBufferParameteruNV(p0, p1, buf)));
    }

    // 阻塞取值型
    public static long glGetNamedBufferParameterui64NV(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVShaderBufferLoad.glGetNamedBufferParameterui64NV(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetUniformuNV(int p0, int p1, java.nio.LongBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillLongs(p2, 16, buf -> org.lwjgl.opengl.NVShaderBufferLoad.glGetUniformuNV(p0, p1, buf)));
    }

    // 阻塞取值型
    public static boolean glIsBufferResidentNV(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVShaderBufferLoad.glIsBufferResidentNV(p0));
    }

    // 阻塞取值型
    public static boolean glIsNamedBufferResidentNV(int p0) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVShaderBufferLoad.glIsNamedBufferResidentNV(p0));
    }

    // 命令型
    public static void glMakeBufferNonResidentNV(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVShaderBufferLoad.glMakeBufferNonResidentNV(p0));
    }

    // 命令型
    public static void glMakeBufferResidentNV(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVShaderBufferLoad.glMakeBufferResidentNV(p0, p1));
    }

    // 命令型
    public static void glMakeNamedBufferNonResidentNV(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVShaderBufferLoad.glMakeNamedBufferNonResidentNV(p0));
    }

    // 命令型
    public static void glMakeNamedBufferResidentNV(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVShaderBufferLoad.glMakeNamedBufferResidentNV(p0, p1));
    }

    // 阻塞直通型（降级：enqueueSnapshot 无 LongBuffer 重载）
    public static void glProgramUniformuNV(int p0, int p1, java.nio.LongBuffer p2) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.NVShaderBufferLoad.glProgramUniformuNV(p0, p1, p2));
    }

    // 命令型
    public static void glProgramUniformui64NV(int p0, int p1, long p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVShaderBufferLoad.glProgramUniformui64NV(p0, p1, p2));
    }

    // 阻塞直通型（降级：enqueueSnapshot 无 LongBuffer 重载）
    public static void glUniformuNV(int p0, java.nio.LongBuffer p1) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.NVShaderBufferLoad.glUniformuNV(p0, p1));
    }

    // 命令型
    public static void glUniformui64NV(int p0, long p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVShaderBufferLoad.glUniformui64NV(p0, p1));
    }
}
