// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.NVTransformFeedback 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class NVTransformFeedback {
    private NVTransformFeedback() {
    }

    // 命令型（字符串捕获，不可变）
    public static void glActiveVaryingNV(int p0, java.lang.CharSequence p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVTransformFeedback.glActiveVaryingNV(p0, p1));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glActiveVaryingNV(int p0, java.nio.ByteBuffer p1) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.NVTransformFeedback.glActiveVaryingNV(p0, snapshot));
    }

    // 命令型
    public static void glBeginTransformFeedbackNV(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVTransformFeedback.glBeginTransformFeedbackNV(p0));
    }

    // 命令型
    public static void glBindBufferBaseNV(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVTransformFeedback.glBindBufferBaseNV(p0, p1, p2));
    }

    // 命令型
    public static void glBindBufferOffsetNV(int p0, int p1, int p2, long p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVTransformFeedback.glBindBufferOffsetNV(p0, p1, p2, p3));
    }

    // 命令型
    public static void glBindBufferRangeNV(int p0, int p1, int p2, long p3, long p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVTransformFeedback.glBindBufferRangeNV(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glEndTransformFeedbackNV() {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVTransformFeedback.glEndTransformFeedbackNV());
    }

    // 阻塞取值型
    public static java.lang.String glGetActiveVaryingNV(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVTransformFeedback.glGetActiveVaryingNV(p0, p1, p2));
    }

    // 阻塞取值型
    public static java.lang.String glGetActiveVaryingNV(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVTransformFeedback.glGetActiveVaryingNV(p0, p1, p2, p3));
    }

    // 阻塞直通型（阻塞期间 buffer/指针直传安全）
    public static void glGetActiveVaryingNV(int p0, int p1, java.nio.IntBuffer p2, java.nio.IntBuffer p3, java.nio.IntBuffer p4, java.nio.ByteBuffer p5) {
        BridgeSupport.blockingWait(() -> org.lwjgl.opengl.NVTransformFeedback.glGetActiveVaryingNV(p0, p1, p2, p3, p4, p5));
    }

    // 阻塞取值型
    public static int glGetActiveVaryingSizeNV(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVTransformFeedback.glGetActiveVaryingSizeNV(p0, p1));
    }

    // 阻塞取值型
    public static int glGetActiveVaryingTypeNV(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVTransformFeedback.glGetActiveVaryingTypeNV(p0, p1));
    }

    // 阻塞取值型
    public static int glGetTransformFeedbackVaryingNV(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVTransformFeedback.glGetTransformFeedbackVaryingNV(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetTransformFeedbackVaryingNV(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.NVTransformFeedback.glGetTransformFeedbackVaryingNV(p0, p1, buf)));
    }

    // 阻塞取值型
    public static int glGetVaryingLocationNV(int p0, java.lang.CharSequence p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVTransformFeedback.glGetVaryingLocationNV(p0, p1));
    }

    // 阻塞取值型
    public static int glGetVaryingLocationNV(int p0, java.nio.ByteBuffer p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVTransformFeedback.glGetVaryingLocationNV(p0, p1));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTransformFeedbackAttribsNV(java.nio.IntBuffer p0, int p1) {
        BridgeSupport.enqueueSnapshot(p0, snapshot -> org.lwjgl.opengl.NVTransformFeedback.glTransformFeedbackAttribsNV(snapshot.asIntBuffer(), p1));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glTransformFeedbackVaryingsNV(int p0, java.nio.IntBuffer p1, int p2) {
        BridgeSupport.enqueueSnapshot(p1, snapshot -> org.lwjgl.opengl.NVTransformFeedback.glTransformFeedbackVaryingsNV(p0, snapshot.asIntBuffer(), p2));
    }
}
