// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.NVVertexBufferUnifiedMemory 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class NVVertexBufferUnifiedMemory {
    private NVVertexBufferUnifiedMemory() {
    }

    // 命令型
    public static void glBufferAddressRangeNV(int p0, int p1, long p2, long p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVVertexBufferUnifiedMemory.glBufferAddressRangeNV(p0, p1, p2, p3));
    }

    // 命令型
    public static void glColorFormatNV(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVVertexBufferUnifiedMemory.glColorFormatNV(p0, p1, p2));
    }

    // 命令型
    public static void glEdgeFlagFormatNV(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVVertexBufferUnifiedMemory.glEdgeFlagFormatNV(p0));
    }

    // 命令型
    public static void glFogCoordFormatNV(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVVertexBufferUnifiedMemory.glFogCoordFormatNV(p0, p1));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetIntegeruNV(int p0, int p1, java.nio.LongBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillLongs(p2, 16, buf -> org.lwjgl.opengl.NVVertexBufferUnifiedMemory.glGetIntegeruNV(p0, p1, buf)));
    }

    // 阻塞取值型
    public static long glGetIntegerui64NV(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVVertexBufferUnifiedMemory.glGetIntegerui64NV(p0, p1));
    }

    // 命令型
    public static void glIndexFormatNV(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVVertexBufferUnifiedMemory.glIndexFormatNV(p0, p1));
    }

    // 命令型
    public static void glNormalFormatNV(int p0, int p1) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVVertexBufferUnifiedMemory.glNormalFormatNV(p0, p1));
    }

    // 命令型
    public static void glSecondaryColorFormatNV(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVVertexBufferUnifiedMemory.glSecondaryColorFormatNV(p0, p1, p2));
    }

    // 命令型
    public static void glTexCoordFormatNV(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVVertexBufferUnifiedMemory.glTexCoordFormatNV(p0, p1, p2));
    }

    // 命令型
    public static void glVertexAttribFormatNV(int p0, int p1, int p2, boolean p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVVertexBufferUnifiedMemory.glVertexAttribFormatNV(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glVertexAttribIFormatNV(int p0, int p1, int p2, int p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVVertexBufferUnifiedMemory.glVertexAttribIFormatNV(p0, p1, p2, p3));
    }

    // 命令型
    public static void glVertexFormatNV(int p0, int p1, int p2) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVVertexBufferUnifiedMemory.glVertexFormatNV(p0, p1, p2));
    }
}
