// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；重新生成见 docs/design/gl-bridge-full-mirror.md
package github.kasuminova.ssoptimizer.bridge.opengl;

/**
 * org.lwjgl.opengl.NVVideoCapture 的 bridge 镜像（全量生成）。
 * <p>
 * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；
 * 语义与手写 bridge 类同构。
 */
public final class NVVideoCapture {
    private NVVideoCapture() {
    }

    // 命令型
    public static void glBeginVideoCaptureNV(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVVideoCapture.glBeginVideoCaptureNV(p0));
    }

    // 命令型
    public static void glBindVideoCaptureStreamBufferNV(int p0, int p1, int p2, long p3) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVVideoCapture.glBindVideoCaptureStreamBufferNV(p0, p1, p2, p3));
    }

    // 命令型
    public static void glBindVideoCaptureStreamTextureNV(int p0, int p1, int p2, int p3, int p4) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVVideoCapture.glBindVideoCaptureStreamTextureNV(p0, p1, p2, p3, p4));
    }

    // 命令型
    public static void glEndVideoCaptureNV(int p0) {
        BridgeSupport.enqueue(() -> org.lwjgl.opengl.NVVideoCapture.glEndVideoCaptureNV(p0));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetVideoCaptureNV(int p0, int p1, java.nio.IntBuffer p2) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p2, 16, buf -> org.lwjgl.opengl.NVVideoCapture.glGetVideoCaptureNV(p0, p1, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetVideoCaptureStreamNV(int p0, int p1, int p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillDoubles(p3, 16, buf -> org.lwjgl.opengl.NVVideoCapture.glGetVideoCaptureStreamNV(p0, p1, p2, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetVideoCaptureStreamNV(int p0, int p1, int p2, java.nio.FloatBuffer p3) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillFloats(p3, 16, buf -> org.lwjgl.opengl.NVVideoCapture.glGetVideoCaptureStreamNV(p0, p1, p2, buf)));
    }

    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）
    public static void glGetVideoCaptureStreamNV(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        BridgeSupport.blockingWait(() -> GetBufferFill.fillInts(p3, 16, buf -> org.lwjgl.opengl.NVVideoCapture.glGetVideoCaptureStreamNV(p0, p1, p2, buf)));
    }

    // 阻塞取值型
    public static double glGetVideoCaptureStreamdNV(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVVideoCapture.glGetVideoCaptureStreamdNV(p0, p1, p2));
    }

    // 阻塞取值型
    public static float glGetVideoCaptureStreamfNV(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVVideoCapture.glGetVideoCaptureStreamfNV(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetVideoCaptureStreamiNV(int p0, int p1, int p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVVideoCapture.glGetVideoCaptureStreamiNV(p0, p1, p2));
    }

    // 阻塞取值型
    public static int glGetVideoCaptureiNV(int p0, int p1) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVVideoCapture.glGetVideoCaptureiNV(p0, p1));
    }

    // 阻塞取值型
    public static int glVideoCaptureNV(int p0, java.nio.IntBuffer p1, java.nio.LongBuffer p2) {
        return BridgeSupport.blockingGet(() -> org.lwjgl.opengl.NVVideoCapture.glVideoCaptureNV(p0, p1, p2));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVideoCaptureStreamParameterNV(int p0, int p1, int p2, java.nio.DoubleBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.NVVideoCapture.glVideoCaptureStreamParameterNV(p0, p1, p2, snapshot.asDoubleBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVideoCaptureStreamParameterNV(int p0, int p1, int p2, java.nio.FloatBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.NVVideoCapture.glVideoCaptureStreamParameterNV(p0, p1, p2, snapshot.asFloatBuffer()));
    }

    // 快照命令型（录制时刻深拷贝）
    public static void glVideoCaptureStreamParameterNV(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        BridgeSupport.enqueueSnapshot(p3, snapshot -> org.lwjgl.opengl.NVVideoCapture.glVideoCaptureStreamParameterNV(p0, p1, p2, snapshot.asIntBuffer()));
    }
}
