#!/usr/bin/env python3
"""GL bridge 全量镜像生成器。

用法：python3 tools/gen_gl_bridge.py [lwjgl.jar 路径]
默认 jar：/mnt/store/Games/Starsector098-linux/lwjgl.jar

机制：javap 解析游戏 lwjgl.jar 的 org/lwjgl/opengl 包全部类，按
docs/design/gl-bridge-full-mirror.md 的分类规则为每个 GL 调用类生成 bridge
镜像源码，落盘到 modules/internal/sso-render/.../bridge/opengl/：

- 已有手写 bridge 的类（HANDWRITTEN）：生成基类 <Name>Gen.java，手写类
  extends 之——invokestatic 的方法解析先命中手写类自身声明，Gen 只兜底；
- 其余类：直接生成 final 入口类 <Name>.java。

生成物幂等覆写；目录中带生成标记但本次未再生成的文件会被删除（防 jar 换版残留）。
生成代码只经 BridgeSupport 的四条通道（enqueue/enqueueSnapshot/blockingWait/
blockingGet 及资源变体），命令体一律全限定名直调真实 GL，不 import。
"""

import re
import subprocess
import sys
import zipfile
from pathlib import Path

DEFAULT_JAR = '/mnt/store/Games/Starsector098-linux/lwjgl.jar'
PROJECT_ROOT = Path(__file__).resolve().parent.parent
BRIDGE_DIR = (PROJECT_ROOT / 'modules/internal/sso-render/src/main/java/'
              'github/kasuminova/ssoptimizer/bridge/opengl')
GENERATED_MARKER = ('// GENERATED by tools/gen_gl_bridge.py — 全量镜像生成物，勿手改；'
                    '重新生成见 docs/design/gl-bridge-full-mirror.md')

# 不镜像的窗口/平台/上下文基建类（只在启动期主线程窗口创建路径使用，
# 不属于模组渲染调用面；Display/GLContext/Util 维持既有手写镜像）
EXCLUDED = {
    'Display', 'GLContext', 'Util', 'AWTUtil', 'ContextGL', 'ContextGLES',
    'LinuxEvent', 'LinuxKeycodes', 'MacOSXNativeMouse', 'NVPresentVideoUtil',
    'NVVideoCaptureUtil', 'Pbuffer', 'Sync', 'WindowsDisplay', 'WindowsKeycodes',
    'XRandR',
}

# 已有手写 bridge 的 GL 调用类：生成 <Name>Gen.java 基类，手写类 extends 之。
# ARBCLEvent 唯一方法的签名含 GLSync 返回（跳过规则），手写类补齐，同样走 Gen 形态。
HANDWRITTEN = {
    'GL11', 'GL12', 'GL13', 'GL14', 'GL15', 'GL20', 'GL30', 'GL31', 'GL32', 'GL33',
    'GL40', 'GL41', 'GL42', 'GL43', 'GL44',
    'ARBVertexBufferObject', 'EXTFramebufferObject', 'ARBFramebufferObject',
    'ARBTextureStorage', 'ARBBindlessTexture', 'NVBindlessTexture',
    'ARBInstancedArrays', 'ARBDrawInstanced', 'ARBSync',
    'ARBCLEvent',
}

# 手写基建类（不生成，但属于 MIRRORED_CLASS_NAMES）
INFRA_HANDWRITTEN = ['Display', 'GLContext', 'Drawable', 'SharedDrawable', 'GLSync', 'Util']

BUFFER_TYPES = {
    'java.nio.IntBuffer', 'java.nio.ByteBuffer', 'java.nio.FloatBuffer',
    'java.nio.DoubleBuffer', 'java.nio.ShortBuffer', 'java.nio.LongBuffer',
}
# buffer 类型 → (GetBufferFill 填充方法, enqueueSnapshot 的 as 视图)
FILL_METHOD = {
    'java.nio.IntBuffer': 'fillInts',
    'java.nio.FloatBuffer': 'fillFloats',
    'java.nio.ByteBuffer': 'fillBooleans',
    'java.nio.DoubleBuffer': 'fillDoubles',
    'java.nio.LongBuffer': 'fillLongs',
}
SNAPSHOT_VIEW = {
    'java.nio.IntBuffer': 'asIntBuffer()',
    'java.nio.FloatBuffer': 'asFloatBuffer()',
    'java.nio.DoubleBuffer': 'asDoubleBuffer()',
    'java.nio.ShortBuffer': 'asShortBuffer()',
}
CALLBACK_TYPES = {
    'org.lwjgl.opengl.KHRDebugCallback',
    'org.lwjgl.opengl.AMDDebugOutputCallback',
    'org.lwjgl.opengl.ARBDebugOutputCallback',
}
SCALAR_TYPES = {'int', 'long', 'float', 'double', 'boolean', 'byte', 'short', 'char'}
STRING_TYPES = {'java.lang.CharSequence', 'java.lang.String'}
GLSYNC_TYPE = 'org.lwjgl.opengl.GLSync'

CLASS_HEADER_RE = re.compile(
    r'^(?:public\s+)?(?:final\s+|abstract\s+)?(?:class|interface)\s+'
    r'org\.lwjgl\.opengl\.(\w+)(?:\s+extends\s+([\w.]+))?')
METHOD_RE = re.compile(
    r'^\s+public static (?:final |native |synchronized |strictfp )*'
    r'([\w.\[\]]+) (\w+)\(([^)]*)\)( throws [^;]+)?;')


class Method:
    __slots__ = ('name', 'ret', 'params', 'throws')

    def __init__(self, name, ret, params, throws):
        self.name = name
        self.ret = ret
        self.params = params  # list[str]，javap 全限定类型
        self.throws = throws

    @property
    def key(self):
        return self.name, tuple(self.params)


class ClassInfo:
    def __init__(self, name, super_name):
        self.name = name
        self.super_name = super_name  # org/lwjgl/opengl 内超类简单名或 None
        self.methods = []


def parse_javap(jar, class_names):
    """批量 javap 解析全部类的 public static 方法与包内超类。"""
    infos = {}
    batch = 60
    for i in range(0, len(class_names), batch):
        fqns = ['org.lwjgl.opengl.' + c for c in class_names[i:i + batch]]
        result = subprocess.run(['javap', '-cp', jar] + fqns,
                                capture_output=True, text=True)
        if result.returncode != 0:
            raise RuntimeError('javap 执行失败: ' + result.stderr[:500])
        current = None
        for line in result.stdout.splitlines():
            header = CLASS_HEADER_RE.match(line)
            if header:
                name = header.group(1)
                super_fqn = header.group(2)
                super_name = None
                if super_fqn and super_fqn.startswith('org.lwjgl.opengl.'):
                    super_name = super_fqn[len('org.lwjgl.opengl.'):]
                current = ClassInfo(name, super_name)
                infos[name] = current
                continue
            if current is None:
                continue
            m = METHOD_RE.match(line)
            if m:
                params = [p.strip() for p in m.group(3).split(',') if p.strip()]
                current.methods.append(
                    Method(m.group(2), m.group(1), params, m.group(4)))
    return infos


def merged_methods(info, infos):
    """沿 org/lwjgl/opengl 包内超类链合并方法（子类优先，按 name+参数列表去重）。

    javac 记 owner 为编译期引用类：继承来的静态方法也必须出现在子类生成物里。
    """
    merged = {}
    chain = []
    current = info
    while current is not None:
        chain.append(current.name)
        for method in current.methods:
            merged.setdefault(method.key, method)
        current = infos.get(current.super_name) if current.super_name else None
    return list(merged.values()), chain


def classify(method):
    """按设计文档分类规则判定通道类别，返回 (类别, 备注)。类别：
    command / command_string / command_string_array / command_callback /
    get_fill / gen_resource / snapshot / passthrough / resource_get / value_get /
    skip_glsync / downgrade_longbuffer
    """
    types = list(method.params)
    if GLSYNC_TYPE in types or method.ret == GLSYNC_TYPE:
        return 'skip_glsync', '签名含 GLSync（对象身份类型，需手写）'
    buffers = [t for t in types if t in BUFFER_TYPES]
    callbacks = [t for t in types if t in CALLBACK_TYPES]
    is_void = method.ret == 'void'
    if is_void:
        if not buffers:
            if callbacks:
                return 'command_callback', None
            if 'java.lang.CharSequence[]' in types:
                return 'command_string_array', None
            return 'command_string' if any(t in STRING_TYPES for t in types) else 'command', None
        if len(buffers) == 1 and not callbacks:
            buf = buffers[0]
            others_ok = all(t in SCALAR_TYPES or t in STRING_TYPES or t in BUFFER_TYPES
                            for t in types)
            if others_ok:
                if method.name.startswith('glGet'):
                    if buf in FILL_METHOD:
                        return 'get_fill', None
                    return 'passthrough', 'ShortBuffer 无对应 fill，直通'
                if method.name.startswith('glGen'):
                    return 'gen_resource', None
                if buf == 'java.nio.LongBuffer':
                    return 'downgrade_longbuffer', 'enqueueSnapshot 无 LongBuffer 重载，降级直通'
                return 'snapshot', None
        return 'passthrough', '多缓冲/指针参数直传'
    if re.match(r'^gl(Gen|Create|New)', method.name):
        return 'resource_get', None
    return 'value_get', None


def render_method(owner, method, category):
    """生成单个镜像方法源码（4 空格缩进，不含尾部空行）。"""
    params_decl = ', '.join(f'{t} p{i}' for i, t in enumerate(method.params))
    args = ', '.join(f'p{i}' for i in range(len(method.params)))
    real = f'org.lwjgl.opengl.{owner}.{method.name}'
    sig = f'public static {method.ret} {method.name}({params_decl})'
    lines = []
    if category == 'command':
        lines.append('    // 命令型')
        lines.append(f'    {sig} {{')
        lines.append(f'        BridgeSupport.enqueue(() -> {real}({args}));')
    elif category == 'command_string':
        lines.append('    // 命令型（字符串捕获，不可变）')
        lines.append(f'    {sig} {{')
        lines.append(f'        BridgeSupport.enqueue(() -> {real}({args}));')
    elif category == 'command_string_array':
        idx = method.params.index('java.lang.CharSequence[]')
        lines.append('    // 命令型（字符串数组录制时刻快照）')
        lines.append(f'    {sig} {{')
        lines.append(f'        final java.lang.CharSequence[] copy = p{idx}.clone();')
        call_args = ', '.join('copy' if i == idx else f'p{i}'
                              for i in range(len(method.params)))
        lines.append(f'        BridgeSupport.enqueue(() -> {real}({call_args}));')
    elif category == 'command_callback':
        lines.append('    // 命令型（回调引用捕获，回调随后在渲染线程触发）')
        lines.append(f'    {sig} {{')
        lines.append(f'        BridgeSupport.enqueue(() -> {real}({args}));')
    elif category == 'get_fill':
        buf_idx = next(i for i, t in enumerate(method.params) if t in BUFFER_TYPES)
        fill = FILL_METHOD[method.params[buf_idx]]
        fill_args = ', '.join('buf' if i == buf_idx else f'p{i}'
                              for i in range(len(method.params)))
        lines.append('    // 缓冲填充 getter（绕过 LWJGL2 固定 remaining>=16 检查）')
        lines.append(f'    {sig} {{')
        lines.append(f'        BridgeSupport.blockingWait(() -> GetBufferFill.{fill}('
                     f'p{buf_idx}, 16, buf -> {real}({fill_args})));')
    elif category == 'gen_resource':
        lines.append('    // 阻塞资源型（glGen 族，不计 StallDetector）')
        lines.append(f'    {sig} {{')
        lines.append(f'        BridgeSupport.blockingWaitResource(() -> {real}({args}));')
    elif category == 'snapshot':
        buf_idx = next(i for i, t in enumerate(method.params) if t in BUFFER_TYPES)
        buf_type = method.params[buf_idx]
        view = 'snapshot' if buf_type == 'java.nio.ByteBuffer' \
            else f'snapshot.{SNAPSHOT_VIEW[buf_type]}'
        snap_args = ', '.join(view if i == buf_idx else f'p{i}'
                              for i in range(len(method.params)))
        lines.append('    // 快照命令型（录制时刻深拷贝）')
        lines.append(f'    {sig} {{')
        lines.append(f'        BridgeSupport.enqueueSnapshot(p{buf_idx}, '
                     f'snapshot -> {real}({snap_args}));')
    elif category == 'passthrough':
        lines.append('    // 阻塞直通型（阻塞期间 buffer/指针直传安全）')
        lines.append(f'    {sig} {{')
        lines.append(f'        BridgeSupport.blockingWait(() -> {real}({args}));')
    elif category == 'downgrade_longbuffer':
        lines.append('    // 阻塞直通型（降级：enqueueSnapshot 无 LongBuffer 重载）')
        lines.append(f'    {sig} {{')
        lines.append(f'        BridgeSupport.blockingWait(() -> {real}({args}));')
    elif category == 'resource_get':
        lines.append('    // 阻塞资源型（glGen/Create/New 族，不计 StallDetector）')
        lines.append(f'    {sig} {{')
        lines.append(f'        return BridgeSupport.blockingGetResource(() -> {real}({args}));')
    elif category == 'value_get':
        lines.append('    // 阻塞取值型')
        lines.append(f'    {sig} {{')
        lines.append(f'        return BridgeSupport.blockingGet(() -> {real}({args}));')
    else:
        raise AssertionError('未知类别: ' + category)
    lines.append('    }')
    return lines


def render_class(name, methods_with_category, handwritten):
    """生成整个类的源码文本。"""
    lines = [GENERATED_MARKER,
             'package github.kasuminova.ssoptimizer.bridge.opengl;',
             '']
    if handwritten:
        lines.append('/**')
        lines.append(f' * org.lwjgl.opengl.{name} 的 bridge 镜像生成基类（全量镜像兜底面）。')
        lines.append(' * <p>')
        lines.append(f' * 手写类 {{@link {name}}} extends 本类：invokestatic 的方法解析先命中手写类')
        lines.append(' * 自身声明（顶点流/状态仿真/id stash/map 仿真等精心语义），未覆盖的')
        lines.append(' * 落到本基类的通用录制/阻塞语义——手写永远优先，生成物只兜底。')
        lines.append(' */')
        lines.append(f'public class {name}Gen {{')
        lines.append(f'    protected {name}Gen() {{')
        lines.append('    }')
    else:
        lines.append('/**')
        lines.append(f' * org.lwjgl.opengl.{name} 的 bridge 镜像（全量生成）。')
        lines.append(f' * <p>')
        lines.append(' * 全部方法只经 BridgeSupport 的录制/阻塞通道，命令体直调真实 GL；')
        lines.append(' * 语义与手写 bridge 类同构。')
        lines.append(' */')
        lines.append(f'public final class {name} {{')
        lines.append(f'    private {name}() {{')
        lines.append('    }')
    for method, category in methods_with_category:
        lines.append('')
        lines.extend(render_method(name, method, category))
    lines.append('}')
    lines.append('')
    return '\n'.join(lines)


def main():
    jar = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_JAR
    if not Path(jar).is_file():
        raise SystemExit(f'lwjgl.jar 不存在: {jar}')

    with zipfile.ZipFile(jar) as z:
        class_names = sorted(
            n[len('org/lwjgl/opengl/'):-len('.class')] for n in z.namelist()
            if n.startswith('org/lwjgl/opengl/') and n.endswith('.class')
            and '$' not in n)
    infos = parse_javap(jar, class_names)

    # 目标类 = 合并（含包内超类链）后有 public static 方法的类。
    # 注意 ARBVertexBufferObject 自身只声明常量，方法全继承自 ARBBufferObject，
    # 按自身方法过滤会漏掉它（javac 记 owner 为编译期引用类，子类生成物必须包含
    # 继承来的方法）。
    merged_by_name = {name: merged_methods(info, infos)[0]
                      for name, info in infos.items()}
    targets = {name: infos[name] for name, merged in merged_by_name.items()
               if merged and name not in EXCLUDED}
    # 生成集不允许出现 throws（带 throws 的只应存在于排除的基建类）
    for name, info in sorted(targets.items()):
        for method in info.methods:
            if method.throws:
                raise SystemExit(
                    f'分类错误：生成集内出现 throws 方法 {name}.{method.name}{method.throws}')

    stats = {}
    skipped = []     # (类, 方法签名, 是否手写类)
    downgraded = []  # (类, 方法签名, 原因)
    generated_files = set()
    per_class_counts = {}
    for name in sorted(targets):
        info = targets[name]
        methods, chain = merged_methods(info, infos)
        kept = []
        for method in methods:
            category, note = classify(method)
            signature = (f'{method.name}({", ".join(method.params)})'
                         f' -> {method.ret}')
            if category == 'skip_glsync':
                skipped.append((name, signature, name in HANDWRITTEN))
                continue
            if note:
                downgraded.append((name, signature, note))
            kept.append((method, category))
        kept.sort(key=lambda mc: (mc[0].name, len(mc[0].params), mc[0].params))
        for _, category in kept:
            stats[category] = stats.get(category, 0) + 1
        file_name = f'{name}Gen.java' if name in HANDWRITTEN else f'{name}.java'
        generated_files.add(file_name)
        per_class_counts[file_name] = len(kept)
        (BRIDGE_DIR / file_name).write_text(
            render_class(name, kept, name in HANDWRITTEN), encoding='utf-8')

    # 幂等清理：带生成标记但本次未再生成的文件删除（jar 换版后不留残留）
    removed = []
    for path in BRIDGE_DIR.glob('*.java'):
        if path.name in generated_files:
            continue
        head = path.read_text(encoding='utf-8', errors='replace')[:300]
        if head.startswith('// GENERATED by tools/gen_gl_bridge.py'):
            path.unlink()
            removed.append(path.name)

    print(f'== 生成统计 ==')
    print(f'目标类 {len(targets)}（手写基类 {len(HANDWRITTEN & set(targets))}，'
          f'纯生成 {len(targets) - len(HANDWRITTEN & set(targets))}），'
          f'生成方法 {sum(per_class_counts.values())}')
    for category in sorted(stats):
        print(f'  {category}: {stats[category]}')
    if removed:
        print(f'清理残留生成物 {len(removed)}: {", ".join(sorted(removed))}')
    print(f'\n== GLSync 跳过清单（{len(skipped)}）==')
    for name, signature, is_handwritten in skipped:
        tag = '手写类内（可忽略）' if is_handwritten else '纯生成类内（需手写补齐）'
        print(f'  {name}.{signature}  [{tag}]')
    print(f'\n== 降级/直通备注清单（{len(downgraded)}）==')
    for name, signature, note in downgraded:
        print(f'  {name}.{signature}  [{note}]')

    mirrored = sorted(set(targets) | set(INFRA_HANDWRITTEN))
    print(f'\n== MIRRORED_CLASS_NAMES（{len(mirrored)}，粘进 RenderThreadRedirector）==')
    for i in range(0, len(mirrored), 6):
        print('            ' + ', '.join(f'"{n}"' for n in mirrored[i:i + 6])
              + (',' if i + 6 < len(mirrored) else ''))


if __name__ == '__main__':
    main()
